// src/components/onboarding/profile-step.tsx
'use client'

import { useState } from 'react'
import { useTranslations } from 'next-intl'
import { cn } from '@/lib/utils'
import { PRONOUNS_OPTIONS, TRANSITION_TYPES, OnboardingState } from '@/lib/onboarding'

interface ProfileStepProps {
  state: OnboardingState
  onUpdate: (profile: OnboardingState['profile']) => void
  onNext: () => void
  onSkip: () => void
}

export function ProfileStep({ state, onUpdate, onNext, onSkip }: ProfileStepProps) {
  const t = useTranslations('onboarding')
  const [pronouns, setPronouns] = useState(state.profile?.pronouns || '')
  const [transitionType, setTransitionType] = useState(state.profile?.transitionType || '')

  const handleNext = () => {
    const profile: OnboardingState['profile'] = {
      pronouns: pronouns || undefined,
      transitionType:
        (transitionType as 'mtf' | 'ftm' | 'non-binary' | 'other' | 'prefer-not-say') || undefined,
    }
    onUpdate(profile)
    onNext()
  }

  return (
    <div className="space-y-8 py-4">
      {/* Header */}
      <div className="space-y-2 text-center">
        <h2 className="text-foreground text-2xl font-bold">{t('profile.title')}</h2>
        <p className="text-muted-foreground">{t('profile.subtitle')}</p>
      </div>

      {/* Pronouns */}
      <div className="space-y-3">
        <label className="text-foreground text-sm font-medium">{t('profile.pronouns')}</label>
        <div className="flex flex-wrap gap-2">
          {PRONOUNS_OPTIONS.map((option) => (
            <button
              key={option.value}
              onClick={() => setPronouns(option.value)}
              className={cn(
                'rounded-full px-4 py-2 text-sm font-medium transition-all',
                'border-2',
                pronouns === option.value
                  ? 'border-primary bg-primary/10 text-primary'
                  : 'border-border bg-muted/30 text-muted-foreground hover:bg-muted'
              )}
            >
              {option.label}
            </button>
          ))}
        </div>
      </div>

      {/* Transition Type */}
      <div className="space-y-3">
        <label className="text-foreground text-sm font-medium">{t('profile.transitionType')}</label>
        <div className="space-y-2">
          {TRANSITION_TYPES.map((option) => (
            <button
              key={option.value}
              onClick={() => setTransitionType(option.value)}
              className={cn(
                'flex w-full items-center gap-3 rounded-xl p-3 text-left transition-all',
                'border-2',
                transitionType === option.value
                  ? 'border-primary bg-primary/10'
                  : 'border-border bg-muted/30 hover:bg-muted'
              )}
            >
              <span className="text-2xl">{option.emoji}</span>
              <span
                className={cn(
                  'font-medium',
                  transitionType === option.value ? 'text-primary' : 'text-foreground'
                )}
              >
                {option.label}
              </span>
            </button>
          ))}
        </div>
      </div>

      {/* Actions */}
      <div className="flex gap-3 pt-4">
        <button
          onClick={onSkip}
          className="text-muted-foreground bg-muted hover:bg-muted/80 flex-1 rounded-xl py-3 font-medium transition-colors"
        >
          {t('profile.skip')}
        </button>
        <button
          onClick={handleNext}
          className="gradient-trans-glow shadow-trans-glow hover:shadow-trans-glow-lg flex-1 rounded-xl py-3 font-medium text-white transition-all active:scale-[0.98]"
        >
          {t('profile.continue')}
        </button>
      </div>
    </div>
  )
}

// src/lib/components/onboarding/ProfileStep.svelte
<script lang="ts">
  import { i18n } from '$lib/i18n.svelte'
  import { PRONOUNS_OPTIONS, TRANSITION_TYPES, type OnboardingState } from '$lib/onboarding'

  let {
    onboardingState,
    onUpdate,
    onNext,
    onSkip,
  }: {
    onboardingState: OnboardingState
    onUpdate: (profile: OnboardingState['profile']) => void
    onNext: () => void
    onSkip: () => void
  } = $props()

  type TransitionType = NonNullable<OnboardingState['profile']>['transitionType']

  let pronouns = $state(onboardingState.profile?.pronouns ?? '')
  let transitionType = $state<TransitionType | ''>(onboardingState.profile?.transitionType ?? '')

  function handleNext() {
    onUpdate({
      pronouns: pronouns || undefined,
      transitionType: transitionType || undefined,
    })
    onNext()
  }
</script>

<div class="profile">
  <div class="head">
    <h2>{i18n.t('onboarding.profile.title')}</h2>
    <p class="subtitle">{i18n.t('onboarding.profile.subtitle')}</p>
  </div>

  <div class="field">
    <label for="pronouns-group">{i18n.t('onboarding.profile.pronouns')}</label>
    <div id="pronouns-group" class="pill-row">
      {#each PRONOUNS_OPTIONS as option (option.value)}
        <button
          type="button"
          class="pill"
          class:active={pronouns === option.value}
          onclick={() => (pronouns = option.value)}
        >
          {option.label}
        </button>
      {/each}
    </div>
  </div>

  <div class="field">
    <label for="transition-group">{i18n.t('onboarding.profile.transitionType')}</label>
    <div id="transition-group" class="option-list">
      {#each TRANSITION_TYPES as option (option.value)}
        <button
          type="button"
          class="option"
          class:active={transitionType === option.value}
          onclick={() => (transitionType = option.value as TransitionType)}
        >
          <span class="emoji">{option.emoji}</span>
          <span>{option.label}</span>
        </button>
      {/each}
    </div>
  </div>

  <div class="actions">
    <button type="button" class="btn-secondary" onclick={onSkip}>
      {i18n.t('onboarding.profile.skip')}
    </button>
    <button type="button" class="btn-primary" onclick={handleNext}>
      {i18n.t('onboarding.profile.continue')}
    </button>
  </div>
</div>

<style>
  .profile {
    display: flex;
    flex-direction: column;
    gap: 28px;
    padding: 12px 0;
  }
  .head {
    text-align: center;
    display: flex;
    flex-direction: column;
    gap: 6px;
  }
  h2 {
    font-size: 20px;
    font-weight: 700;
    margin: 0;
  }
  .subtitle {
    font-size: 12.5px;
    color: var(--ink-soft);
    margin: 0;
  }
  .field {
    display: flex;
    flex-direction: column;
    gap: 10px;
  }
  label {
    font-size: 13px;
    font-weight: 600;
  }
  .pill-row {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
  }
  .pill {
    padding: 8px 16px;
    border-radius: 999px;
    border: 2px solid var(--line);
    background: var(--bg);
    color: var(--ink-soft);
    font-family: inherit;
    font-size: 13px;
    font-weight: 600;
    cursor: pointer;
  }
  .pill.active {
    border-color: var(--blue-deep);
    background: color-mix(in srgb, var(--blue-deep) 12%, transparent);
    color: var(--ink);
  }
  .option-list {
    display: flex;
    flex-direction: column;
    gap: 8px;
  }
  .option {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 12px;
    border-radius: 14px;
    border: 2px solid var(--line);
    background: var(--bg);
    text-align: left;
    font-family: inherit;
    font-size: 13.5px;
    font-weight: 600;
    color: var(--ink);
    cursor: pointer;
  }
  .option.active {
    border-color: var(--blue-deep);
    background: color-mix(in srgb, var(--blue-deep) 10%, transparent);
    color: var(--blue-deep);
  }
  .emoji {
    font-size: 20px;
  }
  .actions {
    display: flex;
    gap: 10px;
  }
  .btn-secondary,
  .btn-primary {
    flex: 1;
    padding: 13px;
    border-radius: 14px;
    border: none;
    font-family: inherit;
    font-size: 14px;
    font-weight: 700;
    cursor: pointer;
  }
  .btn-secondary {
    background: var(--line);
    color: var(--ink-soft);
  }
  .btn-primary {
    background: linear-gradient(135deg, var(--blue-deep), var(--pink-deep));
    color: #fff;
  }
  .btn-secondary:active,
  .btn-primary:active {
    transform: scale(0.98);
  }
</style>
