// src/app/medications/history/page.tsx
'use client'

import { useState, useEffect, useMemo } from 'react'
import { useTranslations, useLocale } from 'next-intl'
import { getDateLocale } from '@/i18n/date-locale'
import type { Locale } from '@/i18n/config'
import Link from 'next/link'
import { format, subMonths, startOfMonth, endOfMonth } from 'date-fns'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover'
import { Calendar } from '@/components/ui/calendar'
import {
  ArrowLeft,
  History,
  Filter,
  Calendar as CalendarIcon,
  Pill,
  TrendingUp,
  Play,
  Square,
  RefreshCw,
} from 'lucide-react'
import { getTreatmentChanges, getMedications } from '@/lib/db'
import type { TreatmentChange, TreatmentChangeType, Medication } from '@/lib/types'
import {
  ChangeEntry,
  ChangeEntrySkeleton,
  changeTypeConfig,
} from '@/components/medications/change-entry'
import { cn } from '@/lib/utils'

type FilterType = 'all' | TreatmentChangeType
type MedicationFilter = 'all' | number

export default function TreatmentHistoryPage() {
  const t = useTranslations('medications')
  const tObj = useTranslations('objectives')
  const locale = useLocale()
  const dateLocale = getDateLocale(locale as Locale)
  const [changes, setChanges] = useState<TreatmentChange[]>([])
  const [medications, setMedications] = useState<Medication[]>([])
  const [loading, setLoading] = useState(true)

  // Filters
  const [typeFilter, setTypeFilter] = useState<FilterType>('all')
  const [medicationFilter, setMedicationFilter] = useState<MedicationFilter>('all')
  const [dateRange, setDateRange] = useState<{ from: Date; to: Date }>({
    from: subMonths(new Date(), 6),
    to: new Date(),
  })

  useEffect(() => {
    loadData()
  }, [])

  async function loadData() {
    setLoading(true)
    try {
      const [changesData, medsData] = await Promise.all([
        getTreatmentChanges(undefined, 500),
        getMedications(),
      ])
      setChanges(changesData)
      setMedications(medsData)
    } finally {
      setLoading(false)
    }
  }

  // Filtered changes
  const filteredChanges = useMemo(() => {
    return changes.filter((change) => {
      // Type filter
      if (typeFilter !== 'all' && change.changeType !== typeFilter) {
        return false
      }
      // Medication filter
      if (medicationFilter !== 'all' && change.medicationId !== medicationFilter) {
        return false
      }
      // Date range filter
      const changeDate = new Date(change.date)
      if (changeDate < dateRange.from || changeDate > dateRange.to) {
        return false
      }
      return true
    })
  }, [changes, typeFilter, medicationFilter, dateRange])

  // Stats
  const stats = useMemo(() => {
    const now = new Date()
    const thisMonth = changes.filter((c) => {
      const d = new Date(c.date)
      return d >= startOfMonth(now) && d <= endOfMonth(now)
    })

    const byType = changes.reduce(
      (acc, c) => {
        acc[c.changeType] = (acc[c.changeType] || 0) + 1
        return acc
      },
      {} as Record<string, number>
    )

    const uniqueMeds = new Set(changes.map((c) => c.medicationId)).size

    return {
      total: changes.length,
      thisMonth: thisMonth.length,
      uniqueMeds,
      mostCommon: Object.entries(byType).sort((a, b) => b[1] - a[1])[0],
    }
  }, [changes])

  // Group by month for display
  const groupedByMonth = useMemo(() => {
    return filteredChanges.reduce(
      (acc, change) => {
        const monthKey = format(new Date(change.date), 'yyyy-MM')
        if (!acc[monthKey]) {
          acc[monthKey] = []
        }
        acc[monthKey].push(change)
        return acc
      },
      {} as Record<string, TreatmentChange[]>
    )
  }, [filteredChanges])

  const sortedMonths = Object.keys(groupedByMonth).sort((a, b) => b.localeCompare(a))

  // Unique medication names for filter
  const uniqueMedicationNames = useMemo(() => {
    const seen = new Map<number, string>()
    changes.forEach((c) => {
      if (!seen.has(c.medicationId)) {
        seen.set(c.medicationId, c.medicationName)
      }
    })
    return Array.from(seen.entries())
  }, [changes])

  return (
    <div className="space-y-6 p-4 pb-24">
      {/* Header */}
      <div className="flex items-center gap-3 pt-2">
        <Link href="/medications">
          <Button variant="ghost" size="icon" className="shrink-0">
            <ArrowLeft className="h-5 w-5" />
          </Button>
        </Link>
        <div>
          <h1 className="text-foreground text-2xl font-bold">{t('history.title')}</h1>
          <p className="text-muted-foreground text-sm">{t('history.subtitle')}</p>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 gap-3">
        <Card>
          <CardContent className="p-3">
            <div className="flex items-center gap-2">
              <div className="bg-primary/10 rounded-lg p-2">
                <History className="text-primary h-4 w-4" />
              </div>
              <div>
                <p className="text-2xl font-bold">{stats.total}</p>
                <p className="text-muted-foreground text-xs">{t('history.totalChanges')}</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-3">
            <div className="flex items-center gap-2">
              <div className="bg-trans-blue/10 rounded-lg p-2">
                <CalendarIcon className="text-trans-blue h-4 w-4" />
              </div>
              <div>
                <p className="text-2xl font-bold">{stats.thisMonth}</p>
                <p className="text-muted-foreground text-xs">{t('history.thisMonth')}</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-3">
            <div className="flex items-center gap-2">
              <div className="bg-trans-pink/10 rounded-lg p-2">
                <Pill className="text-trans-pink h-4 w-4" />
              </div>
              <div>
                <p className="text-2xl font-bold">{stats.uniqueMeds}</p>
                <p className="text-muted-foreground text-xs">{t('history.trackedMeds')}</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-3">
            <div className="flex items-center gap-2">
              <div className="rounded-lg bg-purple-500/10 p-2">
                <TrendingUp className="h-4 w-4 text-purple-500" />
              </div>
              <div>
                <p className="truncate text-sm font-bold">
                  {stats.mostCommon ? tObj(`changeTypes.${stats.mostCommon[0]}`) : '-'}
                </p>
                <p className="text-muted-foreground text-xs">{t('history.mostCommon')}</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Filters */}
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="flex items-center gap-2 text-base">
            <Filter className="h-4 w-4" />
            {t('history.filters')}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <div className="grid grid-cols-2 gap-3">
            {/* Type filter */}
            <Select value={typeFilter} onValueChange={(v) => setTypeFilter(v as FilterType)}>
              <SelectTrigger>
                <SelectValue placeholder="Type" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">{t('history.allTypes')}</SelectItem>
                {Object.entries(changeTypeConfig).map(([key, config]) => {
                  const Icon = config.icon
                  return (
                    <SelectItem key={key} value={key}>
                      <div className="flex items-center gap-2">
                        <Icon className={`h-3 w-3 ${config.color}`} />
                        {tObj(`changeTypes.${key}`)}
                      </div>
                    </SelectItem>
                  )
                })}
              </SelectContent>
            </Select>

            {/* Medication filter */}
            <Select
              value={String(medicationFilter)}
              onValueChange={(v) => setMedicationFilter(v === 'all' ? 'all' : Number(v))}
            >
              <SelectTrigger>
                <SelectValue placeholder="Médicament" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">{t('history.allMeds')}</SelectItem>
                {uniqueMedicationNames.map(([id, name]) => (
                  <SelectItem key={id} value={String(id)}>
                    {name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* Date range */}
          <div className="flex gap-2">
            <Popover>
              <PopoverTrigger asChild>
                <Button
                  variant="outline"
                  className={cn(
                    'flex-1 justify-start text-left font-normal',
                    !dateRange.from && 'text-muted-foreground'
                  )}
                >
                  <CalendarIcon className="mr-2 h-4 w-4" />
                  {dateRange.from
                    ? format(dateRange.from, 'd MMM yyyy', { locale: dateLocale })
                    : t('history.start')}
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-auto p-0" align="start">
                <Calendar
                  mode="single"
                  selected={dateRange.from}
                  onSelect={(date) => date && setDateRange((prev) => ({ ...prev, from: date }))}
                  locale={dateLocale}
                  disabled={(date) => date > dateRange.to}
                />
              </PopoverContent>
            </Popover>
            <span className="text-muted-foreground self-center">→</span>
            <Popover>
              <PopoverTrigger asChild>
                <Button
                  variant="outline"
                  className={cn(
                    'flex-1 justify-start text-left font-normal',
                    !dateRange.to && 'text-muted-foreground'
                  )}
                >
                  <CalendarIcon className="mr-2 h-4 w-4" />
                  {dateRange.to
                    ? format(dateRange.to, 'd MMM yyyy', { locale: dateLocale })
                    : t('history.end')}
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-auto p-0" align="start">
                <Calendar
                  mode="single"
                  selected={dateRange.to}
                  onSelect={(date) => date && setDateRange((prev) => ({ ...prev, to: date }))}
                  locale={dateLocale}
                  disabled={(date) => date < dateRange.from}
                />
              </PopoverContent>
            </Popover>
          </div>

          {/* Quick filters */}
          <div className="flex flex-wrap gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={() =>
                setDateRange({
                  from: subMonths(new Date(), 1),
                  to: new Date(),
                })
              }
            >
              {t('history.lastMonth')}
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={() =>
                setDateRange({
                  from: subMonths(new Date(), 3),
                  to: new Date(),
                })
              }
            >
              {t('history.threeMonths')}
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={() =>
                setDateRange({
                  from: subMonths(new Date(), 6),
                  to: new Date(),
                })
              }
            >
              {t('history.sixMonths')}
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={() =>
                setDateRange({
                  from: subMonths(new Date(), 12),
                  to: new Date(),
                })
              }
            >
              {t('history.oneYear')}
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Results */}
      {loading ? (
        <div className="space-y-3">
          {[1, 2, 3, 4].map((i) => (
            <ChangeEntrySkeleton key={i} />
          ))}
        </div>
      ) : filteredChanges.length === 0 ? (
        <Card>
          <CardContent className="py-12 text-center">
            <History className="text-muted-foreground/50 mx-auto mb-4 h-12 w-12" />
            <h3 className="mb-2 text-lg font-medium">{t('history.noChanges')}</h3>
            <p className="text-muted-foreground mx-auto max-w-xs text-sm">
              {changes.length === 0 ? t('history.noChangesEmpty') : t('history.noChangesFiltered')}
            </p>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-6">
          <p className="text-muted-foreground text-sm">
            {filteredChanges.length} changement
            {filteredChanges.length > 1 ? 's' : ''} trouvé
            {filteredChanges.length > 1 ? 's' : ''}
          </p>

          {sortedMonths.map((monthKey) => {
            const monthChanges = groupedByMonth[monthKey]
            const monthDate = new Date(monthKey + '-01')

            return (
              <div key={monthKey} className="space-y-3">
                <h3 className="text-muted-foreground bg-background/95 sticky top-0 -mx-4 px-4 py-2 text-sm font-medium capitalize backdrop-blur-sm">
                  {format(monthDate, 'MMMM yyyy', { locale: dateLocale })}
                  <Badge variant="outline" className="ml-2">
                    {monthChanges.length}
                  </Badge>
                </h3>
                <div className="space-y-2">
                  {monthChanges.map((change) => (
                    <ChangeEntry key={change.id} change={change} />
                  ))}
                </div>
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}

// src/routes/medications/history/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { format, subMonths, startOfMonth, endOfMonth, endOfDay } from 'date-fns'
  import { i18n, getDateLocale } from '$lib/i18n.svelte'
  import { getTreatmentChanges } from '$lib/db'
  import type { TreatmentChange, TreatmentChangeType } from '$lib/types'
  import ChangeEntry, { changeTypeConfig } from '$lib/components/medications/ChangeEntry.svelte'
  import ArrowLeft from '@lucide/svelte/icons/arrow-left'
  import HistoryIcon from '@lucide/svelte/icons/history'
  import Filter from '@lucide/svelte/icons/filter'
  import CalendarIcon from '@lucide/svelte/icons/calendar'
  import PillIcon from '@lucide/svelte/icons/pill'
  import TrendingUp from '@lucide/svelte/icons/trending-up'

  type FilterType = 'all' | TreatmentChangeType
  type MedicationFilter = 'all' | number

  let changes = $state<TreatmentChange[]>([])
  let loading = $state(true)

  let typeFilter = $state<FilterType>('all')
  let medicationFilter = $state<MedicationFilter>('all')
  let rangeFrom = $state(subMonths(new Date(), 6).toISOString().split('T')[0]!)
  let rangeTo = $state(new Date().toISOString().split('T')[0]!)

  onMount(async () => {
    changes = await getTreatmentChanges(undefined, 500)
    loading = false
  })

  let dateLocale = $derived(getDateLocale(i18n.locale))

  let filteredChanges = $derived.by(() => {
    const from = new Date(rangeFrom)
    const to = endOfDay(new Date(rangeTo))
    return changes.filter((change) => {
      if (typeFilter !== 'all' && change.changeType !== typeFilter) return false
      if (medicationFilter !== 'all' && change.medicationId !== medicationFilter) return false
      const changeDate = new Date(change.date)
      if (changeDate < from || changeDate > to) return false
      return true
    })
  })

  let stats = $derived.by(() => {
    const now = new Date()
    const thisMonth = changes.filter((c) => {
      const d = new Date(c.date)
      return d >= startOfMonth(now) && d <= endOfMonth(now)
    })
    const byType = changes.reduce<Record<string, number>>((acc, c) => {
      acc[c.changeType] = (acc[c.changeType] || 0) + 1
      return acc
    }, {})
    const uniqueMeds = new Set(changes.map((c) => c.medicationId)).size
    const mostCommon = Object.entries(byType).sort((a, b) => b[1] - a[1])[0]
    return { total: changes.length, thisMonth: thisMonth.length, uniqueMeds, mostCommon }
  })

  let groupedByMonth = $derived.by(() => {
    const groups: Record<string, TreatmentChange[]> = {}
    for (const change of filteredChanges) {
      const monthKey = format(new Date(change.date), 'yyyy-MM')
      ;(groups[monthKey] ??= []).push(change)
    }
    return groups
  })

  let sortedMonths = $derived(Object.keys(groupedByMonth).sort((a, b) => b.localeCompare(a)))

  let uniqueMedicationNames = $derived.by(() => {
    const seen: Record<number, string> = {}
    for (const c of changes) {
      seen[c.medicationId] ??= c.medicationName
    }
    return Object.entries(seen).map(([id, name]) => [Number(id), name] as const)
  })

  function setRange(months: number) {
    rangeFrom = subMonths(new Date(), months).toISOString().split('T')[0]!
    rangeTo = new Date().toISOString().split('T')[0]!
  }
</script>

<div class="header">
  <a href="/medications" class="icon-link" aria-label={i18n.t('common.back')}
    ><ArrowLeft size={20} /></a
  >
  <div>
    <h1>{i18n.t('medications.history.title')}</h1>
    <p class="subtitle">{i18n.t('medications.history.subtitle')}</p>
  </div>
</div>

{#if loading}
  <p class="loading">{i18n.t('common.loading')}</p>
{:else}
  <div class="stats-grid">
    <div class="stat">
      <div class="stat-icon"><HistoryIcon size={16} /></div>
      <div>
        <p class="stat-num">{stats.total}</p>
        <p class="stat-label">{i18n.t('medications.history.totalChanges')}</p>
      </div>
    </div>
    <div class="stat">
      <div class="stat-icon"><CalendarIcon size={16} /></div>
      <div>
        <p class="stat-num">{stats.thisMonth}</p>
        <p class="stat-label">{i18n.t('medications.history.thisMonth')}</p>
      </div>
    </div>
    <div class="stat">
      <div class="stat-icon"><PillIcon size={16} /></div>
      <div>
        <p class="stat-num">{stats.uniqueMeds}</p>
        <p class="stat-label">{i18n.t('medications.history.trackedMeds')}</p>
      </div>
    </div>
    <div class="stat">
      <div class="stat-icon"><TrendingUp size={16} /></div>
      <div>
        <p class="stat-num truncate">
          {stats.mostCommon ? i18n.t(`objectives.changeTypes.${stats.mostCommon[0]}`) : '-'}
        </p>
        <p class="stat-label">{i18n.t('medications.history.mostCommon')}</p>
      </div>
    </div>
  </div>

  <div class="card">
    <p class="card-title"><Filter size={14} /> {i18n.t('medications.history.filters')}</p>

    <div class="filter-row">
      <select bind:value={typeFilter}>
        <option value="all">{i18n.t('medications.history.allTypes')}</option>
        {#each Object.keys(changeTypeConfig) as key (key)}
          <option value={key}>{i18n.t(`objectives.changeTypes.${key}`)}</option>
        {/each}
      </select>

      <select
        value={String(medicationFilter)}
        onchange={(e) =>
          (medicationFilter =
            e.currentTarget.value === 'all' ? 'all' : Number(e.currentTarget.value))}
      >
        <option value="all">{i18n.t('medications.history.allMeds')}</option>
        {#each uniqueMedicationNames as [id, name] (id)}
          <option value={String(id)}>{name}</option>
        {/each}
      </select>
    </div>

    <div class="filter-row">
      <div class="field">
        <label for="rangeFrom">{i18n.t('medications.history.start')}</label>
        <input id="rangeFrom" type="date" bind:value={rangeFrom} max={rangeTo} />
      </div>
      <div class="field">
        <label for="rangeTo">{i18n.t('medications.history.end')}</label>
        <input id="rangeTo" type="date" bind:value={rangeTo} min={rangeFrom} />
      </div>
    </div>

    <div class="quick-filters">
      <button type="button" class="chip-btn" onclick={() => setRange(1)}
        >{i18n.t('medications.history.lastMonth')}</button
      >
      <button type="button" class="chip-btn" onclick={() => setRange(3)}
        >{i18n.t('medications.history.threeMonths')}</button
      >
      <button type="button" class="chip-btn" onclick={() => setRange(6)}
        >{i18n.t('medications.history.sixMonths')}</button
      >
      <button type="button" class="chip-btn" onclick={() => setRange(12)}
        >{i18n.t('medications.history.oneYear')}</button
      >
    </div>
  </div>

  {#if filteredChanges.length === 0}
    <div class="empty-card">
      <HistoryIcon size={40} />
      <h3>{i18n.t('medications.history.noChanges')}</h3>
      <p>
        {changes.length === 0
          ? i18n.t('medications.history.noChangesEmpty')
          : i18n.t('medications.history.noChangesFiltered')}
      </p>
    </div>
  {:else}
    <p class="result-count">
      {filteredChanges.length}
      {filteredChanges.length > 1
        ? i18n.t('medications.history.changes')
        : i18n.t('medications.history.change')}
      {filteredChanges.length > 1
        ? i18n.t('medications.history.foundPlural')
        : i18n.t('medications.history.found')}
    </p>

    {#each sortedMonths as monthKey (monthKey)}
      {@const monthChanges = groupedByMonth[monthKey]!}
      {@const monthDate = new Date(monthKey + '-01')}
      <div class="month-group">
        <h3 class="month-title">
          {format(monthDate, 'MMMM yyyy', { locale: dateLocale })}
          <span class="month-count">{monthChanges.length}</span>
        </h3>
        <div class="entries">
          {#each monthChanges as change (change.id)}
            <ChangeEntry {change} />
          {/each}
        </div>
      </div>
    {/each}
  {/if}
{/if}

<style>
  .loading {
    color: var(--ink-soft);
    text-align: center;
    padding: 40px 0;
  }
  .header {
    display: flex;
    align-items: center;
    gap: 10px;
    margin-bottom: 18px;
  }
  h1 {
    font-size: 19px;
    font-weight: 700;
    margin: 0;
  }
  .subtitle {
    font-size: 12.5px;
    color: var(--ink-soft);
    margin: 2px 0 0;
  }
  .icon-link {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 36px;
    height: 36px;
    border-radius: 10px;
    color: var(--ink);
    text-decoration: none;
    flex-shrink: 0;
  }
  .stats-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 10px;
    margin-bottom: 14px;
  }
  .stat {
    display: flex;
    align-items: center;
    gap: 8px;
    background: var(--bg);
    border: 1px solid var(--line);
    border-radius: 12px;
    padding: 10px;
  }
  .stat-icon {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 32px;
    height: 32px;
    border-radius: 9px;
    background: var(--page);
    flex-shrink: 0;
  }
  .stat-num {
    font-size: 18px;
    font-weight: 700;
    margin: 0;
  }
  .stat-num.truncate {
    font-size: 13px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    max-width: 100px;
  }
  .stat-label {
    font-size: 10.5px;
    color: var(--ink-soft);
    margin: 1px 0 0;
  }
  .card {
    background: var(--bg);
    border: 1px solid var(--line);
    border-radius: 16px;
    padding: 14px;
    margin-bottom: 14px;
  }
  .card-title {
    display: flex;
    align-items: center;
    gap: 6px;
    font-size: 13px;
    font-weight: 600;
    margin: 0 0 12px;
  }
  .filter-row {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 10px;
    margin-bottom: 10px;
  }
  select,
  input {
    width: 100%;
    padding: 9px 10px;
    border: 1px solid var(--line);
    border-radius: 9px;
    background: var(--page);
    color: var(--ink);
    font-family: inherit;
    font-size: 13px;
  }
  label {
    display: block;
    font-size: 11.5px;
    color: var(--ink-soft);
    margin-bottom: 4px;
  }
  .quick-filters {
    display: flex;
    flex-wrap: wrap;
    gap: 6px;
  }
  .chip-btn {
    padding: 6px 12px;
    border-radius: 999px;
    border: 1px solid var(--line);
    background: var(--page);
    color: var(--ink);
    font-family: inherit;
    font-size: 12px;
    cursor: pointer;
  }
  .empty-card {
    text-align: center;
    padding: 40px 16px;
    border: 1px solid var(--line);
    border-radius: 16px;
    color: var(--ink-faint);
  }
  .empty-card h3 {
    font-size: 15px;
    color: var(--ink);
    margin: 12px 0 6px;
  }
  .empty-card p {
    font-size: 13px;
    color: var(--ink-soft);
    margin: 0;
  }
  .result-count {
    font-size: 12.5px;
    color: var(--ink-soft);
    margin: 0 0 12px;
  }
  .month-group {
    margin-bottom: 18px;
  }
  .month-title {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 13px;
    font-weight: 600;
    color: var(--ink-soft);
    text-transform: capitalize;
    margin: 0 0 10px;
  }
  .month-count {
    font-size: 11px;
    padding: 2px 8px;
    border-radius: 999px;
    border: 1px solid var(--line);
    color: var(--ink-soft);
  }
  .entries {
    display: flex;
    flex-direction: column;
    gap: 8px;
  }
</style>
