// src/components/objectives/objective-card.tsx
'use client'

import Link from 'next/link'
import { useLocale, useTranslations } from 'next-intl'
import { getDateLocale } from '@/i18n/date-locale'
import type { Locale } from '@/i18n/config'
import { format } from 'date-fns'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Progress } from '@/components/ui/progress'
import {
  Stethoscope,
  FileText,
  Users,
  Activity,
  Heart,
  ChevronRight,
  Calendar,
  CheckCircle2,
  Clock,
  Pause,
  XCircle,
} from 'lucide-react'
import type { Objective, ObjectiveCategory, ObjectiveStatus } from '@/lib/types'

// Category configuration
export const categoryConfig: Record<
  ObjectiveCategory,
  { label: string; icon: typeof Stethoscope; color: string; bgColor: string }
> = {
  medical: {
    label: 'Médical',
    icon: Stethoscope,
    color: 'text-trans-pink',
    bgColor: 'bg-trans-pink/20',
  },
  administrative: {
    label: 'Administratif',
    icon: FileText,
    color: 'text-trans-blue',
    bgColor: 'bg-trans-blue/20',
  },
  social: {
    label: 'Social',
    icon: Users,
    color: 'text-blue-400',
    bgColor: 'bg-blue-400/20',
  },
  physical: {
    label: 'Physique',
    icon: Activity,
    color: 'text-pink-400',
    bgColor: 'bg-pink-400/20',
  },
  mental: {
    label: 'Mental',
    icon: Heart,
    color: 'text-rose-300',
    bgColor: 'bg-rose-300/20',
  },
}

// Status configuration
export const statusConfig: Record<
  ObjectiveStatus,
  { label: string; icon: typeof Clock; color: string; bgColor: string }
> = {
  not_started: {
    label: 'not_started',
    icon: Clock,
    color: 'text-muted-foreground',
    bgColor: 'bg-muted',
  },
  in_progress: {
    label: 'in_progress',
    icon: Activity,
    color: 'text-trans-blue',
    bgColor: 'bg-trans-blue/20',
  },
  completed: {
    label: 'completed',
    icon: CheckCircle2,
    color: 'text-green-500',
    bgColor: 'bg-green-500/20',
  },
  paused: {
    label: 'paused',
    icon: Pause,
    color: 'text-yellow-500',
    bgColor: 'bg-yellow-500/20',
  },
  cancelled: {
    label: 'cancelled',
    icon: XCircle,
    color: 'text-red-500',
    bgColor: 'bg-red-500/20',
  },
}

interface ObjectiveCardProps {
  objective: Objective
  milestonesCount?: number
  milestonesCompleted?: number
}

export function ObjectiveCard({
  objective,
  milestonesCount = 0,
  milestonesCompleted = 0,
}: ObjectiveCardProps) {
  const locale = useLocale()
  const t = useTranslations('objectives')
  const dateLocale = getDateLocale(locale as Locale)
  const category = categoryConfig[objective.category]
  const status = statusConfig[objective.status]
  const CategoryIcon = category.icon
  const StatusIcon = status.icon

  const progress =
    objective.progress ??
    (milestonesCount > 0 ? Math.round((milestonesCompleted / milestonesCount) * 100) : 0)

  return (
    <Link href={`/objectives/${objective.id}`}>
      <Card className="cursor-pointer transition-shadow hover:shadow-md">
        <CardContent className="p-4">
          <div className="flex items-start gap-3">
            {/* Category icon */}
            <div className={`rounded-lg p-2 ${category.bgColor} shrink-0`}>
              <CategoryIcon className={`h-5 w-5 ${category.color}`} />
            </div>

            {/* Content */}
            <div className="min-w-0 flex-1">
              <div className="mb-1 flex items-center gap-2">
                <h3 className="text-foreground truncate font-semibold">{objective.title}</h3>
                <ChevronRight className="text-muted-foreground h-4 w-4 shrink-0" />
              </div>

              {objective.description && (
                <p className="text-muted-foreground mb-2 line-clamp-2 text-sm">
                  {objective.description}
                </p>
              )}

              {/* Badges */}
              <div className="mb-3 flex flex-wrap gap-2">
                <Badge variant="outline" className={`${status.bgColor} border-0`}>
                  <StatusIcon className={`mr-1 h-3 w-3 ${status.color}`} />
                  <span className={status.color}>{t(`detail.statuses.${objective.status}`)}</span>
                </Badge>

                <Badge variant="outline" className="text-muted-foreground">
                  {category.label}
                </Badge>
              </div>

              {/* Progress bar */}
              {(objective.status === 'in_progress' || objective.status === 'completed') && (
                <div className="space-y-1">
                  <div className="text-muted-foreground flex justify-between text-xs">
                    <span>{progress}%</span>
                    {milestonesCount > 0 && (
                      <span>
                        {milestonesCompleted}/{milestonesCount} étapes
                      </span>
                    )}
                  </div>
                  <Progress value={progress} className="h-2" />
                </div>
              )}

              {/* Target date */}
              {objective.targetDate && objective.status !== 'completed' && (
                <div className="text-muted-foreground mt-2 flex items-center gap-1 text-xs">
                  <Calendar className="h-3 w-3" />
                  <span>
                    Objectif:{' '}
                    {format(new Date(objective.targetDate), 'd MMM yyyy', { locale: dateLocale })}
                  </span>
                </div>
              )}

              {/* Completed date */}
              {objective.completedDate && objective.status === 'completed' && (
                <div className="mt-2 flex items-center gap-1 text-xs text-green-500">
                  <CheckCircle2 className="h-3 w-3" />
                  <span>
                    {t('detail.completedOn')}{' '}
                    {format(new Date(objective.completedDate), 'd MMM yyyy', {
                      locale: dateLocale,
                    })}
                  </span>
                </div>
              )}
            </div>
          </div>
        </CardContent>
      </Card>
    </Link>
  )
}

// Skeleton for loading state
export function ObjectiveCardSkeleton() {
  return (
    <Card>
      <CardContent className="p-4">
        <div className="flex items-start gap-3">
          <div className="bg-muted h-9 w-9 animate-pulse rounded-lg" />
          <div className="flex-1 space-y-2">
            <div className="bg-muted h-5 w-3/4 animate-pulse rounded" />
            <div className="bg-muted h-4 w-full animate-pulse rounded" />
            <div className="flex gap-2">
              <div className="bg-muted h-5 w-20 animate-pulse rounded" />
              <div className="bg-muted h-5 w-16 animate-pulse rounded" />
            </div>
            <div className="bg-muted h-2 w-full animate-pulse rounded" />
          </div>
        </div>
      </CardContent>
    </Card>
  )
}

// src/lib/components/objectives/ObjectiveCard.svelte
<script module lang="ts">
  import type { ObjectiveCategory, ObjectiveStatus } from '$lib/types'
  import Stethoscope from '@lucide/svelte/icons/stethoscope'
  import FileText from '@lucide/svelte/icons/file-text'
  import Users from '@lucide/svelte/icons/users'
  import Activity from '@lucide/svelte/icons/activity'
  import Heart from '@lucide/svelte/icons/heart'
  import Clock from '@lucide/svelte/icons/clock'
  import CheckCircle2 from '@lucide/svelte/icons/check-circle-2'
  import Pause from '@lucide/svelte/icons/pause'
  import XCircle from '@lucide/svelte/icons/x-circle'

  export const categoryConfig: Record<
    ObjectiveCategory,
    { icon: typeof Stethoscope; color: string }
  > = {
    medical: { icon: Stethoscope, color: 'var(--pink-deep)' },
    administrative: { icon: FileText, color: 'var(--blue-deep)' },
    social: { icon: Users, color: 'var(--blue)' },
    physical: { icon: Activity, color: 'var(--pink)' },
    mental: { icon: Heart, color: 'var(--gold)' },
  }

  export const statusConfig: Record<ObjectiveStatus, { icon: typeof Clock; color: string }> = {
    not_started: { icon: Clock, color: 'var(--ink-soft)' },
    in_progress: { icon: Activity, color: 'var(--blue-deep)' },
    completed: { icon: CheckCircle2, color: 'var(--ok)' },
    paused: { icon: Pause, color: 'var(--watch)' },
    cancelled: { icon: XCircle, color: 'var(--alert)' },
  }
</script>

<script lang="ts">
  import { i18n, getDateLocale } from '$lib/i18n.svelte'
  import { format } from 'date-fns'
  import type { Objective } from '$lib/types'
  import ChevronRight from '@lucide/svelte/icons/chevron-right'
  import CalendarIcon from '@lucide/svelte/icons/calendar'

  let {
    objective,
    milestonesCount = 0,
    milestonesCompleted = 0,
  }: {
    objective: Objective
    milestonesCount?: number
    milestonesCompleted?: number
  } = $props()

  let category = $derived(categoryConfig[objective.category])
  let status = $derived(statusConfig[objective.status])
  let progress = $derived(
    objective.progress ??
      (milestonesCount > 0 ? Math.round((milestonesCompleted / milestonesCount) * 100) : 0)
  )
</script>

<a href={`/objectives/${objective.id}`} class="card">
  <div
    class="icon-wrap"
    style:background={`color-mix(in srgb, ${category.color} 16%, transparent)`}
  >
    <category.icon size={18} color={category.color} />
  </div>
  <div class="content">
    <div class="title-row">
      <h3>{objective.title}</h3>
      <ChevronRight size={16} class="chevron" />
    </div>
    {#if objective.description}
      <p class="description">{objective.description}</p>
    {/if}
    <div class="badges">
      <span class="badge" style:color={status.color}>
        <status.icon size={12} />
        {i18n.t(`objectives.detail.statuses.${objective.status}`)}
      </span>
      <span class="badge muted">{i18n.t(`objectives.categories.${objective.category}`)}</span>
    </div>
    {#if objective.status === 'in_progress' || objective.status === 'completed'}
      <div class="progress-row">
        <div class="progress-track">
          <div class="progress-fill" style:width={`${progress}%`}></div>
        </div>
        <span class="progress-txt"
          >{progress}%{#if milestonesCount > 0}
            &middot; {milestonesCompleted}/{milestonesCount} {i18n.t('objectives.steps')}{/if}</span
        >
      </div>
    {/if}
    {#if objective.targetDate && objective.status !== 'completed'}
      <div class="date-line">
        <CalendarIcon size={12} />
        {i18n.t('objectives.detail.target')}: {format(
          new Date(objective.targetDate),
          'd MMM yyyy',
          {
            locale: getDateLocale(i18n.locale),
          }
        )}
      </div>
    {/if}
    {#if objective.completedDate && objective.status === 'completed'}
      <div class="date-line done">
        <CheckCircle2 size={12} />
        {i18n.t('objectives.detail.completedOn')}
        {format(new Date(objective.completedDate), 'd MMM yyyy', {
          locale: getDateLocale(i18n.locale),
        })}
      </div>
    {/if}
  </div>
</a>

<style>
  .card {
    display: flex;
    align-items: flex-start;
    gap: 12px;
    border: 1px solid var(--line);
    border-radius: 16px;
    padding: 14px;
    background: var(--bg);
    text-decoration: none;
    color: inherit;
  }
  .icon-wrap {
    flex-shrink: 0;
    width: 36px;
    height: 36px;
    border-radius: 10px;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  .content {
    flex: 1;
    min-width: 0;
  }
  .title-row {
    display: flex;
    align-items: center;
    gap: 6px;
  }
  h3 {
    flex: 1;
    min-width: 0;
    font-size: 14.5px;
    font-weight: 600;
    margin: 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  .card :global(.chevron) {
    color: var(--ink-soft);
    flex-shrink: 0;
  }
  .description {
    font-size: 12.5px;
    color: var(--ink-soft);
    margin: 4px 0 0;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    line-clamp: 2;
    -webkit-box-orient: vertical;
    overflow: hidden;
  }
  .badges {
    display: flex;
    flex-wrap: wrap;
    gap: 6px;
    margin-top: 8px;
  }
  .badge {
    display: inline-flex;
    align-items: center;
    gap: 4px;
    font-size: 11px;
    font-weight: 600;
  }
  .badge.muted {
    color: var(--ink-soft);
  }
  .progress-row {
    margin-top: 8px;
  }
  .progress-track {
    height: 5px;
    background: var(--line);
    border-radius: 3px;
    overflow: hidden;
  }
  .progress-fill {
    height: 100%;
    background: linear-gradient(90deg, var(--blue-deep), var(--pink-deep));
    transition: width 0.4s ease;
  }
  .progress-txt {
    display: block;
    font-size: 11px;
    color: var(--ink-soft);
    margin-top: 4px;
  }
  .date-line {
    display: flex;
    align-items: center;
    gap: 4px;
    font-size: 11.5px;
    color: var(--ink-soft);
    margin-top: 8px;
  }
  .date-line.done {
    color: var(--ok);
  }
</style>
