// src/routes/progress/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { format, differenceInDays } from 'date-fns'
  import { i18n, getDateLocale } from '$lib/i18n.svelte'
  import { getPhysicalProgress, getUserProfile } from '$lib/db'
  import type { PhysicalProgress } from '$lib/types'
  import ProgressChart from '$lib/components/progress/ProgressChart.svelte'
  import ExportButton from '$lib/components/ui/ExportButton.svelte'
  import {
    availableMeasurements,
    measurementDiff,
    MEASUREMENT_UNITS,
    MEASUREMENT_LABEL_KEY,
    MEASUREMENT_CHART_COLOR,
    BODY_MEASUREMENT_KEYS,
  } from '$lib/components/progress/progress-charts'
  import Plus from '@lucide/svelte/icons/plus'
  import ArrowLeftRight from '@lucide/svelte/icons/arrow-left-right'
  import TrendingUp from '@lucide/svelte/icons/trending-up'
  import ListIcon from '@lucide/svelte/icons/list'
  import ImageIcon from '@lucide/svelte/icons/image'
  import Ruler from '@lucide/svelte/icons/ruler'
  import Camera from '@lucide/svelte/icons/camera'
  import ChevronRight from '@lucide/svelte/icons/chevron-right'

  let entries = $state<PhysicalProgress[]>([])
  let loading = $state(true)
  let activeTab = $state<'timeline' | 'charts' | 'photos'>('timeline')
  let userName = $state<string | undefined>()
  let chartRef = $state<HTMLDivElement>()

  onMount(async () => {
    const [entriesData, profile] = await Promise.all([getPhysicalProgress(50), getUserProfile()])
    entries = entriesData
    if (profile?.firstName) {
      userName = profile.firstName
    }
    loading = false
  })

  let available = $derived(availableMeasurements(entries))
  let bodyMeasurements = $derived(
    available.filter((k) =>
      BODY_MEASUREMENT_KEYS.includes(k as (typeof BODY_MEASUREMENT_KEYS)[number])
    )
  )
  let entriesWithPhotos = $derived(entries.filter((e) => e.photos && e.photos.length > 0))
  let totalPhotos = $derived(entries.reduce((acc, e) => acc + (e.photos?.length ?? 0), 0))
  let firstEntry = $derived([...entries].reverse()[0])
  let lastEntry = $derived(entries[0])
  let daysTracked = $derived(
    firstEntry && lastEntry && firstEntry !== lastEntry
      ? differenceInDays(new Date(lastEntry.date), new Date(firstEntry.date))
      : 0
  )

  let bodyExportData = $derived(
    bodyMeasurements
      .map((key) => {
        const last = lastEntry?.measurements?.[key]
        if (last === undefined) return null
        return {
          marker: key,
          label: i18n.t(MEASUREMENT_LABEL_KEY[key]),
          value: last,
          unit: MEASUREMENT_UNITS[key],
        }
      })
      .filter((d): d is NonNullable<typeof d> => d !== null)
  )
</script>

<div class="header">
  <div>
    <h1>{i18n.t('progress.title')}</h1>
    <p class="subtitle">
      {entries.length}
      {entries.length > 1 ? i18n.t('progress.entries') : i18n.t('progress.entry')}
    </p>
  </div>
  <div class="header-actions">
    <a href="/progress/compare" class="icon-link" aria-label={i18n.t('progress.compare.title')}>
      <ArrowLeftRight size={18} />
    </a>
    <a href="/progress/new" class="btn-primary-sm">
      <Plus size={16} />
      {i18n.t('progress.add')}
    </a>
  </div>
</div>

{#if loading}
  <p class="loading">{i18n.t('common.loading')}</p>
{:else if entries.length === 0}
  <div class="empty-card">
    <TrendingUp size={28} />
    <h3>{i18n.t('progress.noEntries')}</h3>
    <p>{i18n.t('progress.noEntriesDesc')}</p>
    <a href="/progress/new" class="btn-primary-sm">
      <Plus size={16} />
      {i18n.t('progress.addEntry')}
    </a>
  </div>
{:else}
  <div class="tabs">
    <button
      type="button"
      class:active={activeTab === 'timeline'}
      onclick={() => (activeTab = 'timeline')}
    >
      <ListIcon size={15} />
      {i18n.t('progress.tabs.timeline')}
    </button>
    <button
      type="button"
      class:active={activeTab === 'charts'}
      onclick={() => (activeTab = 'charts')}
    >
      <TrendingUp size={15} />
      {i18n.t('progress.tabs.charts')}
    </button>
    <button
      type="button"
      class:active={activeTab === 'photos'}
      onclick={() => (activeTab = 'photos')}
    >
      <ImageIcon size={15} />
      {i18n.t('progress.tabs.photos')}
    </button>
  </div>

  {#if activeTab === 'timeline'}
    <div class="stats-row">
      <div class="stat-card">
        <p class="stat-value">{entries.length}</p>
        <p class="stat-label">{i18n.t('progress.stats.entries')}</p>
      </div>
      <div class="stat-card">
        <p class="stat-value">{totalPhotos}</p>
        <p class="stat-label">{i18n.t('progress.stats.photos')}</p>
      </div>
      <div class="stat-card">
        <p class="stat-value">{daysTracked}</p>
        <p class="stat-label">{i18n.t('progress.stats.days')}</p>
      </div>
    </div>

    <div class="entry-list">
      {#each entries as entry (entry.id)}
        <a href={`/progress/${entry.id}`} class="entry-card">
          <div class="entry-thumb">
            {#if entry.photos && entry.photos.length > 0}
              <img src={entry.photos[0]} alt="" />
            {:else}
              <Ruler size={22} />
            {/if}
          </div>
          <div class="entry-body">
            <p class="entry-date">
              {format(new Date(entry.date), 'd MMMM yyyy', { locale: getDateLocale(i18n.locale) })}
            </p>
            <div class="entry-badges">
              {#if entry.photos && entry.photos.length > 0}
                <span class="badge"><Camera size={11} /> {entry.photos.length}</span>
              {/if}
              {#if entry.measurements && Object.keys(entry.measurements).length > 0}
                <span class="badge"
                  ><Ruler size={11} /> {Object.keys(entry.measurements).length}</span
                >
              {/if}
              {#each (entry.tags ?? []).slice(0, 2) as tag (tag)}
                <span class="badge">{tag}</span>
              {/each}
            </div>
          </div>
          <ChevronRight size={18} class="chevron" />
        </a>
      {/each}
    </div>
  {:else if activeTab === 'charts'}
    {#if available.length === 0}
      <p class="empty-note">{i18n.t('progress.noMeasurements')}</p>
    {:else}
      {#if bodyMeasurements.length > 0}
        <div class="card">
          <div class="card-head">
            <p class="card-title">{i18n.t('progress.bodyMeasurements')}</p>
            <ExportButton
              {chartRef}
              title={i18n.t('progress.bodyEvolution')}
              subtitle={i18n.t('progress.measurementsLabel')}
              {userName}
              data={bodyExportData}
            />
          </div>
          <div bind:this={chartRef}>
            <ProgressChart
              {entries}
              series={bodyMeasurements.map((key) => ({
                key,
                label: i18n.t(MEASUREMENT_LABEL_KEY[key]),
                unit: MEASUREMENT_UNITS[key],
                color: MEASUREMENT_CHART_COLOR[key]!,
              }))}
            />
          </div>
        </div>
      {/if}

      {#if available.includes('weight')}
        <div class="card">
          <p class="card-title">{i18n.t('progress.weightLabel')}</p>
          <ProgressChart
            {entries}
            series={[
              {
                key: 'weight',
                label: i18n.t(MEASUREMENT_LABEL_KEY.weight),
                unit: MEASUREMENT_UNITS.weight,
                color: MEASUREMENT_CHART_COLOR.weight!,
              },
            ]}
          />
        </div>
      {/if}

      {#if firstEntry && lastEntry && firstEntry.id !== lastEntry.id}
        <div class="card">
          <p class="card-title">{i18n.t('progress.evolution')}</p>
          <div class="evolution-list">
            {#each available as key (key)}
              {@const diff = measurementDiff(
                firstEntry.measurements?.[key],
                lastEntry.measurements?.[key]
              )}
              {#if diff !== undefined}
                <div class="evolution-row">
                  <span class="evolution-label">{i18n.t(MEASUREMENT_LABEL_KEY[key])}</span>
                  <span class="evolution-value">
                    {firstEntry.measurements?.[key]} → {lastEntry.measurements?.[key]}
                    {MEASUREMENT_UNITS[key]}
                    <span class="evolution-diff" class:up={diff > 0} class:down={diff < 0}>
                      {diff > 0 ? '+' : ''}{diff.toFixed(1)}
                    </span>
                  </span>
                </div>
              {/if}
            {/each}
          </div>
        </div>
      {/if}
    {/if}
  {:else if entriesWithPhotos.length === 0}
    <p class="empty-note">{i18n.t('progress.noPhotos')}</p>
  {:else}
    <div class="photo-grid">
      {#each entries as entry (entry.id)}
        {#each entry.photos ?? [] as photo, index (`${entry.id}-${index}`)}
          <a href={`/progress/${entry.id}`} class="photo-tile">
            <img src={photo} alt="" />
          </a>
        {/each}
      {/each}
    </div>
  {/if}
{/if}

<style>
  .loading {
    color: var(--ink-soft);
    text-align: center;
    padding: 40px 0;
  }
  .header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    margin-bottom: 18px;
  }
  h1 {
    font-size: 21px;
    font-weight: 700;
    margin: 0;
  }
  .subtitle {
    font-size: 12.5px;
    color: var(--ink-soft);
    margin: 2px 0 0;
  }
  .header-actions {
    display: flex;
    align-items: center;
    gap: 8px;
  }
  .icon-link {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 36px;
    height: 36px;
    border-radius: 10px;
    border: 1px solid var(--line);
    color: var(--ink);
    text-decoration: none;
  }
  .btn-primary-sm {
    display: flex;
    align-items: center;
    gap: 5px;
    padding: 8px 14px;
    border-radius: 10px;
    background: linear-gradient(135deg, var(--blue-deep), var(--pink-deep));
    color: #fff;
    font-size: 13px;
    font-weight: 600;
    text-decoration: none;
    border: none;
    cursor: pointer;
  }
  .empty-card {
    text-align: center;
    padding: 40px 16px;
    border: 1px solid var(--line);
    border-radius: 16px;
    color: var(--ink-soft);
  }
  .empty-card h3 {
    font-size: 15px;
    color: var(--ink);
    margin: 12px 0 6px;
  }
  .empty-card p {
    font-size: 13px;
    margin: 0 0 16px;
  }
  .empty-card .btn-primary-sm {
    display: inline-flex;
  }
  .empty-note {
    color: var(--ink-soft);
    text-align: center;
    font-size: 13px;
    padding: 30px 0;
  }
  .tabs {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    gap: 8px;
    margin-bottom: 14px;
  }
  .tabs button {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 6px;
    padding: 9px;
    border-radius: 10px;
    border: 1px solid var(--line);
    background: var(--bg);
    color: var(--ink-soft);
    font-size: 12.5px;
    font-weight: 600;
    font-family: inherit;
    cursor: pointer;
  }
  .tabs button.active {
    background: linear-gradient(135deg, var(--blue-deep), var(--pink-deep));
    color: #fff;
    border-color: transparent;
  }
  .stats-row {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    gap: 10px;
    margin-bottom: 14px;
  }
  .stat-card {
    text-align: center;
    padding: 12px 8px;
    border: 1px solid var(--line);
    border-radius: 14px;
    background: var(--bg);
  }
  .stat-value {
    font-size: 20px;
    font-weight: 700;
    margin: 0;
  }
  .stat-label {
    font-size: 11px;
    color: var(--ink-soft);
    margin: 2px 0 0;
  }
  .entry-list {
    display: flex;
    flex-direction: column;
    gap: 10px;
  }
  .entry-card {
    display: flex;
    align-items: stretch;
    gap: 0;
    border: 1px solid var(--line);
    border-radius: 16px;
    background: var(--bg);
    text-decoration: none;
    color: var(--ink);
    overflow: hidden;
  }
  .entry-thumb {
    width: 72px;
    height: 72px;
    flex-shrink: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    background: var(--page);
    color: var(--ink-soft);
  }
  .entry-thumb img {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }
  .entry-body {
    flex: 1;
    min-width: 0;
    display: flex;
    flex-direction: column;
    justify-content: center;
    gap: 4px;
    padding: 10px 12px;
  }
  .entry-date {
    font-size: 14px;
    font-weight: 600;
    margin: 0;
  }
  .entry-badges {
    display: flex;
    flex-wrap: wrap;
    gap: 5px;
  }
  .badge {
    display: flex;
    align-items: center;
    gap: 3px;
    font-size: 10.5px;
    color: var(--ink-soft);
    border: 1px solid var(--line);
    border-radius: 999px;
    padding: 2px 8px;
  }
  :global(.entry-card .chevron) {
    align-self: center;
    margin-right: 12px;
    color: var(--ink-soft);
    flex-shrink: 0;
  }
  .card {
    background: var(--bg);
    border: 1px solid var(--line);
    border-radius: 16px;
    padding: 16px;
    margin-bottom: 14px;
  }
  .card-title {
    font-size: 13px;
    font-weight: 600;
    margin: 0 0 10px;
  }
  .card-head {
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    gap: 10px;
  }
  .evolution-list {
    display: flex;
    flex-direction: column;
    gap: 8px;
  }
  .evolution-row {
    display: flex;
    align-items: center;
    justify-content: space-between;
    font-size: 13px;
  }
  .evolution-label {
    color: var(--ink-soft);
  }
  .evolution-value {
    display: flex;
    align-items: center;
    gap: 8px;
  }
  .evolution-diff {
    border: 1px solid var(--line);
    border-radius: 999px;
    padding: 1px 8px;
    font-size: 11.5px;
  }
  .evolution-diff.up {
    border-color: var(--ok);
    color: var(--ok);
  }
  .evolution-diff.down {
    border-color: var(--alert);
    color: var(--alert);
  }
  .photo-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 6px;
  }
  .photo-tile {
    aspect-ratio: 1;
    border-radius: 10px;
    overflow: hidden;
    background: var(--page);
  }
  .photo-tile img {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }
</style>

// src/app/progress/page.tsx
'use client'

import { useEffect, useState, useRef } from 'react'
import { useTranslations, useLocale } from 'next-intl'
import { getDateLocale } from '@/i18n/date-locale'
import type { Locale } from '@/i18n/config'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import {
  TrendingUp,
  Plus,
  Camera,
  Ruler,
  ChevronRight,
  ImageIcon,
  ArrowLeftRight,
} from 'lucide-react'
import Link from 'next/link'
import { getPhysicalProgress, getUserProfile } from '@/lib/db'
import type { PhysicalProgress, Measurements } from '@/lib/types'
import { format } from 'date-fns'
import { ExportButton } from '@/components/ui/export-button'
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Legend,
} from 'recharts'

const MEASUREMENT_UNITS: Record<keyof Measurements, string> = {
  weight: 'kg',
  height: 'cm',
  chest: 'cm',
  underbust: 'cm',
  waist: 'cm',
  hips: 'cm',
  shoulders: 'cm',
}

export default function ProgressPage() {
  const t = useTranslations('progress')
  const tc = useTranslations('common')
  const locale = useLocale()
  const dateLocale = getDateLocale(locale as Locale)

  const MEASUREMENT_LABELS: Record<keyof Measurements, string> = {
    weight: t('measurements.weight'),
    height: t('measurements.height'),
    chest: t('measurements.chest'),
    underbust: t('measurements.underChest'),
    waist: t('waistLabel'),
    hips: t('measurements.hips'),
    shoulders: t('measurements.shoulders'),
  }
  const [entries, setEntries] = useState<PhysicalProgress[]>([])
  const [loading, setLoading] = useState(true)
  const [userName, setUserName] = useState<string | undefined>()
  const chartRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    async function loadData() {
      const [data, profile] = await Promise.all([getPhysicalProgress(50), getUserProfile()])
      setEntries(data)
      if (profile?.firstName) {
        setUserName(profile.firstName)
      }
      setLoading(false)
    }
    loadData()
  }, [])

  // Prepare chart data (reverse for chronological order)
  const chartData = [...entries].reverse().map((entry) => ({
    date: format(new Date(entry.date), 'd MMM', { locale: dateLocale }),
    fullDate: format(new Date(entry.date), 'd MMMM yyyy', { locale: dateLocale }),
    ...entry.measurements,
  }))

  // Get available measurements (ones that have at least one data point)
  const availableMeasurements = Object.keys(MEASUREMENT_LABELS).filter((key) =>
    entries.some((e) => e.measurements?.[key as keyof Measurements] !== undefined)
  ) as (keyof Measurements)[]

  // Stats
  const entriesWithPhotos = entries.filter((e) => e.photos && e.photos.length > 0).length
  const totalPhotos = entries.reduce((acc, e) => acc + (e.photos?.length || 0), 0)

  // Get first and last measurements for comparison
  const firstEntry = [...entries].reverse()[0]
  const lastEntry = entries[0]

  if (loading) {
    return (
      <div className="flex min-h-[50vh] items-center justify-center p-4">
        <p className="text-muted-foreground">{tc('loading')}</p>
      </div>
    )
  }

  return (
    <div className="space-y-6 p-4 pb-24">
      {/* Header */}
      <div className="flex items-center justify-between pt-2">
        <div>
          <h1 className="text-foreground text-2xl font-bold">{t('title')}</h1>
          <p className="text-muted-foreground text-sm">
            {entries.length} {entries.length > 1 ? t('entries') : t('entry')}
          </p>
        </div>
        <div className="flex gap-2">
          <Link href="/progress/compare">
            <Button size="sm" variant="outline" className="gap-2">
              <ArrowLeftRight className="h-4 w-4" />
            </Button>
          </Link>
          <Link href="/progress/new">
            <Button size="sm" className="gap-2">
              <Plus className="h-4 w-4" />
              {t('add')}
            </Button>
          </Link>
        </div>
      </div>

      {entries.length === 0 ? (
        <Card>
          <CardContent className="py-12 text-center">
            <div className="bg-muted/50 mx-auto mb-4 w-fit rounded-full p-4">
              <TrendingUp className="text-muted-foreground h-8 w-8" />
            </div>
            <h3 className="text-foreground mb-2 font-medium">{t('noEntries')}</h3>
            <p className="text-muted-foreground mb-4 text-sm">{t('noEntriesDesc')}</p>
            <Link href="/progress/new">
              <Button className="gap-2">
                <Plus className="h-4 w-4" />
                {t('addEntry')}
              </Button>
            </Link>
          </CardContent>
        </Card>
      ) : (
        <Tabs defaultValue="timeline" className="space-y-4">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="timeline">{t('tabs.timeline')}</TabsTrigger>
            <TabsTrigger value="graphs">{t('tabs.charts')}</TabsTrigger>
            <TabsTrigger value="photos">{t('tabs.photos')}</TabsTrigger>
          </TabsList>

          {/* Timeline Tab */}
          <TabsContent value="timeline" className="space-y-4">
            {/* Quick Stats */}
            <div className="grid grid-cols-3 gap-3">
              <Card>
                <CardContent className="p-3 text-center">
                  <p className="text-primary text-2xl font-bold">{entries.length}</p>
                  <p className="text-muted-foreground text-xs">{t('stats.entries')}</p>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-3 text-center">
                  <p className="text-foreground text-2xl font-bold">{totalPhotos}</p>
                  <p className="text-muted-foreground text-xs">{t('stats.photos')}</p>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-3 text-center">
                  <p className="text-foreground text-2xl font-bold">
                    {firstEntry && lastEntry && firstEntry !== lastEntry
                      ? Math.floor(
                          (new Date(lastEntry.date).getTime() -
                            new Date(firstEntry.date).getTime()) /
                            (1000 * 60 * 60 * 24)
                        )
                      : 0}
                  </p>
                  <p className="text-muted-foreground text-xs">{t('stats.days')}</p>
                </CardContent>
              </Card>
            </div>

            {/* Entries List */}
            <div className="space-y-3">
              {entries.map((entry) => (
                <Link key={entry.id} href={`/progress/${entry.id}`}>
                  <Card className="hover:bg-muted/30 overflow-hidden transition-colors">
                    <CardContent className="p-0">
                      <div className="flex items-stretch">
                        {/* Thumbnail */}
                        {entry.photos && entry.photos.length > 0 ? (
                          <div className="h-20 w-20 flex-shrink-0">
                            <img
                              src={entry.photos[0]}
                              alt=""
                              className="h-full w-full object-cover"
                            />
                          </div>
                        ) : (
                          <div className="bg-muted flex h-20 w-20 flex-shrink-0 items-center justify-center">
                            <Ruler className="text-muted-foreground h-6 w-6" />
                          </div>
                        )}

                        {/* Content */}
                        <div className="flex flex-1 items-center justify-between p-3">
                          <div className="space-y-1">
                            <p className="text-foreground font-medium">
                              {format(new Date(entry.date), 'd MMMM yyyy', { locale: dateLocale })}
                            </p>
                            <div className="flex flex-wrap gap-1">
                              {entry.photos && entry.photos.length > 0 && (
                                <Badge variant="outline" className="gap-1 text-xs">
                                  <Camera className="h-3 w-3" />
                                  {entry.photos.length}
                                </Badge>
                              )}
                              {entry.measurements && Object.keys(entry.measurements).length > 0 && (
                                <Badge variant="outline" className="gap-1 text-xs">
                                  <Ruler className="h-3 w-3" />
                                  {Object.keys(entry.measurements).length}
                                </Badge>
                              )}
                              {entry.tags?.slice(0, 2).map((tag) => (
                                <Badge key={tag} variant="secondary" className="text-xs">
                                  {tag}
                                </Badge>
                              ))}
                            </div>
                          </div>
                          <ChevronRight className="text-muted-foreground h-5 w-5" />
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                </Link>
              ))}
            </div>
          </TabsContent>

          {/* Graphs Tab */}
          <TabsContent value="graphs" className="space-y-4">
            {availableMeasurements.length === 0 ? (
              <Card>
                <CardContent className="py-12 text-center">
                  <p className="text-muted-foreground">{t('noMeasurements')}</p>
                </CardContent>
              </Card>
            ) : (
              <>
                {/* Body Measurements Chart */}
                {availableMeasurements.filter((m) =>
                  ['chest', 'underbust', 'waist', 'hips'].includes(m)
                ).length > 0 && (
                  <Card>
                    <CardHeader className="pb-2">
                      <div className="flex items-center justify-between">
                        <CardTitle className="text-base">{t('bodyMeasurements')}</CardTitle>
                        <ExportButton
                          chartRef={chartRef}
                          title={t('bodyEvolution')}
                          subtitle={t('measurementsLabel')}
                          userName={userName}
                          data={availableMeasurements
                            .filter((m) => ['chest', 'underbust', 'waist', 'hips'].includes(m))
                            .map((key) => {
                              const last = lastEntry?.measurements?.[key]
                              if (last === undefined) return null
                              return {
                                marker: key,
                                label: MEASUREMENT_LABELS[key],
                                value: last,
                                unit: MEASUREMENT_UNITS[key],
                              }
                            })
                            .filter((d): d is NonNullable<typeof d> => d !== null)}
                        />
                      </div>
                    </CardHeader>
                    <CardContent>
                      <div ref={chartRef} className="h-64">
                        <ResponsiveContainer width="100%" height="100%">
                          <LineChart data={chartData}>
                            <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
                            <XAxis
                              dataKey="date"
                              tick={{ fill: 'var(--muted-foreground)', fontSize: 12 }}
                              tickLine={{ stroke: 'var(--border)' }}
                            />
                            <YAxis
                              tick={{ fill: 'var(--muted-foreground)', fontSize: 12 }}
                              tickLine={{ stroke: 'var(--border)' }}
                              domain={['auto', 'auto']}
                            />
                            <Tooltip
                              contentStyle={{
                                backgroundColor: 'var(--card)',
                                border: '1px solid var(--border)',
                                borderRadius: '8px',
                              }}
                            />
                            <Legend />
                            {availableMeasurements.includes('chest') && (
                              <Line
                                type="monotone"
                                dataKey="chest"
                                name={t('chestLabel')}
                                stroke="#F5A9B8"
                                strokeWidth={2}
                                dot={{ fill: '#F5A9B8' }}
                              />
                            )}
                            {availableMeasurements.includes('underbust') && (
                              <Line
                                type="monotone"
                                dataKey="underbust"
                                name={t('underChestLabel')}
                                stroke="#D4849A"
                                strokeWidth={2}
                                dot={{ fill: '#D4849A' }}
                              />
                            )}
                            {availableMeasurements.includes('waist') && (
                              <Line
                                type="monotone"
                                dataKey="waist"
                                name={t('waistLabel')}
                                stroke="#5BCEFA"
                                strokeWidth={2}
                                dot={{ fill: '#5BCEFA' }}
                              />
                            )}
                            {availableMeasurements.includes('hips') && (
                              <Line
                                type="monotone"
                                dataKey="hips"
                                name={t('hipsLabel')}
                                stroke="#3BA8D4"
                                strokeWidth={2}
                                dot={{ fill: '#3BA8D4' }}
                              />
                            )}
                          </LineChart>
                        </ResponsiveContainer>
                      </div>
                    </CardContent>
                  </Card>
                )}

                {/* Weight Chart */}
                {availableMeasurements.includes('weight') && (
                  <Card>
                    <CardHeader className="pb-2">
                      <CardTitle className="text-base">{t('weightLabel')}</CardTitle>
                    </CardHeader>
                    <CardContent>
                      <div className="h-48">
                        <ResponsiveContainer width="100%" height="100%">
                          <LineChart data={chartData}>
                            <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
                            <XAxis
                              dataKey="date"
                              tick={{ fill: 'var(--muted-foreground)', fontSize: 12 }}
                            />
                            <YAxis
                              tick={{ fill: 'var(--muted-foreground)', fontSize: 12 }}
                              domain={['auto', 'auto']}
                            />
                            <Tooltip
                              contentStyle={{
                                backgroundColor: 'var(--card)',
                                border: '1px solid var(--border)',
                                borderRadius: '8px',
                              }}
                              formatter={(value) => [`${value} kg`, t('weightLabel')]}
                            />
                            <Line
                              type="monotone"
                              dataKey="weight"
                              stroke="#9333EA"
                              strokeWidth={2}
                              dot={{ fill: '#9333EA' }}
                            />
                          </LineChart>
                        </ResponsiveContainer>
                      </div>
                    </CardContent>
                  </Card>
                )}

                {/* Comparison Card */}
                {firstEntry && lastEntry && firstEntry.id !== lastEntry.id && (
                  <Card>
                    <CardHeader className="pb-2">
                      <CardTitle className="text-base">{t('evolution')}</CardTitle>
                    </CardHeader>
                    <CardContent>
                      <div className="space-y-2">
                        {availableMeasurements.map((key) => {
                          const first = firstEntry.measurements?.[key]
                          const last = lastEntry.measurements?.[key]
                          if (first === undefined || last === undefined) return null

                          const diff = last - first
                          const sign = diff > 0 ? '+' : ''

                          return (
                            <div key={key} className="flex items-center justify-between text-sm">
                              <span className="text-muted-foreground">
                                {MEASUREMENT_LABELS[key]}
                              </span>
                              <div className="flex items-center gap-2">
                                <span>
                                  {first} → {last} {MEASUREMENT_UNITS[key]}
                                </span>
                                <Badge
                                  variant={diff === 0 ? 'secondary' : 'outline'}
                                  className={
                                    diff > 0
                                      ? 'border-green-500 text-green-500'
                                      : diff < 0
                                        ? 'border-red-500 text-red-500'
                                        : ''
                                  }
                                >
                                  {sign}
                                  {diff.toFixed(1)}
                                </Badge>
                              </div>
                            </div>
                          )
                        })}
                      </div>
                    </CardContent>
                  </Card>
                )}
              </>
            )}
          </TabsContent>

          {/* Photos Tab */}
          <TabsContent value="photos" className="space-y-4">
            {entriesWithPhotos === 0 ? (
              <Card>
                <CardContent className="py-12 text-center">
                  <div className="bg-muted/50 mx-auto mb-4 w-fit rounded-full p-4">
                    <ImageIcon className="text-muted-foreground h-8 w-8" />
                  </div>
                  <p className="text-muted-foreground">{t('noPhotos')}</p>
                </CardContent>
              </Card>
            ) : (
              <div className="grid grid-cols-3 gap-2">
                {entries.flatMap((entry) =>
                  (entry.photos || []).map((photo, idx) => (
                    <Link
                      key={`${entry.id}-${idx}`}
                      href={`/progress/${entry.id}`}
                      className="bg-muted aspect-square overflow-hidden rounded-lg"
                    >
                      <img
                        src={photo}
                        alt=""
                        className="h-full w-full object-cover transition-transform hover:scale-105"
                      />
                    </Link>
                  ))
                )}
              </div>
            )}
          </TabsContent>
        </Tabs>
      )}
    </div>
  )
}
