// src/routes/onboarding/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation'
  import { i18n } from '$lib/i18n.svelte'
  import {
    getOnboardingState,
    saveOnboardingState,
    completeOnboarding,
    ONBOARDING_STEPS,
    type OnboardingState,
  } from '$lib/onboarding'
  import WelcomeStep from '$lib/components/onboarding/WelcomeStep.svelte'
  import ProfileStep from '$lib/components/onboarding/ProfileStep.svelte'
  import MedicationStep from '$lib/components/onboarding/MedicationStep.svelte'
  import TourStep from '$lib/components/onboarding/TourStep.svelte'

  let onboardingState = $state<OnboardingState>({ completed: false, currentStep: 0 })
  let mounted = $state(false)

  $effect(() => {
    const saved = getOnboardingState()
    if (saved.completed) {
      goto('/', { replaceState: true })
      return
    }
    onboardingState = saved
    mounted = true
  })

  function goToStep(step: number) {
    onboardingState = { ...onboardingState, currentStep: step }
    saveOnboardingState(onboardingState)
  }

  function nextStep() {
    if (onboardingState.currentStep < ONBOARDING_STEPS.length - 1) {
      goToStep(onboardingState.currentStep + 1)
    }
  }

  function updateProfile(profile: OnboardingState['profile']) {
    onboardingState = { ...onboardingState, profile }
    saveOnboardingState(onboardingState)
  }

  function handleComplete() {
    completeOnboarding()
    goto('/', { replaceState: true })
  }

  let currentStep = $derived(ONBOARDING_STEPS[onboardingState.currentStep]!)
</script>

<div class="page">
  {#if mounted}
    <div class="progress">
      <div class="dots">
        {#each ONBOARDING_STEPS as step, index (step.id)}
          <button
            type="button"
            class="dot"
            class:current={index === onboardingState.currentStep}
            class:done={index < onboardingState.currentStep}
            disabled={index > onboardingState.currentStep}
            onclick={() => index < onboardingState.currentStep && goToStep(index)}
            aria-label={step.title}
          ></button>
        {/each}
      </div>
      <p class="counter">
        {onboardingState.currentStep + 1} / {ONBOARDING_STEPS.length}
        {#if currentStep.optional}
          ({i18n.t('onboarding.optional')})
        {/if}
      </p>
    </div>

    <div class="content">
      {#if currentStep.id === 'welcome'}
        <WelcomeStep onNext={nextStep} />
      {:else if currentStep.id === 'profile'}
        <ProfileStep
          {onboardingState}
          onUpdate={updateProfile}
          onNext={nextStep}
          onSkip={nextStep}
        />
      {:else if currentStep.id === 'medication'}
        <MedicationStep onNext={nextStep} onSkip={nextStep} />
      {:else if currentStep.id === 'tour'}
        <TourStep onComplete={handleComplete} />
      {/if}
    </div>
  {/if}
</div>

<style>
  .page {
    display: flex;
    flex-direction: column;
    min-height: calc(100vh - 136px);
  }
  .progress {
    padding: 12px 0 4px;
  }
  .dots {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 6px;
  }
  .dot {
    height: 6px;
    width: 6px;
    border-radius: 999px;
    border: none;
    background: var(--line);
    padding: 0;
    cursor: default;
  }
  .dot.current {
    width: 24px;
    background: linear-gradient(135deg, var(--blue-deep), var(--pink-deep));
  }
  .dot.done {
    background: color-mix(in srgb, var(--blue-deep) 45%, transparent);
    cursor: pointer;
  }
  .counter {
    text-align: center;
    font-size: 11px;
    color: var(--ink-soft);
    margin: 6px 0 0;
  }
  .content {
    flex: 1;
  }
</style>

// src/app/onboarding/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { cn } from '@/lib/utils'
import {
  getOnboardingState,
  saveOnboardingState,
  completeOnboarding,
  ONBOARDING_STEPS,
  OnboardingState,
} from '@/lib/onboarding'
import { WelcomeStep } from '@/components/onboarding/welcome-step'
import { ProfileStep } from '@/components/onboarding/profile-step'
import { MedicationStep } from '@/components/onboarding/medication-step'
import { TourStep } from '@/components/onboarding/tour-step'

export default function OnboardingPage() {
  const router = useRouter()
  const [state, setState] = useState<OnboardingState>({
    completed: false,
    currentStep: 0,
  })
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    const savedState = getOnboardingState()
    // If already completed, redirect to home
    if (savedState.completed) {
      router.replace('/')
      return
    }
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setState(savedState)

    setMounted(true)
  }, [router])

  const goToStep = (step: number) => {
    const newState = { ...state, currentStep: step }
    setState(newState)
    saveOnboardingState(newState)
  }

  const nextStep = () => {
    if (state.currentStep < ONBOARDING_STEPS.length - 1) {
      goToStep(state.currentStep + 1)
    }
  }

  const updateProfile = (profile: OnboardingState['profile']) => {
    const newState = { ...state, profile }
    setState(newState)
    saveOnboardingState(newState)
  }

  const handleComplete = () => {
    completeOnboarding()
    router.replace('/')
  }

  if (!mounted) {
    return (
      <div className="bg-background flex min-h-screen items-center justify-center">
        <div className="border-primary h-8 w-8 animate-spin rounded-full border-2 border-t-transparent" />
      </div>
    )
  }

  const currentStep = ONBOARDING_STEPS[state.currentStep]

  return (
    <div className="bg-background flex min-h-screen flex-col">
      {/* Progress Indicator */}
      <div className="p-4 pt-8">
        <div className="flex items-center justify-center gap-2">
          {ONBOARDING_STEPS.map((step, index) => (
            <button
              key={step.id}
              onClick={() => index < state.currentStep && goToStep(index)}
              disabled={index > state.currentStep}
              className={cn(
                'h-2 rounded-full transition-all',
                index === state.currentStep
                  ? 'bg-primary w-8'
                  : index < state.currentStep
                    ? 'bg-primary/50 hover:bg-primary/70 w-2'
                    : 'bg-muted w-2'
              )}
            />
          ))}
        </div>
        <p className="text-muted-foreground mt-2 text-center text-xs">
          {state.currentStep + 1} / {ONBOARDING_STEPS.length}
          {currentStep.optional && ' (optionnel)'}
        </p>
      </div>

      {/* Step Content */}
      <div className="flex-1 px-6 pb-8">
        {currentStep.id === 'welcome' && <WelcomeStep onNext={nextStep} />}
        {currentStep.id === 'profile' && (
          <ProfileStep state={state} onUpdate={updateProfile} onNext={nextStep} onSkip={nextStep} />
        )}
        {currentStep.id === 'medication' && <MedicationStep onNext={nextStep} onSkip={nextStep} />}
        {currentStep.id === 'tour' && <TourStep onComplete={handleComplete} />}
      </div>
    </div>
  )
}
