// src/app/bloodtests/[id]/page.tsx
'use client'

import { useEffect, useState } from 'react'
import { useTranslations, useLocale } from 'next-intl'
import { getDateLocale } from '@/i18n/date-locale'
import type { Locale } from '@/i18n/config'
import { useParams, useRouter } from 'next/navigation'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import {
  ArrowLeft,
  Trash2,
  Pencil,
  FlaskConical,
  Heart,
  Activity,
  AlertTriangle,
  CheckCircle2,
} from 'lucide-react'
import Link from 'next/link'
import { format } from 'date-fns'
import { db, deleteBloodTest, getUserProfile } from '@/lib/db'
import type { BloodTest, BloodMarker } from '@/lib/types'
import { REFERENCE_RANGES } from '@/lib/constants'

// Marker groups for display
const MARKER_GROUPS: Record<string, { icon: typeof FlaskConical; markers: BloodMarker[] }> = {
  hormones: {
    icon: FlaskConical,
    markers: [
      'estradiol',
      'testosterone',
      'lh',
      'fsh',
      'prolactin',
      'shbg',
      'dheas',
      'progesterone',
    ],
  },
  blood: {
    icon: Heart,
    markers: ['hematocrit', 'hemoglobin'],
  },
  organs: {
    icon: Activity,
    markers: ['alt', 'ast', 'creatinine', 'potassium'],
  },
}

export default function BloodTestDetailPage() {
  const t = useTranslations('bloodtests')
  const locale = useLocale()
  const dateLocale = getDateLocale(locale as Locale)
  const params = useParams()
  const router = useRouter()
  const [test, setTest] = useState<BloodTest | null>(null)
  const [loading, setLoading] = useState(true)
  const [context, setContext] = useState<'feminizing' | 'masculinizing'>('feminizing')

  useEffect(() => {
    async function load() {
      const id = parseInt(params.id as string)
      if (isNaN(id)) {
        router.push('/bloodtests')
        return
      }

      const [testData, profile] = await Promise.all([db.bloodTests.get(id), getUserProfile()])

      if (!testData) {
        router.push('/bloodtests')
        return
      }

      setTest(testData)
      if (profile?.targetGender) {
        setContext(profile.targetGender === 'masculinizing' ? 'masculinizing' : 'feminizing')
      }
      setLoading(false)
    }
    load()
  }, [params.id, router])

  async function handleDelete() {
    if (!test?.id) return
    if (!confirm(t('detail.deleteConfirm'))) return

    await deleteBloodTest(test.id)
    router.push('/bloodtests')
  }

  // Get status for a marker value
  function getMarkerStatus(marker: BloodMarker, value: number): 'normal' | 'low' | 'high' {
    const range = REFERENCE_RANGES.find((r) => r.marker === marker && r.context === context)
    if (!range) return 'normal'
    if (value < range.min) return 'low'
    if (value > range.max) return 'high'
    return 'normal'
  }

  if (loading) {
    return (
      <div className="space-y-6 p-4">
        <div className="pt-2">
          <h1 className="text-foreground text-xl font-bold">{t('detail.loading')}</h1>
        </div>
      </div>
    )
  }

  if (!test) return null

  // Group results by category
  const resultsByMarker = new Map(test.results.map((r) => [r.marker, r]))

  return (
    <div className="space-y-6 p-4 pb-24">
      {/* Header */}
      <div className="flex items-center justify-between pt-2">
        <div className="flex items-center gap-3">
          <Link href="/bloodtests">
            <Button variant="ghost" size="icon">
              <ArrowLeft className="h-5 w-5" />
            </Button>
          </Link>
          <div>
            <h1 className="text-foreground text-xl font-bold">
              {format(new Date(test.date), 'dd MMMM yyyy', { locale: dateLocale })}
            </h1>
            {test.lab && (
              <Badge variant="secondary" className="mt-1">
                {test.lab}
              </Badge>
            )}
          </div>
        </div>
        <div className="flex items-center gap-1">
          <Link href={`/bloodtests/${params.id}/edit`}>
            <Button variant="ghost" size="icon" className="text-muted-foreground">
              <Pencil className="h-5 w-5" />
            </Button>
          </Link>
          <Button
            variant="ghost"
            size="icon"
            className="text-muted-foreground hover:text-destructive"
            onClick={handleDelete}
          >
            <Trash2 className="h-5 w-5" />
          </Button>
        </div>
      </div>

      {/* Results by group */}
      {Object.entries(MARKER_GROUPS).map(([groupKey, group]) => {
        const groupResults = group.markers
          .filter((marker) => resultsByMarker.has(marker))
          .map((marker) => ({
            marker,
            result: resultsByMarker.get(marker)!,
          }))

        if (groupResults.length === 0) return null

        const Icon = group.icon

        return (
          <Card key={groupKey}>
            <CardHeader className="pb-3">
              <CardTitle className="flex items-center gap-2 text-base">
                <Icon className="text-primary h-4 w-4" />
                {t('groups.' + groupKey)}
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {groupResults.map(({ marker, result }) => {
                const status = getMarkerStatus(marker, result.value)
                const range = REFERENCE_RANGES.find(
                  (r) => r.marker === marker && r.context === context
                )

                return (
                  <div
                    key={marker}
                    className={`flex items-center justify-between rounded-lg p-3 ${
                      status === 'normal'
                        ? 'bg-muted/30'
                        : status === 'low'
                          ? 'bg-yellow-500/10'
                          : 'bg-red-500/10'
                    }`}
                  >
                    <div className="flex-1">
                      <div className="flex items-center gap-2">
                        <span className="text-foreground font-medium">
                          {t('markers.' + marker)}
                        </span>
                        {status !== 'normal' && (
                          <AlertTriangle
                            className={`h-4 w-4 ${
                              status === 'low' ? 'text-yellow-500' : 'text-red-500'
                            }`}
                          />
                        )}
                        {status === 'normal' && <CheckCircle2 className="h-4 w-4 text-green-500" />}
                      </div>
                      <p className="text-muted-foreground mt-0.5 text-xs">
                        {t('descriptions.' + marker)}
                      </p>
                    </div>
                    <div className="text-right">
                      <div
                        className={`text-lg font-semibold ${
                          status === 'normal'
                            ? 'text-foreground'
                            : status === 'low'
                              ? 'text-yellow-500'
                              : 'text-red-500'
                        }`}
                      >
                        {result.value}{' '}
                        <span className="text-muted-foreground text-sm font-normal">
                          {result.unit}
                        </span>
                      </div>
                      {range && (
                        <p className="text-muted-foreground text-xs">
                          {t('detail.targetLabel')}: {range.min} - {range.max}
                        </p>
                      )}
                    </div>
                  </div>
                )
              })}
            </CardContent>
          </Card>
        )
      })}

      {/* Notes */}
      {test.notes && (
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base">{t('detail.notesTitle')}</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground text-sm whitespace-pre-wrap">{test.notes}</p>
          </CardContent>
        </Card>
      )}

      {/* Summary card */}
      <Card className="border-primary/30 bg-primary/5">
        <CardContent className="py-4">
          <div className="flex items-center gap-3">
            <div className="bg-primary/20 rounded-full p-2">
              <FlaskConical className="text-primary h-5 w-5" />
            </div>
            <div>
              <p className="text-foreground font-medium">
                {test.results.length}{' '}
                {test.results.length > 1 ? t('detail.markerPlural') : t('detail.markerSingular')}
              </p>
              <p className="text-muted-foreground text-sm">
                {test.results.filter((r) => getMarkerStatus(r.marker, r.value) === 'normal').length}{' '}
                {t('detail.inTargetRange')}
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}

// src/routes/bloodtests/[id]/+page.svelte
<script lang="ts">
  import { page } from '$app/state'
  import { goto } from '$app/navigation'
  import { format } from 'date-fns'
  import { i18n, getDateLocale } from '$lib/i18n.svelte'
  import { getBloodTest, deleteBloodTest, getUserProfile } from '$lib/db'
  import {
    REFERENCE_RANGES,
    getHematocritStatus,
    getReferenceRangeSource,
    HEMATOCRIT_ALERT_THRESHOLD_SOURCE,
  } from '$lib/constants'
  import type { BloodTest, BloodMarker } from '$lib/types'
  import ArrowLeft from '@lucide/svelte/icons/arrow-left'
  import Trash2 from '@lucide/svelte/icons/trash-2'
  import Pencil from '@lucide/svelte/icons/pencil'
  import FlaskConical from '@lucide/svelte/icons/flask-conical'
  import Heart from '@lucide/svelte/icons/heart'
  import Activity from '@lucide/svelte/icons/activity'
  import FileText from '@lucide/svelte/icons/file-text'

  const MARKER_GROUPS: { key: string; icon: typeof FlaskConical; markers: BloodMarker[] }[] = [
    {
      key: 'hormones',
      icon: FlaskConical,
      markers: [
        'estradiol',
        'testosterone',
        'lh',
        'fsh',
        'prolactin',
        'shbg',
        'dheas',
        'progesterone',
      ],
    },
    { key: 'blood', icon: Heart, markers: ['hematocrit', 'hemoglobin'] },
    { key: 'organs', icon: Activity, markers: ['alt', 'ast', 'creatinine', 'potassium'] },
  ]

  let test = $state<BloodTest | null>(null)
  let loading = $state(true)
  let context = $state<'feminizing' | 'masculinizing'>('feminizing')

  async function loadData() {
    const id = parseInt(page.params.id!)
    if (isNaN(id)) {
      await goto('/bloodtests')
      return
    }

    const [testData, profile] = await Promise.all([getBloodTest(id), getUserProfile()])
    if (!testData) {
      await goto('/bloodtests')
      return
    }

    test = testData
    if (profile?.targetGender) {
      context = profile.targetGender === 'masculinizing' ? 'masculinizing' : 'feminizing'
    }
    loading = false
  }

  $effect(() => {
    void page.params.id
    loading = true
    loadData()
  })

  async function handleDelete() {
    if (!test?.id || !confirm(i18n.t('bloodtests.detail.deleteConfirm'))) return
    await deleteBloodTest(test.id)
    await goto('/bloodtests')
  }
</script>

{#if loading}
  <p class="loading">{i18n.t('bloodtests.detail.loading')}</p>
{:else if test}
  {@const resultsByMarker = new Map(test.results.map((r) => [r.marker, r]))}
  <div class="header">
    <div class="header-left">
      <a href="/bloodtests" class="icon-link" aria-label={i18n.t('common.back')}
        ><ArrowLeft size={20} /></a
      >
      <div>
        <h1>
          {format(new Date(test.date), 'd MMMM yyyy', { locale: getDateLocale(i18n.locale) })}
        </h1>
        {#if test.lab}
          <span class="lab-badge">{test.lab}</span>
        {/if}
      </div>
    </div>
    <div class="header-actions">
      <a href={`/bloodtests/${test.id}/edit`} class="icon-link" aria-label={i18n.t('common.edit')}
        ><Pencil size={18} /></a
      >
      <button
        type="button"
        class="icon-link danger"
        onclick={handleDelete}
        aria-label={i18n.t('common.delete')}
      >
        <Trash2 size={18} />
      </button>
    </div>
  </div>

  {#each MARKER_GROUPS as group (group.key)}
    {@const Icon = group.icon}
    {@const groupResults = group.markers
      .filter((m) => resultsByMarker.has(m))
      .map((m) => ({ marker: m, result: resultsByMarker.get(m)! }))}
    {#if groupResults.length > 0}
      <div class="card">
        <p class="card-title"><Icon size={14} /> {i18n.t('bloodtests.groups.' + group.key)}</p>
        <div class="result-list">
          {#each groupResults as { marker, result } (marker)}
            {@const status = marker === 'hematocrit' ? getHematocritStatus(result.value) : 'ok'}
            {@const source = getReferenceRangeSource(marker, context)}
            {@const range = REFERENCE_RANGES.find(
              (r) => r.marker === marker && r.context === context
            )}
            <div
              class="result-line"
              class:watch={status === 'watch'}
              class:alert={status === 'alert'}
            >
              <div>
                <p class="marker-name">{i18n.t('bloodtests.markers.' + marker)}</p>
                <p class="marker-desc">{i18n.t('bloodtests.descriptions.' + marker)}</p>
                {#if status !== 'ok'}
                  <p class="threshold-source">{HEMATOCRIT_ALERT_THRESHOLD_SOURCE}</p>
                {/if}
              </div>
              <div class="result-value">
                <span class="value">{result.value} <span class="unit">{result.unit}</span></span>
                {#if range}
                  <p class="target">
                    {i18n.t('bloodtests.detail.targetLabel')}: {range.min} - {range.max}
                    {#if source}({source}){/if}
                  </p>
                {/if}
              </div>
            </div>
          {/each}
        </div>
      </div>
    {/if}
  {/each}

  {#if test.notes}
    <div class="card">
      <p class="card-title"><FileText size={14} /> {i18n.t('bloodtests.detail.notesTitle')}</p>
      <p class="notes">{test.notes}</p>
    </div>
  {/if}

  <div class="card summary-card">
    <div class="summary-icon">
      <FlaskConical size={20} />
    </div>
    <div>
      <p class="summary-count">
        {test.results.length}
        {test.results.length > 1
          ? i18n.t('bloodtests.detail.markerPlural')
          : i18n.t('bloodtests.detail.markerSingular')}
      </p>
    </div>
  </div>
{/if}

<style>
  .loading {
    color: var(--ink-soft);
    text-align: center;
    padding: 40px 0;
  }
  .header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    margin-bottom: 16px;
  }
  .header-left {
    display: flex;
    align-items: center;
    gap: 10px;
  }
  h1 {
    font-size: 19px;
    font-weight: 700;
    margin: 0;
  }
  .lab-badge {
    display: inline-block;
    margin-top: 4px;
    font-size: 11px;
    padding: 2px 8px;
    border-radius: 999px;
    border: 1px solid var(--line);
    color: var(--ink-soft);
  }
  .header-actions {
    display: flex;
    align-items: center;
    gap: 4px;
  }
  .icon-link {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 36px;
    height: 36px;
    border-radius: 10px;
    color: var(--ink);
    text-decoration: none;
    border: none;
    background: transparent;
    cursor: pointer;
    flex-shrink: 0;
  }
  .icon-link.danger {
    color: var(--alert);
  }
  .card {
    background: var(--bg);
    border: 1px solid var(--line);
    border-radius: 16px;
    padding: 16px;
    margin-bottom: 14px;
  }
  .card-title {
    display: flex;
    align-items: center;
    gap: 6px;
    font-size: 13px;
    font-weight: 600;
    margin: 0 0 10px;
  }
  .result-list {
    display: flex;
    flex-direction: column;
    gap: 10px;
  }
  .result-line {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    gap: 10px;
    padding: 10px;
    border-radius: 12px;
    background: color-mix(in srgb, var(--ink) 3%, transparent);
  }
  .result-line.watch {
    background: color-mix(in srgb, var(--watch) 14%, transparent);
  }
  .result-line.alert {
    background: color-mix(in srgb, var(--alert) 14%, transparent);
  }
  .marker-name {
    font-size: 13.5px;
    font-weight: 600;
    margin: 0;
  }
  .marker-desc {
    font-size: 11px;
    color: var(--ink-soft);
    margin: 2px 0 0;
  }
  .threshold-source {
    font-size: 10px;
    color: var(--ink-faint);
    margin: 2px 0 0;
  }
  .result-value {
    text-align: right;
    flex-shrink: 0;
  }
  .value {
    font-size: 16px;
    font-weight: 600;
  }
  .unit {
    font-size: 12px;
    font-weight: 400;
    color: var(--ink-soft);
  }
  .target {
    font-size: 11px;
    color: var(--ink-soft);
    margin: 2px 0 0;
  }
  .notes {
    font-size: 13.5px;
    white-space: pre-wrap;
    margin: 0;
    color: var(--ink-soft);
  }
  .summary-card {
    display: flex;
    align-items: center;
    gap: 14px;
  }
  .summary-icon {
    width: 44px;
    height: 44px;
    border-radius: 12px;
    display: flex;
    align-items: center;
    justify-content: center;
    background: color-mix(in srgb, var(--blue-deep) 18%, transparent);
    color: var(--blue-deep);
    flex-shrink: 0;
  }
  .summary-count {
    font-size: 14px;
    font-weight: 600;
    margin: 0;
  }
</style>
