// src/routes/practitioners/[id]/edit/+page.svelte
<script lang="ts">
  import { page } from '$app/state'
  import { goto } from '$app/navigation'
  import { i18n } from '$lib/i18n.svelte'
  import { getPractitioner, updatePractitioner } from '$lib/db'
  import type { AppointmentType } from '$lib/types'
  import PractitionerFormFields from '$lib/components/practitioners/PractitionerFormFields.svelte'
  import ArrowLeft from '@lucide/svelte/icons/arrow-left'

  let loading = $state(true)
  let saving = $state(false)
  let practitionerId = $state<number | null>(null)

  let name = $state('')
  let specialty = $state<AppointmentType>('general')
  let location = $state('')
  let phone = $state('')
  let email = $state('')
  let website = $state('')
  let notes = $state('')
  let isTransFriendly = $state(false)

  async function loadData() {
    const id = parseInt(page.params.id!)
    if (isNaN(id)) {
      await goto('/practitioners')
      return
    }

    const data = await getPractitioner(id)
    if (!data) {
      await goto('/practitioners')
      return
    }

    practitionerId = id
    name = data.name
    specialty = data.specialty
    location = data.location ?? ''
    phone = data.phone ?? ''
    email = data.email ?? ''
    website = data.website ?? ''
    notes = data.notes ?? ''
    isTransFriendly = data.isTransFriendly ?? false
    loading = false
  }

  $effect(() => {
    void page.params.id
    loading = true
    loadData()
  })

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault()
    if (!practitionerId || !name.trim()) return

    saving = true
    try {
      await updatePractitioner(practitionerId, {
        name: name.trim(),
        specialty,
        location: location.trim() || undefined,
        phone: phone.trim() || undefined,
        email: email.trim() || undefined,
        website: website.trim() || undefined,
        notes: notes.trim() || undefined,
        isTransFriendly,
      })
      await goto('/practitioners')
    } finally {
      saving = false
    }
  }
</script>

{#if loading}
  <p class="loading">{i18n.t('appointments.detail.loading')}</p>
{:else}
  <div class="header">
    <a href="/practitioners" class="icon-link" aria-label={i18n.t('common.back')}
      ><ArrowLeft size={20} /></a
    >
    <div>
      <h1>{i18n.t('practitioners.edit.title')}</h1>
      <p class="subtitle">{name}</p>
    </div>
  </div>

  <form onsubmit={handleSubmit}>
    <PractitionerFormFields
      bind:name
      bind:specialty
      bind:location
      bind:phone
      bind:email
      bind:website
      bind:notes
      bind:isTransFriendly
      {saving}
      backHref="/practitioners"
    />
  </form>
{/if}

<style>
  .loading {
    color: var(--ink-soft);
    text-align: center;
    padding: 40px 0;
  }
  .header {
    display: flex;
    align-items: center;
    gap: 10px;
    margin-bottom: 18px;
  }
  h1 {
    font-size: 19px;
    font-weight: 700;
    margin: 0;
  }
  .subtitle {
    font-size: 12.5px;
    color: var(--ink-soft);
    margin: 2px 0 0;
  }
  .icon-link {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 36px;
    height: 36px;
    border-radius: 10px;
    color: var(--ink);
    text-decoration: none;
    flex-shrink: 0;
  }
</style>

// src/app/practitioners/[id]/edit/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter, useParams } from 'next/navigation'
import { useTranslations } from 'next-intl'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { ArrowLeft } from 'lucide-react'
import { getPractitioner, updatePractitioner } from '@/lib/db'
import { PractitionerFormFields } from '@/components/practitioners/PractitionerFormFields'
import type { AppointmentType, Practitioner } from '@/lib/types'

export default function EditPractitionerPage() {
  const router = useRouter()
  const params = useParams()
  const t = useTranslations('practitioners')
  const tAppt = useTranslations('appointments')
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [practitioner, setPractitioner] = useState<Practitioner | null>(null)

  // Form state
  const [name, setName] = useState('')
  const [specialty, setSpecialty] = useState<AppointmentType>('general')
  const [location, setLocation] = useState('')
  const [phone, setPhone] = useState('')
  const [email, setEmail] = useState('')
  const [website, setWebsite] = useState('')
  const [notes, setNotes] = useState('')
  const [isTransFriendly, setIsTransFriendly] = useState(false)

  useEffect(() => {
    async function loadPractitioner() {
      const id = parseInt(params.id as string)
      if (isNaN(id)) {
        router.push('/practitioners')
        return
      }

      const data = await getPractitioner(id)
      if (!data) {
        router.push('/practitioners')
        return
      }

      setPractitioner(data)
      setName(data.name)
      setSpecialty(data.specialty)
      setLocation(data.location || '')
      setPhone(data.phone || '')
      setEmail(data.email || '')
      setWebsite(data.website || '')
      setNotes(data.notes || '')
      setIsTransFriendly(data.isTransFriendly || false)
      setLoading(false)
    }
    loadPractitioner()
  }, [params.id, router])

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!name.trim() || !practitioner?.id) return

    setSaving(true)
    try {
      await updatePractitioner(practitioner.id, {
        name: name.trim(),
        specialty,
        location: location.trim() || undefined,
        phone: phone.trim() || undefined,
        email: email.trim() || undefined,
        website: website.trim() || undefined,
        notes: notes.trim() || undefined,
        isTransFriendly,
      })

      router.push('/practitioners')
    } catch (error) {
      console.error('Failed to update practitioner:', error)
      setSaving(false)
    }
  }

  if (loading) {
    return (
      <div className="flex min-h-[50vh] items-center justify-center p-4">
        <p className="text-muted-foreground">{tAppt('detail.loading')}</p>
      </div>
    )
  }

  return (
    <div className="space-y-6 p-4 pb-24">
      {/* Header */}
      <div className="flex items-center gap-3 pt-2">
        <Link href="/practitioners">
          <Button variant="ghost" size="icon" className="shrink-0">
            <ArrowLeft className="h-5 w-5" />
          </Button>
        </Link>
        <div>
          <h1 className="text-foreground text-2xl font-bold">{t('edit.title')}</h1>
          <p className="text-muted-foreground text-sm">{practitioner?.name}</p>
        </div>
      </div>

      <form onSubmit={handleSubmit} className="space-y-6">
        <PractitionerFormFields
          name={name}
          onNameChange={setName}
          specialty={specialty}
          onSpecialtyChange={setSpecialty}
          location={location}
          onLocationChange={setLocation}
          phone={phone}
          onPhoneChange={setPhone}
          email={email}
          onEmailChange={setEmail}
          website={website}
          onWebsiteChange={setWebsite}
          notes={notes}
          onNotesChange={setNotes}
          isTransFriendly={isTransFriendly}
          onIsTransFriendlyChange={setIsTransFriendly}
          saving={saving}
          isValid={name.trim().length > 0}
          backHref="/practitioners"
          labels={{
            basicInfo: t('edit.basicInfo'),
            fullName: t('edit.fullName'),
            namePlaceholder: t('edit.namePlaceholder'),
            specialty: t('edit.specialty'),
            transFriendly: t('edit.transFriendly'),
            transFriendlyDesc: t('edit.transFriendlyDesc'),
            contact: t('edit.contact'),
            address: t('edit.address'),
            addressPlaceholder: t('edit.addressPlaceholder'),
            phone: t('edit.phone'),
            phonePlaceholder: t('edit.phonePlaceholder'),
            email: t('edit.email'),
            emailPlaceholder: t('edit.emailPlaceholder'),
            website: t('edit.website'),
            websitePlaceholder: t('edit.websitePlaceholder'),
            notes: t('edit.notes'),
            notesPlaceholder: t('edit.notesPlaceholder'),
            cancel: t('editPage.cancel'),
            save: t('editPage.save'),
            saving: t('editPage.saving'),
          }}
        />
      </form>
    </div>
  )
}
