// src/routes/journal/new/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation'
  import { set as setDateFields } from 'date-fns'
  import { i18n } from '$lib/i18n.svelte'
  import { addJournalEntry } from '$lib/db'
  import type { MoodLevel } from '$lib/types'
  import JournalFormFields from '$lib/components/journal/JournalFormFields.svelte'
  import ArrowLeft from '@lucide/svelte/icons/arrow-left'

  let saving = $state(false)

  let date = $state(new Date().toISOString().split('T')[0]!)
  let content = $state('')
  let mood = $state<MoodLevel | undefined>(undefined)
  let energyLevel = $state<MoodLevel | undefined>(undefined)
  let sleepQuality = $state<MoodLevel | undefined>(undefined)
  let tags = $state<string[]>([])
  let isPrivate = $state(false)

  function withTimeOfDay(dateStr: string, source: Date): Date {
    const [year, month, day] = dateStr.split('-').map(Number)
    return setDateFields(source, { year, month: (month ?? 1) - 1, date: day, seconds: 0 })
  }

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault()
    if (!content.trim()) return

    saving = true
    try {
      await addJournalEntry({
        date: withTimeOfDay(date, new Date()),
        content: content.trim(),
        mood,
        tags: $state.snapshot(tags),
        energyLevel,
        sleepQuality,
        isPrivate,
      })
      await goto('/journal')
    } catch {
      saving = false
    }
  }
</script>

<div class="header">
  <a href="/journal" class="icon-link" aria-label={i18n.t('common.back')}><ArrowLeft size={20} /></a
  >
  <div>
    <h1>{i18n.t('journal.new.title')}</h1>
    <p class="subtitle">{i18n.t('journal.new.subtitle')}</p>
  </div>
</div>

<form onsubmit={handleSubmit}>
  <JournalFormFields
    bind:date
    bind:content
    bind:mood
    bind:energyLevel
    bind:sleepQuality
    bind:tags
    bind:isPrivate
    variant="new"
    {saving}
  />
</form>

<style>
  .header {
    display: flex;
    align-items: center;
    gap: 10px;
    margin-bottom: 18px;
  }
  h1 {
    font-size: 19px;
    font-weight: 700;
    margin: 0;
  }
  .subtitle {
    font-size: 12.5px;
    color: var(--ink-soft);
    margin: 2px 0 0;
  }
  .icon-link {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 36px;
    height: 36px;
    border-radius: 10px;
    color: var(--ink);
    text-decoration: none;
    flex-shrink: 0;
  }
</style>

// src/app/journal/new/page.tsx
'use client'

import { useState } from 'react'
import { useTranslations, useLocale } from 'next-intl'
import { getDateLocale } from '@/i18n/date-locale'
import type { Locale } from '@/i18n/config'
import { useRouter } from 'next/navigation'
import { Button } from '@/components/ui/button'
import { ArrowLeft } from 'lucide-react'
import Link from 'next/link'
import { addJournalEntry } from '@/lib/db'
import type { MoodLevel } from '@/lib/types'
import { JournalFormFields } from '@/components/journal/JournalFormFields'

export default function NewJournalEntryPage() {
  const t = useTranslations('journal')
  const router = useRouter()
  const locale = useLocale()
  const dateLocale = getDateLocale(locale as Locale)
  const [saving, setSaving] = useState(false)

  // Form state
  const [content, setContent] = useState('')
  const [mood, setMood] = useState<MoodLevel | undefined>()
  const [tags, setTags] = useState<string[]>([])
  const [energyLevel, setEnergyLevel] = useState<MoodLevel | undefined>()
  const [sleepQuality, setSleepQuality] = useState<MoodLevel | undefined>()
  const [isPrivate, setIsPrivate] = useState(false)
  const [entryDate, setEntryDate] = useState<Date>(new Date())

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()

    if (!content.trim()) return

    setSaving(true)
    try {
      await addJournalEntry({
        date: entryDate,
        content: content.trim(),
        mood,
        tags,
        energyLevel,
        sleepQuality,
        isPrivate,
      })
      router.push('/journal')
    } catch (error) {
      console.error('Failed to save entry:', error)
      setSaving(false)
    }
  }

  return (
    <div className="space-y-6 p-4 pb-24">
      <div className="flex items-center gap-3 pt-2">
        <Link href="/journal">
          <Button variant="ghost" size="icon" className="shrink-0">
            <ArrowLeft className="h-5 w-5" />
          </Button>
        </Link>
        <div>
          <h1 className="text-foreground text-2xl font-bold">{t('new.title')}</h1>
          <p className="text-muted-foreground text-sm">{t('new.subtitle')}</p>
        </div>
      </div>

      <form onSubmit={handleSubmit} className="space-y-6">
        <JournalFormFields
          content={content}
          onContentChange={setContent}
          mood={mood}
          onMoodChange={setMood}
          tags={tags}
          onTagsChange={setTags}
          energyLevel={energyLevel}
          onEnergyLevelChange={setEnergyLevel}
          sleepQuality={sleepQuality}
          onSleepQualityChange={setSleepQuality}
          isPrivate={isPrivate}
          onIsPrivateChange={setIsPrivate}
          entryDate={entryDate}
          onEntryDateChange={setEntryDate}
          dateLocale={dateLocale}
          saving={saving}
          isValid={content.trim().length > 0}
          labels={{
            dateLabel: t('new.dateLabel'),
            contentLabel: t('new.contentLabel'),
            contentPlaceholder: t('new.contentPlaceholder'),
            howFeeling: t('new.howFeeling'),
            generalMood: t('new.generalMood'),
            energyLevel: t('new.energyLevel'),
            sleepQuality: t('new.sleepQuality'),
            tags: t('new.tags'),
            addTags: t('new.addTags'),
            privateEntry: t('new.privateEntry'),
            excludeExport: t('new.excludeExport'),
            save: t('new.save'),
            saving: t('new.saving'),
          }}
        />
      </form>
    </div>
  )
}
