// src/components/appointments/AppointmentFormFields.tsx
'use client'

import { useTranslations } from 'next-intl'
import Link from 'next/link'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Calendar } from '@/components/ui/calendar'
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover'
import { Calendar as CalendarIcon, Clock, Bell, Coins } from 'lucide-react'
import { APPOINTMENT_TYPES, REMINDER_TIMES } from '@/lib/constants'
import type { AppointmentType, Objective, Practitioner } from '@/lib/types'
import { format } from 'date-fns'
import type { Locale as DateFnsLocale } from 'date-fns'
import { PractitionerInput } from '@/components/appointments/practitioner-input'

interface AppointmentLabels {
  typeLabel: string
  selectType: string
  dateAndTime: string
  dateLabel: string
  selectDate: string
  timeLabel: string
  details: string
  practitionerLabel: string
  practitionerPlaceholder: string
  locationLabel: string
  locationPlaceholder: string
  notesLabel: string
  notesPlaceholder: string
  linkedObjective?: string
  noLinkedObjective?: string
  costLabel: string
  costPlaceholder: string
  reminderTitle: string
  reminderConfig: string
  noReminder: string
  save: string
  saving: string
}

interface Props {
  type: AppointmentType
  onTypeChange: (v: AppointmentType) => void
  date: Date | undefined
  onDateChange: (v: Date | undefined) => void
  time: string
  onTimeChange: (v: string) => void
  doctor: string
  onPractitionerChange: (name: string, id?: number) => void
  onPractitionerSelect: (practitioner: Practitioner) => void
  location: string
  onLocationChange: (v: string) => void
  notes: string
  onNotesChange: (v: string) => void
  reminderMinutes: number | undefined
  onReminderMinutesChange: (v: number | undefined) => void
  cost: string
  onCostChange: (v: string) => void
  showCostTracking: boolean
  linkedObjectives?: Objective[]
  objectiveId?: number
  onObjectiveIdChange?: (v: number | undefined) => void
  saving: boolean
  dateLocale: DateFnsLocale
  labels: AppointmentLabels
}

export function AppointmentFormFields({
  type,
  onTypeChange,
  date,
  onDateChange,
  time,
  onTimeChange,
  doctor,
  onPractitionerChange,
  onPractitionerSelect,
  location,
  onLocationChange,
  notes,
  onNotesChange,
  reminderMinutes,
  onReminderMinutesChange,
  cost,
  onCostChange,
  showCostTracking,
  linkedObjectives,
  objectiveId,
  onObjectiveIdChange,
  saving,
  dateLocale,
  labels,
}: Props) {
  const t = useTranslations('appointments')

  return (
    <>
      {/* Type */}
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-base">{labels.typeLabel}</CardTitle>
        </CardHeader>
        <CardContent>
          <Select value={type} onValueChange={(v) => onTypeChange(v as AppointmentType)}>
            <SelectTrigger>
              <SelectValue placeholder={labels.selectType} />
            </SelectTrigger>
            <SelectContent>
              {(
                Object.entries(APPOINTMENT_TYPES) as [
                  AppointmentType,
                  { label: string; color: string },
                ][]
              ).map(([key, { color }]) => (
                <SelectItem key={key} value={key}>
                  <div className="flex items-center gap-2">
                    <div className="h-3 w-3 rounded-full" style={{ backgroundColor: color }} />
                    {t('types.' + key)}
                  </div>
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </CardContent>
      </Card>

      {/* Date & Time */}
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-base">{labels.dateAndTime}</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label>{labels.dateLabel}</Label>
            <Popover>
              <PopoverTrigger asChild>
                <Button variant="outline" className="w-full justify-start text-left font-normal">
                  <CalendarIcon className="mr-2 h-4 w-4" />
                  {date ? (
                    format(date, 'EEEE d MMMM yyyy', { locale: dateLocale })
                  ) : (
                    <span className="text-muted-foreground">{labels.selectDate}</span>
                  )}
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-auto p-0" align="start">
                <Calendar
                  mode="single"
                  selected={date}
                  onSelect={onDateChange}
                  locale={dateLocale}
                  initialFocus
                />
              </PopoverContent>
            </Popover>
          </div>

          <div className="space-y-2">
            <Label htmlFor="time">{labels.timeLabel}</Label>
            <div className="relative">
              <Clock className="text-muted-foreground absolute top-1/2 left-3 h-4 w-4 -translate-y-1/2" />
              <Input
                id="time"
                type="time"
                value={time}
                onChange={(e) => onTimeChange(e.target.value)}
                className="pl-10"
              />
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Details */}
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-base">{labels.details}</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="doctor">{labels.practitionerLabel}</Label>
            <PractitionerInput
              id="doctor"
              value={doctor}
              onChange={onPractitionerChange}
              onSelect={onPractitionerSelect}
              specialty={type}
              placeholder={labels.practitionerPlaceholder}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="location">{labels.locationLabel}</Label>
            <Input
              id="location"
              value={location}
              onChange={(e) => onLocationChange(e.target.value)}
              placeholder={labels.locationPlaceholder}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="notes">{labels.notesLabel}</Label>
            <Textarea
              id="notes"
              value={notes}
              onChange={(e) => onNotesChange(e.target.value)}
              placeholder={labels.notesPlaceholder}
              rows={3}
            />
          </div>

          {linkedObjectives && linkedObjectives.length > 0 && onObjectiveIdChange && (
            <div className="space-y-2">
              <Label>{labels.linkedObjective}</Label>
              <Select
                value={objectiveId?.toString() || 'none'}
                onValueChange={(v) => onObjectiveIdChange(v === 'none' ? undefined : parseInt(v))}
              >
                <SelectTrigger>
                  <SelectValue placeholder={labels.linkedObjective} />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="none">{labels.noLinkedObjective}</SelectItem>
                  {linkedObjectives.map((obj) => (
                    <SelectItem key={obj.id} value={obj.id!.toString()}>
                      {obj.title}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          )}

          {showCostTracking && (
            <div className="space-y-2">
              <Label htmlFor="cost" className="flex items-center gap-2">
                <Coins className="h-4 w-4" />
                {labels.costLabel}
              </Label>
              <Input
                id="cost"
                type="number"
                min="0"
                max="99999.99"
                step="0.01"
                value={cost}
                onChange={(e) => onCostChange(e.target.value)}
                placeholder={labels.costPlaceholder}
              />
            </div>
          )}
        </CardContent>
      </Card>

      {/* Reminder */}
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="flex items-center gap-2 text-base">
            <Bell className="h-4 w-4" />
            {labels.reminderTitle}
          </CardTitle>
        </CardHeader>
        <CardContent>
          <Select
            value={reminderMinutes?.toString() || 'none'}
            onValueChange={(v) => onReminderMinutesChange(v === 'none' ? undefined : parseInt(v))}
          >
            <SelectTrigger>
              <SelectValue placeholder={labels.reminderConfig} />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="none">{labels.noReminder}</SelectItem>
              {REMINDER_TIMES.map(({ value }) => (
                <SelectItem key={value} value={value.toString()}>
                  {t('reminderTimes.' + value)}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </CardContent>
      </Card>

      {/* Submit */}
      <Button type="submit" className="w-full" disabled={saving || !date}>
        {saving ? labels.saving : labels.save}
      </Button>
    </>
  )
}

// src/lib/components/appointments/AppointmentFormFields.svelte
<script lang="ts">
  import { i18n } from '$lib/i18n.svelte'
  import { APPOINTMENT_TYPES, REMINDER_TIMES } from '$lib/constants'
  import type { AppointmentType, Objective } from '$lib/types'
  import PractitionerInput from '$lib/components/practitioners/PractitionerInput.svelte'

  const TYPES = Object.keys(APPOINTMENT_TYPES) as AppointmentType[]

  let {
    date = $bindable(),
    time = $bindable(),
    type = $bindable(),
    doctor = $bindable(),
    practitionerId = $bindable(),
    location = $bindable(),
    notes = $bindable(),
    cost = $bindable(),
    reminderMinutes = $bindable(),
    objectiveId = $bindable(),
    objectives,
    saving,
    backHref,
  }: {
    date: string
    time: string
    type: AppointmentType
    doctor: string
    practitionerId: number | undefined
    location: string
    notes: string
    cost: string
    reminderMinutes: string
    objectiveId: string
    objectives: Objective[]
    saving: boolean
    backHref: string
  } = $props()
</script>

<div class="card">
  <p class="card-title">{i18n.t('appointments.form.dateAndTime')}</p>
  <div class="field-row">
    <div class="field">
      <label for="date">{i18n.t('appointments.form.dateLabel')}</label>
      <input id="date" type="date" bind:value={date} required />
    </div>
    <div class="field">
      <label for="time">{i18n.t('appointments.form.timeLabel')}</label>
      <input id="time" type="time" bind:value={time} />
    </div>
  </div>
  <div class="field">
    <label for="type">{i18n.t('appointments.form.typeLabel')}</label>
    <select id="type" bind:value={type}>
      {#each TYPES as t (t)}
        <option value={t}>{i18n.t('appointments.types.' + t)}</option>
      {/each}
    </select>
  </div>
</div>

<div class="card">
  <p class="card-title">{i18n.t('appointments.form.details')}</p>
  <div class="field">
    <label for="doctor">{i18n.t('appointments.form.practitionerLabel')}</label>
    <PractitionerInput
      id="doctor"
      bind:value={doctor}
      bind:practitionerId
      specialty={type}
      placeholder={i18n.t('appointments.form.practitionerPlaceholder')}
      onSelect={(practitioner) => {
        if (practitioner.location && !location) location = practitioner.location
      }}
    />
  </div>
  <div class="field">
    <label for="location">{i18n.t('appointments.form.locationLabel')}</label>
    <input
      id="location"
      type="text"
      bind:value={location}
      placeholder={i18n.t('appointments.form.locationPlaceholder')}
    />
  </div>
  <div class="field-row">
    <div class="field">
      <label for="cost">{i18n.t('appointments.form.costLabel')}</label>
      <input
        id="cost"
        type="number"
        step="0.01"
        min="0"
        bind:value={cost}
        placeholder={i18n.t('appointments.form.costPlaceholder')}
      />
    </div>
    <div class="field">
      <label for="reminder">{i18n.t('appointments.form.reminderTitle')}</label>
      <select id="reminder" bind:value={reminderMinutes}>
        <option value="">{i18n.t('appointments.form.noReminder')}</option>
        {#each REMINDER_TIMES as r (r.value)}
          <option value={String(r.value)}>{i18n.t('appointments.reminderTimes.' + r.value)}</option>
        {/each}
      </select>
    </div>
  </div>
  <div class="field">
    <label for="objective">{i18n.t('appointments.form.linkedObjective')}</label>
    <select id="objective" bind:value={objectiveId}>
      <option value="">{i18n.t('appointments.form.noLinkedObjective')}</option>
      {#each objectives as objective (objective.id)}
        <option value={String(objective.id)}>{objective.title}</option>
      {/each}
    </select>
  </div>
  <div class="field">
    <label for="notes">{i18n.t('appointments.form.notesLabel')}</label>
    <textarea
      id="notes"
      bind:value={notes}
      placeholder={i18n.t('appointments.form.notesPlaceholder')}
      rows="3"
    ></textarea>
  </div>
</div>

<div class="actions">
  <a href={backHref} class="btn-outline-sm">{i18n.t('common.cancel')}</a>
  <button type="submit" class="btn-primary-sm" disabled={saving}>
    {saving ? i18n.t('common.saving') : i18n.t('common.save')}
  </button>
</div>

<style>
  .card {
    background: var(--bg);
    border: 1px solid var(--line);
    border-radius: 16px;
    padding: 16px;
    margin-bottom: 14px;
  }
  .card-title {
    font-size: 13px;
    font-weight: 600;
    margin: 0 0 10px;
  }
  .field-row {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 10px;
  }
  .field {
    display: flex;
    flex-direction: column;
    margin-bottom: 10px;
  }
  .field:last-child {
    margin-bottom: 0;
  }
  label {
    font-size: 12px;
    color: var(--ink-soft);
    margin-bottom: 5px;
  }
  input,
  select,
  textarea {
    width: 100%;
    padding: 9px 11px;
    border: 1px solid var(--line);
    border-radius: 9px;
    background: var(--page);
    color: var(--ink);
    font-family: inherit;
    font-size: 13.5px;
  }
  .actions {
    display: flex;
    gap: 10px;
  }
  .btn-outline-sm,
  .btn-primary-sm {
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 10px 14px;
    border-radius: 10px;
    font-size: 13.5px;
    font-weight: 600;
    font-family: inherit;
    cursor: pointer;
    text-decoration: none;
    border: 1px solid var(--line);
    background: var(--page);
    color: var(--ink);
  }
  .btn-primary-sm {
    border: none;
    background: linear-gradient(135deg, var(--blue-deep), var(--pink-deep));
    color: #fff;
  }
  .btn-primary-sm:disabled {
    opacity: 0.5;
    cursor: default;
  }
</style>
