// src/routes/bloodtests/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { format } from 'date-fns'
  import { i18n, getDateLocale } from '$lib/i18n.svelte'
  import { getBloodTests, deleteBloodTest, getUserProfile } from '$lib/db'
  import { getHematocritStatus, BLOOD_MARKERS, REFERENCE_RANGES } from '$lib/constants'
  import type { BloodTest, BloodMarker } from '$lib/types'
  import HormoneChart from '$lib/components/bloodtests/HormoneChart.svelte'
  import ExportButton from '$lib/components/ui/ExportButton.svelte'
  import Plus from '@lucide/svelte/icons/plus'
  import TrendingUp from '@lucide/svelte/icons/trending-up'
  import ListIcon from '@lucide/svelte/icons/list'
  import Pencil from '@lucide/svelte/icons/pencil'
  import Trash2 from '@lucide/svelte/icons/trash-2'
  import ChevronRight from '@lucide/svelte/icons/chevron-right'
  import TestTube from '@lucide/svelte/icons/test-tube'

  let tests = $state<BloodTest[]>([])
  let loading = $state(true)
  let context = $state<'feminizing' | 'masculinizing'>('feminizing')
  let activeTab = $state<'charts' | 'list'>('charts')
  let userName = $state<string | undefined>()
  let chartRef = $state<HTMLDivElement>()

  onMount(async () => {
    const [testsData, profile] = await Promise.all([getBloodTests(50), getUserProfile()])
    tests = testsData
    if (profile?.targetGender) {
      context = profile.targetGender === 'masculinizing' ? 'masculinizing' : 'feminizing'
    }
    if (profile?.firstName) {
      userName = profile.firstName
    }
    loading = false
  })

  function getMarkerStatus(marker: BloodMarker, value: number): 'normal' | 'low' | 'high' {
    const range = REFERENCE_RANGES.find((r) => r.marker === marker && r.context === context)
    if (!range) return 'normal'
    if (value < range.min) return 'low'
    if (value > range.max) return 'high'
    return 'normal'
  }

  async function handleDelete(id: number) {
    if (!confirm(i18n.t('bloodtests.confirmDelete'))) return
    await deleteBloodTest(id)
    tests = tests.filter((t) => t.id !== id)
  }

  let mainHormones = $derived<BloodMarker[]>(
    context === 'feminizing' ? ['estradiol', 'testosterone'] : ['testosterone', 'estradiol']
  )

  let hasSafetyMarkers = $derived(
    tests.some((t) =>
      t.results.some((r) => ['prolactin', 'hematocrit', 'alt', 'potassium'].includes(r.marker))
    )
  )

  let hormoneExportData = $derived(
    mainHormones
      .map((marker) => {
        const lastValue = tests[0]?.results.find((r) => r.marker === marker)
        if (!lastValue) return null
        const range = REFERENCE_RANGES.find((r) => r.marker === marker && r.context === context)
        return {
          marker,
          label: i18n.t('bloodtests.markers.' + marker),
          value: lastValue.value,
          unit: BLOOD_MARKERS[marker].unit,
          targetMin: range?.min,
          targetMax: range?.max,
          status: getMarkerStatus(marker, lastValue.value),
        }
      })
      .filter((d): d is NonNullable<typeof d> => d !== null)
  )
</script>

<div class="header">
  <div>
    <h1>{i18n.t('bloodtests.title')}</h1>
    <p class="subtitle">
      {tests.length}
      {tests.length > 1
        ? i18n.t('bloodtests.list.recordedPlural')
        : i18n.t('bloodtests.list.recorded')}
    </p>
  </div>
  <a href="/bloodtests/new" class="btn-primary-sm">
    <Plus size={16} />
    {i18n.t('bloodtests.add')}
  </a>
</div>

{#if loading}
  <p class="loading">{i18n.t('bloodtests.loading')}</p>
{:else if tests.length === 0}
  <div class="empty-card">
    <TestTube size={28} />
    <h3>{i18n.t('bloodtests.list.empty')}</h3>
    <p>{i18n.t('bloodtests.list.emptyDesc')}</p>
    <a href="/bloodtests/new" class="btn-primary-sm">
      <Plus size={16} />
      {i18n.t('bloodtests.list.addOne')}
    </a>
  </div>
{:else}
  <div class="tabs">
    <button
      type="button"
      class:active={activeTab === 'charts'}
      onclick={() => (activeTab = 'charts')}
    >
      <TrendingUp size={15} />
      {i18n.t('bloodtests.list.chartsTab')}
    </button>
    <button type="button" class:active={activeTab === 'list'} onclick={() => (activeTab = 'list')}>
      <ListIcon size={15} />
      {i18n.t('bloodtests.list.historyTab')}
    </button>
  </div>

  {#if activeTab === 'charts'}
    <div class="card">
      <div class="card-head">
        <p class="card-title">
          {context === 'feminizing'
            ? i18n.t('bloodtests.hormonesFem')
            : i18n.t('bloodtests.hormonesMas')}
        </p>
        {#if tests.length > 0}
          <ExportButton
            {chartRef}
            title={i18n.t('bloodtests.hormoneTracking')}
            subtitle={context === 'feminizing'
              ? i18n.t('bloodtests.thsFem')
              : i18n.t('bloodtests.thsMas')}
            {userName}
            data={hormoneExportData}
          />
        {/if}
      </div>
      <div bind:this={chartRef}>
        <HormoneChart
          {tests}
          series={mainHormones.map((marker) => ({
            marker,
            color: marker === 'estradiol' ? 'var(--pink-deep)' : 'var(--blue-deep)',
          }))}
          {context}
        />
      </div>
    </div>

    {#if hasSafetyMarkers}
      <div class="card">
        <p class="card-title">{i18n.t('bloodtests.list.safetyMarkers')}</p>
        <HormoneChart
          {tests}
          series={[
            { marker: 'prolactin', color: 'var(--gold)' },
            { marker: 'hematocrit', color: 'var(--blue-deep)' },
          ]}
          {context}
        />
      </div>
    {/if}
  {:else}
    <div class="test-list">
      {#each tests as test (test.id)}
        <div class="test-card">
          <div class="test-head">
            <div>
              <span class="date"
                >{format(new Date(test.date), 'd MMMM yyyy', {
                  locale: getDateLocale(i18n.locale),
                })}</span
              >
              {#if test.lab}
                <span class="lab-badge">{test.lab}</span>
              {/if}
            </div>
            <div class="test-actions">
              <a
                href={`/bloodtests/${test.id}/edit`}
                class="icon-link"
                aria-label={i18n.t('common.edit')}><Pencil size={16} /></a
              >
              <button
                type="button"
                class="icon-link danger"
                onclick={() => test.id && handleDelete(test.id)}
                aria-label={i18n.t('common.delete')}
              >
                <Trash2 size={16} />
              </button>
              <a
                href={`/bloodtests/${test.id}`}
                class="icon-link"
                aria-label={i18n.t('bloodtests.list.detailsLabel')}><ChevronRight size={16} /></a
              >
            </div>
          </div>
          <div class="results-row">
            {#each test.results.slice(0, 4) as result (result.marker)}
              {@const status =
                result.marker === 'hematocrit' ? getHematocritStatus(result.value) : 'ok'}
              <span class="result">
                <span class="result-label">{i18n.t('bloodtests.markers.' + result.marker)}:</span>
                <span class:watch={status === 'watch'} class:alert={status === 'alert'}
                  >{result.value}</span
                >
              </span>
            {/each}
            {#if test.results.length > 4}
              <span class="result-more"
                >+{test.results.length - 4} {i18n.t('bloodtests.othersSuffix')}</span
              >
            {/if}
          </div>
          {#if test.notes}
            <p class="notes-preview">{test.notes}</p>
          {/if}
        </div>
      {/each}
    </div>
  {/if}
{/if}

<style>
  .loading {
    color: var(--ink-soft);
    text-align: center;
    padding: 40px 0;
  }
  .header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    margin-bottom: 18px;
  }
  h1 {
    font-size: 21px;
    font-weight: 700;
    margin: 0;
  }
  .subtitle {
    font-size: 12.5px;
    color: var(--ink-soft);
    margin: 2px 0 0;
  }
  .btn-primary-sm {
    display: flex;
    align-items: center;
    gap: 5px;
    padding: 8px 14px;
    border-radius: 10px;
    background: linear-gradient(135deg, var(--blue-deep), var(--pink-deep));
    color: #fff;
    font-size: 13px;
    font-weight: 600;
    text-decoration: none;
    border: none;
    cursor: pointer;
  }
  .empty-card {
    text-align: center;
    padding: 40px 16px;
    border: 1px solid var(--line);
    border-radius: 16px;
    color: var(--ink-soft);
  }
  .empty-card h3 {
    font-size: 15px;
    color: var(--ink);
    margin: 12px 0 6px;
  }
  .empty-card p {
    font-size: 13px;
    margin: 0 0 16px;
  }
  .empty-card .btn-primary-sm {
    display: inline-flex;
  }
  .tabs {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 8px;
    margin-bottom: 14px;
  }
  .tabs button {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 6px;
    padding: 9px;
    border-radius: 10px;
    border: 1px solid var(--line);
    background: var(--bg);
    color: var(--ink-soft);
    font-size: 13px;
    font-weight: 600;
    font-family: inherit;
    cursor: pointer;
  }
  .tabs button.active {
    background: linear-gradient(135deg, var(--blue-deep), var(--pink-deep));
    color: #fff;
    border-color: transparent;
  }
  .card {
    background: var(--bg);
    border: 1px solid var(--line);
    border-radius: 16px;
    padding: 16px;
    margin-bottom: 14px;
  }
  .card-title {
    font-size: 13px;
    font-weight: 600;
    margin: 0 0 10px;
  }
  .card-head {
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    gap: 10px;
  }
  .test-list {
    display: flex;
    flex-direction: column;
    gap: 12px;
  }
  .test-card {
    border: 1px solid var(--line);
    border-radius: 16px;
    padding: 14px;
    background: var(--bg);
  }
  .test-head {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
  }
  .date {
    font-size: 14.5px;
    font-weight: 600;
  }
  .lab-badge {
    margin-left: 8px;
    font-size: 11px;
    padding: 2px 8px;
    border-radius: 999px;
    border: 1px solid var(--line);
    color: var(--ink-soft);
  }
  .test-actions {
    display: flex;
    gap: 2px;
  }
  .icon-link {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 32px;
    height: 32px;
    border-radius: 9px;
    color: var(--ink-soft);
    text-decoration: none;
    border: none;
    background: transparent;
    cursor: pointer;
  }
  .icon-link.danger:hover {
    color: var(--alert);
  }
  .results-row {
    display: flex;
    flex-wrap: wrap;
    gap: 4px 14px;
    margin-top: 10px;
    font-size: 13px;
  }
  .result-label {
    color: var(--ink-soft);
  }
  .result .watch {
    color: var(--watch);
    font-weight: 600;
  }
  .result .alert {
    color: var(--alert);
    font-weight: 600;
  }
  .result-more {
    font-size: 13px;
    color: var(--ink-soft);
  }
  .notes-preview {
    font-size: 12.5px;
    color: var(--ink-soft);
    margin: 8px 0 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
</style>

// src/app/bloodtests/page.tsx
'use client'

import { useEffect, useState, useRef } from 'react'
import { useTranslations, useLocale } from 'next-intl'
import { getDateLocale } from '@/i18n/date-locale'
import type { Locale } from '@/i18n/config'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { TestTube, Plus, TrendingUp, List, ChevronRight, Trash2, Pencil } from 'lucide-react'
import Link from 'next/link'
import { format } from 'date-fns'
import { getBloodTests, deleteBloodTest, getUserProfile } from '@/lib/db'
import type { BloodTest, BloodMarker } from '@/lib/types'
import { BLOOD_MARKERS, REFERENCE_RANGES } from '@/lib/constants'
import { HormoneChart } from '@/components/bloodtests/hormone-chart'
import { ExportButton } from '@/components/ui/export-button'

export default function BloodTestsPage() {
  const t = useTranslations('bloodtests')
  const locale = useLocale()
  const dateLocale = getDateLocale(locale as Locale)
  const [tests, setTests] = useState<BloodTest[]>([])
  const [loading, setLoading] = useState(true)
  const [context, setContext] = useState<'feminizing' | 'masculinizing'>('feminizing')
  const [userName, setUserName] = useState<string | undefined>()
  const chartRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    async function load() {
      const [testsData, profile] = await Promise.all([getBloodTests(50), getUserProfile()])
      setTests(testsData)
      if (profile?.targetGender) {
        setContext(profile.targetGender === 'masculinizing' ? 'masculinizing' : 'feminizing')
      }
      if (profile?.firstName) {
        setUserName(profile.firstName)
      }
      setLoading(false)
    }
    load()
  }, [])

  async function handleDelete(id: number) {
    if (!confirm(t('confirmDelete'))) return
    await deleteBloodTest(id)
    setTests(tests.filter((t) => t.id !== id))
  }

  // Get status for a marker value
  function getMarkerStatus(marker: BloodMarker, value: number): 'normal' | 'low' | 'high' {
    const range = REFERENCE_RANGES.find((r) => r.marker === marker && r.context === context)
    if (!range) return 'normal'
    if (value < range.min) return 'low'
    if (value > range.max) return 'high'
    return 'normal'
  }

  // Main hormone markers for summary
  const mainHormones: BloodMarker[] =
    context === 'feminizing' ? ['estradiol', 'testosterone'] : ['testosterone', 'estradiol']

  if (loading) {
    return (
      <div className="space-y-6 p-4">
        <div className="pt-2">
          <h1 className="text-foreground text-2xl font-bold">{t('title')}</h1>
          <p className="text-muted-foreground text-sm">{t('loading')}</p>
        </div>
      </div>
    )
  }

  if (tests.length === 0) {
    return (
      <div className="space-y-6 p-4">
        <div className="flex items-center justify-between pt-2">
          <div>
            <h1 className="text-foreground text-2xl font-bold">{t('title')}</h1>
            <p className="text-muted-foreground text-sm">{t('list.subtitle')}</p>
          </div>
          <Link href="/bloodtests/new">
            <Button size="sm" className="gap-2">
              <Plus className="h-4 w-4" />
              {t('add')}
            </Button>
          </Link>
        </div>

        <Card>
          <CardContent className="py-12 text-center">
            <div className="bg-muted/50 mx-auto mb-4 w-fit rounded-full p-4">
              <TestTube className="text-muted-foreground h-8 w-8" />
            </div>
            <h3 className="text-foreground mb-2 font-medium">{t('list.empty')}</h3>
            <p className="text-muted-foreground mb-4 text-sm">{t('list.emptyDesc')}</p>
            <Link href="/bloodtests/new">
              <Button className="gap-2">
                <Plus className="h-4 w-4" />
                {t('list.addOne')}
              </Button>
            </Link>
          </CardContent>
        </Card>
      </div>
    )
  }

  return (
    <div className="space-y-6 p-4 pb-24">
      {/* Header */}
      <div className="flex items-center justify-between pt-2">
        <div>
          <h1 className="text-foreground text-2xl font-bold">{t('title')}</h1>
          <p className="text-muted-foreground text-sm">
            {tests.length} {tests.length > 1 ? t('list.recordedPlural') : t('list.recorded')}
          </p>
        </div>
        <Link href="/bloodtests/new">
          <Button size="sm" className="gap-2">
            <Plus className="h-4 w-4" />
            {t('add')}
          </Button>
        </Link>
      </div>

      {/* Tabs: Charts / List */}
      <Tabs defaultValue="charts" className="space-y-4">
        <TabsList className="grid w-full grid-cols-2">
          <TabsTrigger value="charts" className="gap-2">
            <TrendingUp className="h-4 w-4" />
            {t('list.chartsTab')}
          </TabsTrigger>
          <TabsTrigger value="list" className="gap-2">
            <List className="h-4 w-4" />
            {t('list.historyTab')}
          </TabsTrigger>
        </TabsList>

        {/* Charts Tab */}
        <TabsContent value="charts" className="space-y-4">
          {/* Main hormones chart */}
          <Card>
            <CardHeader className="pb-2">
              <div className="flex items-center justify-between">
                <CardTitle className="text-base">
                  {context === 'feminizing' ? t('hormonesFem') : t('hormonesMas')}
                </CardTitle>
                {tests.length > 0 && (
                  <ExportButton
                    chartRef={chartRef}
                    title={t('hormoneTracking')}
                    subtitle={context === 'feminizing' ? t('thsFem') : t('thsMas')}
                    userName={userName}
                    data={mainHormones
                      .map((marker) => {
                        const lastValue = tests[0]?.results.find((r) => r.marker === marker)
                        const range = REFERENCE_RANGES.find(
                          (r) => r.marker === marker && r.context === context
                        )
                        const markerInfo = BLOOD_MARKERS[marker]
                        if (!lastValue) return null
                        return {
                          marker,
                          label: t('markers.' + marker),
                          value: lastValue.value,
                          unit: markerInfo.unit,
                          targetMin: range?.min,
                          targetMax: range?.max,
                          status: getMarkerStatus(marker, lastValue.value),
                        }
                      })
                      .filter((d): d is NonNullable<typeof d> => d !== null)}
                  />
                )}
              </div>
            </CardHeader>
            <CardContent>
              <div ref={chartRef}>
                {tests.length >= 1 ? (
                  <HormoneChart
                    tests={tests}
                    markers={mainHormones}
                    context={context}
                    height={280}
                  />
                ) : (
                  <p className="text-muted-foreground py-8 text-center text-sm">
                    {t('addForChart')}
                  </p>
                )}
              </div>

              {/* Legend with current values */}
              {tests.length > 0 && (
                <div className="border-border mt-4 border-t pt-4">
                  <p className="text-muted-foreground mb-2 text-xs">{t('lastAnalysis')}</p>
                  <div className="flex flex-wrap gap-4">
                    {mainHormones.map((marker) => {
                      const lastValue = tests[0]?.results.find((r) => r.marker === marker)
                      if (!lastValue) return null

                      const status = getMarkerStatus(marker, lastValue.value)
                      const markerInfo = BLOOD_MARKERS[marker]
                      const range = REFERENCE_RANGES.find(
                        (r) => r.marker === marker && r.context === context
                      )

                      return (
                        <div key={marker} className="flex items-center gap-2">
                          <div
                            className="h-3 w-3 rounded-full"
                            style={{
                              backgroundColor: marker === 'estradiol' ? '#F5A9B8' : '#5BCEFA',
                            }}
                          />
                          <span className="text-sm">
                            {t('markers.' + marker)}:{' '}
                            <span
                              className={
                                status === 'normal'
                                  ? 'text-green-500'
                                  : status === 'low'
                                    ? 'text-yellow-500'
                                    : 'text-red-500'
                              }
                            >
                              {lastValue.value} {markerInfo.unit}
                            </span>
                          </span>
                          {range && (
                            <span className="text-muted-foreground text-xs">
                              ({t('target')}: {range.min}-{range.max})
                            </span>
                          )}
                        </div>
                      )
                    })}
                  </div>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Secondary markers */}
          {tests.some((t) =>
            t.results.some((r) =>
              ['prolactin', 'hematocrit', 'alt', 'potassium'].includes(r.marker)
            )
          ) && (
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-base">{t('list.safetyMarkers')}</CardTitle>
              </CardHeader>
              <CardContent>
                <HormoneChart
                  tests={tests}
                  markers={['prolactin', 'hematocrit'] as BloodMarker[]}
                  context={context}
                  height={200}
                />
              </CardContent>
            </Card>
          )}
        </TabsContent>

        {/* List Tab */}
        <TabsContent value="list" className="space-y-3">
          {tests.map((test) => (
            <Card key={test.id}>
              <CardContent className="p-4">
                <div className="flex items-start justify-between">
                  <div className="flex-1">
                    <div className="mb-2 flex items-center gap-2">
                      <span className="text-foreground font-medium">
                        {format(new Date(test.date), 'dd MMMM yyyy', { locale: dateLocale })}
                      </span>
                      {test.lab && (
                        <Badge variant="secondary" className="text-xs">
                          {test.lab}
                        </Badge>
                      )}
                    </div>

                    {/* Key results */}
                    <div className="flex flex-wrap gap-x-4 gap-y-1">
                      {test.results.slice(0, 4).map((result) => {
                        const status = getMarkerStatus(result.marker, result.value)

                        return (
                          <span key={result.marker} className="text-sm">
                            <span className="text-muted-foreground">
                              {t('markers.' + result.marker)}:
                            </span>{' '}
                            <span
                              className={
                                status === 'normal'
                                  ? 'text-foreground'
                                  : status === 'low'
                                    ? 'text-yellow-500'
                                    : 'text-red-500'
                              }
                            >
                              {result.value}
                            </span>
                          </span>
                        )
                      })}
                      {test.results.length > 4 && (
                        <span className="text-muted-foreground text-sm">
                          +{test.results.length - 4} {t('othersSuffix')}
                        </span>
                      )}
                    </div>

                    {test.notes && (
                      <p className="text-muted-foreground mt-2 line-clamp-1 text-sm">
                        {test.notes}
                      </p>
                    )}
                  </div>

                  <div className="ml-2 flex items-center gap-1">
                    <Link href={`/bloodtests/${test.id}/edit`}>
                      <Button variant="ghost" size="icon" className="text-muted-foreground h-8 w-8">
                        <Pencil className="h-4 w-4" />
                      </Button>
                    </Link>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="text-muted-foreground hover:text-destructive h-8 w-8"
                      onClick={() => test.id && handleDelete(test.id)}
                    >
                      <Trash2 className="h-4 w-4" />
                    </Button>
                    <Link href={`/bloodtests/${test.id}`}>
                      <Button variant="ghost" size="icon" className="h-8 w-8">
                        <ChevronRight className="h-4 w-4" />
                      </Button>
                    </Link>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </TabsContent>
      </Tabs>
    </div>
  )
}
