// src/routes/appointments/[id]/+page.svelte
<script lang="ts">
  import { page } from '$app/state'
  import { goto } from '$app/navigation'
  import { format, set as setDateFields } from 'date-fns'
  import { i18n, getDateLocale } from '$lib/i18n.svelte'
  import { getAppointment, deleteAppointment, getObjective } from '$lib/db'
  import { getModulePreferences } from '$lib/notifications'
  import { formatCurrency } from '$lib/utils'
  import type { Appointment, Objective } from '$lib/types'
  import ArrowLeft from '@lucide/svelte/icons/arrow-left'
  import Trash2 from '@lucide/svelte/icons/trash-2'
  import Pencil from '@lucide/svelte/icons/pencil'
  import Calendar from '@lucide/svelte/icons/calendar'
  import User from '@lucide/svelte/icons/user'
  import MapPin from '@lucide/svelte/icons/map-pin'
  import Bell from '@lucide/svelte/icons/bell'
  import Euro from '@lucide/svelte/icons/euro'
  import FileText from '@lucide/svelte/icons/file-text'
  import Target from '@lucide/svelte/icons/target'

  let appointment = $state<Appointment | null>(null)
  let objective = $state<Objective | null>(null)
  let loading = $state(true)
  const costTrackingEnabled = getModulePreferences().costTrackingEnabled

  async function loadData() {
    const id = parseInt(page.params.id!)
    if (isNaN(id)) {
      await goto('/appointments')
      return
    }

    const data = await getAppointment(id)
    if (!data) {
      await goto('/appointments')
      return
    }

    appointment = data
    objective = data.objectiveId ? ((await getObjective(data.objectiveId)) ?? null) : null
    loading = false
  }

  $effect(() => {
    void page.params.id
    loading = true
    loadData()
  })

  async function handleDelete() {
    if (!appointment?.id || !confirm(i18n.t('appointments.detail.deleteConfirm'))) return
    await deleteAppointment(appointment.id)
    await goto('/appointments')
  }

  let isPast = $derived.by(() => {
    if (!appointment) return false
    const aptDate = appointment.time
      ? setDateFields(new Date(appointment.date), {
          hours: Number(appointment.time.split(':')[0]),
          minutes: Number(appointment.time.split(':')[1]),
          seconds: 0,
          milliseconds: 0,
        })
      : setDateFields(new Date(appointment.date), {
          hours: 23,
          minutes: 59,
          seconds: 59,
          milliseconds: 999,
        })
    return aptDate < new Date()
  })
</script>

{#if loading}
  <p class="loading">{i18n.t('appointments.detail.loading')}</p>
{:else if appointment}
  <div class="header">
    <div class="header-left">
      <a href="/appointments" class="icon-link" aria-label={i18n.t('common.back')}
        ><ArrowLeft size={20} /></a
      >
      <div>
        <h1>
          {i18n.t('appointments.types.' + appointment.type)}
        </h1>
        {#if isPast}
          <span class="past-badge">{i18n.t('appointments.detail.pastBadge')}</span>
        {/if}
      </div>
    </div>
    <div class="header-actions">
      <a
        href={`/appointments/${appointment.id}/edit`}
        class="icon-link"
        aria-label={i18n.t('common.edit')}><Pencil size={18} /></a
      >
      <button
        type="button"
        class="icon-link danger"
        onclick={handleDelete}
        aria-label={i18n.t('common.delete')}
      >
        <Trash2 size={18} />
      </button>
    </div>
  </div>

  <div class="card">
    <p class="card-title"><Calendar size={14} /> {i18n.t('appointments.detail.dateAndTime')}</p>
    <p class="value">
      {format(new Date(appointment.date), 'EEEE d MMMM yyyy', {
        locale: getDateLocale(i18n.locale),
      })}
      {#if appointment.time}
        · {appointment.time}
      {/if}
    </p>
  </div>

  {#if appointment.doctor || appointment.location}
    <div class="card">
      <p class="card-title"><User size={14} /> {i18n.t('appointments.detail.information')}</p>
      {#if appointment.doctor}
        <div class="info-line">
          <span class="info-label">{i18n.t('appointments.detail.practitionerLabel')}</span>
          <span>{appointment.doctor}</span>
        </div>
      {/if}
      {#if appointment.location}
        <div class="info-line">
          <span class="info-label"
            ><MapPin size={12} /> {i18n.t('appointments.detail.locationLabel')}</span
          >
          <span>{appointment.location}</span>
        </div>
      {/if}
    </div>
  {/if}

  {#if appointment.reminderMinutes}
    <div class="card">
      <p class="card-title"><Bell size={14} /> {i18n.t('appointments.detail.reminderTitle')}</p>
      <p class="value">{i18n.t('appointments.reminderTimes.' + appointment.reminderMinutes)}</p>
    </div>
  {/if}

  {#if costTrackingEnabled && appointment.cost !== undefined && appointment.cost > 0}
    <div class="card">
      <p class="card-title"><Euro size={14} /> {i18n.t('appointments.detail.costTitle')}</p>
      <p class="value">{formatCurrency(appointment.cost, i18n.locale)}</p>
    </div>
  {/if}

  {#if objective}
    <div class="card">
      <p class="card-title"><Target size={14} /> {i18n.t('appointments.form.linkedObjective')}</p>
      <p class="value">{objective.title}</p>
    </div>
  {/if}

  {#if appointment.notes}
    <div class="card">
      <p class="card-title"><FileText size={14} /> {i18n.t('appointments.detail.notesTitle')}</p>
      <p class="notes">{appointment.notes}</p>
    </div>
  {/if}
{/if}

<style>
  .loading {
    color: var(--ink-soft);
    text-align: center;
    padding: 40px 0;
  }
  .header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    margin-bottom: 16px;
  }
  .header-left {
    display: flex;
    align-items: center;
    gap: 10px;
  }
  h1 {
    font-size: 19px;
    font-weight: 700;
    margin: 0;
  }
  .past-badge {
    display: inline-block;
    margin-top: 4px;
    font-size: 11px;
    padding: 2px 8px;
    border-radius: 999px;
    border: 1px solid var(--line);
    color: var(--ink-soft);
  }
  .header-actions {
    display: flex;
    align-items: center;
    gap: 4px;
  }
  .icon-link {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 36px;
    height: 36px;
    border-radius: 10px;
    color: var(--ink);
    text-decoration: none;
    border: none;
    background: transparent;
    cursor: pointer;
    flex-shrink: 0;
  }
  .icon-link.danger {
    color: var(--alert);
  }
  .card {
    background: var(--bg);
    border: 1px solid var(--line);
    border-radius: 16px;
    padding: 16px;
    margin-bottom: 14px;
  }
  .card-title {
    display: flex;
    align-items: center;
    gap: 6px;
    font-size: 13px;
    font-weight: 600;
    margin: 0 0 10px;
  }
  .value {
    font-size: 14px;
    margin: 0;
    text-transform: capitalize;
  }
  .info-line {
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-size: 13.5px;
    padding: 6px 0;
  }
  .info-line:not(:last-child) {
    border-bottom: 1px solid var(--line);
  }
  .info-label {
    display: flex;
    align-items: center;
    gap: 4px;
    color: var(--ink-soft);
  }
  .notes {
    font-size: 13.5px;
    white-space: pre-wrap;
    margin: 0;
    color: var(--ink-soft);
  }
</style>

// src/app/appointments/[id]/page.tsx
'use client'

import { useEffect, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { useLocale } from 'next-intl'
import { getDateLocale } from '@/i18n/date-locale'
import type { Locale } from '@/i18n/config'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import {
  ArrowLeft,
  Trash2,
  Pencil,
  Calendar,
  Clock,
  MapPin,
  User,
  Bell,
  FileText,
  Stethoscope,
  Brain,
  Heart,
  Scissors,
  Droplet,
  CalendarDays,
  Syringe,
  Mic,
  Zap,
  Coins,
} from 'lucide-react'
import Link from 'next/link'
import { useTranslations } from 'next-intl'
import { getAppointmentWithPractitioner, deleteAppointment } from '@/lib/db'
import { APPOINTMENT_TYPES } from '@/lib/constants'
import type { Appointment, AppointmentType, Practitioner } from '@/lib/types'
import { format } from 'date-fns'
import { isAppointmentPast } from '@/lib/utils'
import { getModulePreferences } from '@/lib/notifications'

// Icon mapping
const ICONS: Record<string, React.ElementType> = {
  Stethoscope,
  Brain,
  Heart,
  Scissors,
  User,
  Droplet,
  Calendar: CalendarDays,
  Syringe,
  Mic,
  Zap,
}

// Separate component to render the appointment icon
function AppointmentIcon({
  type,
  className,
  style,
}: {
  type: AppointmentType
  className?: string
  style?: React.CSSProperties
}) {
  const iconName = APPOINTMENT_TYPES[type]?.icon || 'Calendar'
  const IconComponent = ICONS[iconName] || CalendarDays
  return <IconComponent className={className} style={style} />
}

export default function AppointmentDetailPage() {
  const t = useTranslations('appointments')
  const locale = useLocale()
  const dateLocale = getDateLocale(locale as Locale)
  const params = useParams()
  const router = useRouter()
  const [appointment, setAppointment] = useState<Appointment | null>(null)
  const [practitioner, setPractitioner] = useState<Practitioner | null>(null)
  const [loading, setLoading] = useState(true)
  const [deleting, setDeleting] = useState(false)
  const [showCostTracking, setShowCostTracking] = useState(
    () => getModulePreferences().costTrackingEnabled
  )

  useEffect(() => {
    async function loadAppointment() {
      const id = parseInt(params.id as string)
      if (isNaN(id)) {
        router.push('/appointments')
        return
      }

      const result = await getAppointmentWithPractitioner(id)
      if (!result) {
        router.push('/appointments')
        return
      }

      setAppointment(result.appointment)
      setPractitioner(result.practitioner ?? null)
      setLoading(false)
    }
    loadAppointment()
  }, [params.id, router])

  async function handleDelete() {
    if (!appointment?.id || !confirm(t('detail.deleteConfirm'))) return

    setDeleting(true)
    try {
      await deleteAppointment(appointment.id)
      router.push('/appointments')
    } catch (error) {
      console.error('Error deleting appointment:', error)
      setDeleting(false)
    }
  }

  if (loading) {
    return (
      <div className="flex min-h-[50vh] items-center justify-center p-4">
        <p className="text-muted-foreground">{t('detail.loading')}</p>
      </div>
    )
  }

  if (!appointment) return null

  const typeInfo = APPOINTMENT_TYPES[appointment.type]
  const isPastAppointment = isAppointmentPast(appointment)

  return (
    <div className="space-y-6 p-4 pb-24">
      {/* Header */}
      <div className="flex items-center justify-between pt-2">
        <div className="flex items-center gap-3">
          <Link href="/appointments">
            <Button variant="ghost" size="icon">
              <ArrowLeft className="h-5 w-5" />
            </Button>
          </Link>
          <div>
            <h1 className="text-foreground text-xl font-bold">{t('types.' + appointment.type)}</h1>
            <p className="text-muted-foreground text-sm">
              {format(new Date(appointment.date), 'EEEE d MMMM yyyy', { locale: dateLocale })}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-1">
          <Link href={`/appointments/${appointment.id}/edit`}>
            <Button variant="ghost" size="icon">
              <Pencil className="h-5 w-5" />
            </Button>
          </Link>
          <Button
            variant="ghost"
            size="icon"
            onClick={handleDelete}
            disabled={deleting}
            className="text-destructive hover:text-destructive"
          >
            <Trash2 className="h-5 w-5" />
          </Button>
        </div>
      </div>

      {/* Status Badge */}
      {isPastAppointment && (
        <Badge variant="secondary" className="w-fit">
          {t('detail.pastBadge')}
        </Badge>
      )}

      {/* Type Card */}
      <Card>
        <CardContent className="p-4">
          <div className="flex items-center gap-4">
            <div className="rounded-xl p-3" style={{ backgroundColor: `${typeInfo?.color}20` }}>
              <AppointmentIcon
                type={appointment.type}
                className="h-8 w-8"
                style={{ color: typeInfo?.color }}
              />
            </div>
            <div>
              <p className="text-foreground text-lg font-medium">
                {t('types.' + appointment.type)}
              </p>
              <p className="text-muted-foreground capitalize">{appointment.type}</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Date & Time */}
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="flex items-center gap-2 text-base">
            <Calendar className="h-4 w-4" />
            {t('detail.dateAndTime')}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <div className="flex items-center gap-3">
            <CalendarDays className="text-muted-foreground h-5 w-5" />
            <div>
              <p className="font-medium">
                {format(new Date(appointment.date), 'EEEE d MMMM yyyy', { locale: dateLocale })}
              </p>
            </div>
          </div>
          {appointment.time && (
            <div className="flex items-center gap-3">
              <Clock className="text-muted-foreground h-5 w-5" />
              <p className="font-medium">{appointment.time}</p>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Doctor & Location - prioritize the linked practitioner */}
      {(() => {
        const displayName = practitioner?.name || appointment.doctor
        const displayLocation = practitioner?.location || appointment.location
        if (!displayName && !displayLocation) return null
        return (
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-base">{t('detail.information')}</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {displayName && (
                <div className="flex items-center gap-3">
                  <User className="text-muted-foreground h-5 w-5" />
                  <div>
                    <p className="text-muted-foreground text-xs">{t('detail.practitionerLabel')}</p>
                    <p className="font-medium">{displayName}</p>
                  </div>
                </div>
              )}
              {displayLocation && (
                <div className="flex items-center gap-3">
                  <MapPin className="text-muted-foreground h-5 w-5" />
                  <div>
                    <p className="text-muted-foreground text-xs">{t('detail.locationLabel')}</p>
                    <p className="font-medium">{displayLocation}</p>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>
        )
      })()}

      {/* Reminder */}
      {appointment.reminderMinutes && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="flex items-center gap-2 text-base">
              <Bell className="h-4 w-4" />
              {t('detail.reminderTitle')}
            </CardTitle>
          </CardHeader>
          <CardContent>
            <Badge variant="outline">{t('reminderTimes.' + appointment.reminderMinutes)}</Badge>
          </CardContent>
        </Card>
      )}

      {/* Cost */}
      {showCostTracking && appointment.cost !== undefined && appointment.cost > 0 && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="flex items-center gap-2 text-base">
              <Coins className="h-4 w-4" />
              {t('detail.costTitle')}
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-foreground text-xl font-bold">
              {appointment.cost.toLocaleString('fr-FR', {
                minimumFractionDigits: 2,
                maximumFractionDigits: 2,
              })}{' '}
              €
            </p>
          </CardContent>
        </Card>
      )}

      {/* Notes */}
      {appointment.notes && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="flex items-center gap-2 text-base">
              <FileText className="h-4 w-4" />
              {t('detail.notesTitle')}
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-foreground whitespace-pre-wrap">{appointment.notes}</p>
          </CardContent>
        </Card>
      )}
    </div>
  )
}
