// src/routes/journal/[id]/edit/+page.svelte
<script lang="ts">
  import { page } from '$app/state'
  import { goto } from '$app/navigation'
  import { set as setDateFields } from 'date-fns'
  import { i18n } from '$lib/i18n.svelte'
  import { getJournalEntry, updateJournalEntry } from '$lib/db'
  import type { MoodLevel } from '$lib/types'
  import JournalFormFields from '$lib/components/journal/JournalFormFields.svelte'
  import ArrowLeft from '@lucide/svelte/icons/arrow-left'

  let loading = $state(true)
  let saving = $state(false)
  let entryId = $state<number | null>(null)
  let originalDate = $state(new Date())

  let date = $state('')
  let content = $state('')
  let mood = $state<MoodLevel | undefined>(undefined)
  let energyLevel = $state<MoodLevel | undefined>(undefined)
  let sleepQuality = $state<MoodLevel | undefined>(undefined)
  let tags = $state<string[]>([])
  let isPrivate = $state(false)

  async function loadData() {
    const id = parseInt(page.params.id!)
    if (isNaN(id)) {
      await goto('/journal')
      return
    }

    const entry = await getJournalEntry(id)
    if (!entry) {
      await goto('/journal')
      return
    }

    entryId = id
    originalDate = new Date(entry.date)
    date = originalDate.toISOString().split('T')[0]!
    content = entry.content
    mood = entry.mood
    energyLevel = entry.energyLevel
    sleepQuality = entry.sleepQuality
    tags = entry.tags
    isPrivate = entry.isPrivate ?? false

    loading = false
  }

  $effect(() => {
    void page.params.id
    loading = true
    loadData()
  })

  function withTimeOfDay(dateStr: string, source: Date): Date {
    const [year, month, day] = dateStr.split('-').map(Number)
    return setDateFields(source, { year, month: (month ?? 1) - 1, date: day, seconds: 0 })
  }

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault()
    if (!entryId || !content.trim()) return

    saving = true
    try {
      await updateJournalEntry(entryId, {
        date: withTimeOfDay(date, originalDate),
        content: content.trim(),
        mood,
        tags: $state.snapshot(tags),
        energyLevel,
        sleepQuality,
        isPrivate,
      })
      await goto(`/journal/${entryId}`)
    } catch {
      saving = false
    }
  }
</script>

{#if loading}
  <p class="loading">{i18n.t('journal.title')}...</p>
{:else}
  <div class="header">
    <a href={`/journal/${entryId}`} class="icon-link" aria-label={i18n.t('common.back')}
      ><ArrowLeft size={20} /></a
    >
    <div>
      <h1>{i18n.t('journal.edit.title')}</h1>
      <p class="subtitle">{i18n.t('journal.edit.subtitle')}</p>
    </div>
  </div>

  <form onsubmit={handleSubmit}>
    <JournalFormFields
      bind:date
      bind:content
      bind:mood
      bind:energyLevel
      bind:sleepQuality
      bind:tags
      bind:isPrivate
      variant="edit"
      {saving}
      backHref={`/journal/${entryId}`}
    />
  </form>
{/if}

<style>
  .loading {
    color: var(--ink-soft);
    text-align: center;
    padding: 40px 0;
  }
  .header {
    display: flex;
    align-items: center;
    gap: 10px;
    margin-bottom: 18px;
  }
  h1 {
    font-size: 19px;
    font-weight: 700;
    margin: 0;
  }
  .subtitle {
    font-size: 12.5px;
    color: var(--ink-soft);
    margin: 2px 0 0;
  }
  .icon-link {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 36px;
    height: 36px;
    border-radius: 10px;
    color: var(--ink);
    text-decoration: none;
    flex-shrink: 0;
  }
</style>

// src/app/journal/[id]/edit/page.tsx
'use client'

import { useState, useEffect, use } from 'react'
import { useTranslations, useLocale } from 'next-intl'
import { getDateLocale } from '@/i18n/date-locale'
import type { Locale } from '@/i18n/config'
import { useRouter } from 'next/navigation'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { ArrowLeft } from 'lucide-react'
import Link from 'next/link'
import { getJournalEntry, updateJournalEntry } from '@/lib/db'
import type { JournalEntry, MoodLevel } from '@/lib/types'
import { JournalFormFields } from '@/components/journal/JournalFormFields'

export default function EditJournalEntryPage({ params }: { params: Promise<{ id: string }> }) {
  const t = useTranslations('journal')
  const tCommon = useTranslations('common')
  const locale = useLocale()
  const dateLocale = getDateLocale(locale as Locale)
  const resolvedParams = use(params)
  const router = useRouter()
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [entry, setEntry] = useState<JournalEntry | null>(null)

  // Form state
  const [content, setContent] = useState('')
  const [mood, setMood] = useState<MoodLevel | undefined>()
  const [tags, setTags] = useState<string[]>([])
  const [energyLevel, setEnergyLevel] = useState<MoodLevel | undefined>()
  const [sleepQuality, setSleepQuality] = useState<MoodLevel | undefined>()
  const [isPrivate, setIsPrivate] = useState(false)
  const [entryDate, setEntryDate] = useState<Date>(new Date())

  useEffect(() => {
    loadEntry()
  }, [resolvedParams.id])

  async function loadEntry() {
    setLoading(true)
    try {
      const data = await getJournalEntry(Number(resolvedParams.id))
      if (data) {
        setEntry(data)
        setContent(data.content)
        setMood(data.mood)
        setTags(data.tags)
        setEnergyLevel(data.energyLevel)
        setSleepQuality(data.sleepQuality)
        setIsPrivate(data.isPrivate || false)
        setEntryDate(new Date(data.date))
      }
    } finally {
      setLoading(false)
    }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()

    if (!content.trim() || !entry?.id) return

    setSaving(true)
    try {
      await updateJournalEntry(entry.id, {
        date: entryDate,
        content: content.trim(),
        mood,
        tags,
        energyLevel,
        sleepQuality,
        isPrivate,
      })
      router.push(`/journal/${entry.id}`)
    } catch (error) {
      console.error('Failed to update entry:', error)
      setSaving(false)
    }
  }

  if (loading) {
    return (
      <div className="space-y-6 p-4 pb-24">
        <div className="flex items-center gap-3 pt-2">
          <div className="bg-muted h-10 w-10 animate-pulse rounded" />
          <div className="flex-1 space-y-2">
            <div className="bg-muted h-6 w-48 animate-pulse rounded" />
            <div className="bg-muted h-4 w-32 animate-pulse rounded" />
          </div>
        </div>
        <Card>
          <CardContent className="p-4">
            <div className="bg-muted h-32 animate-pulse rounded" />
          </CardContent>
        </Card>
      </div>
    )
  }

  if (!entry) {
    return (
      <div className="space-y-6 p-4 pb-24">
        <div className="flex items-center gap-3 pt-2">
          <Link href="/journal">
            <Button variant="ghost" size="icon">
              <ArrowLeft className="h-5 w-5" />
            </Button>
          </Link>
          <h1 className="text-2xl font-bold">{t('detail.notFound')}</h1>
        </div>
        <Card>
          <CardContent className="p-8 text-center">
            <p className="text-muted-foreground">{t('detail.notFoundDesc')}</p>
            <Link href="/journal">
              <Button className="mt-4">{t('detail.backToJournal')}</Button>
            </Link>
          </CardContent>
        </Card>
      </div>
    )
  }

  return (
    <div className="space-y-6 p-4 pb-24">
      <div className="flex items-center gap-3 pt-2">
        <Link href={`/journal/${entry.id}`}>
          <Button variant="ghost" size="icon" className="shrink-0">
            <ArrowLeft className="h-5 w-5" />
          </Button>
        </Link>
        <div>
          <h1 className="text-foreground text-2xl font-bold">{t('edit.title')}</h1>
          <p className="text-muted-foreground text-sm">{t('edit.subtitle')}</p>
        </div>
      </div>

      <form onSubmit={handleSubmit} className="space-y-6">
        <JournalFormFields
          content={content}
          onContentChange={setContent}
          mood={mood}
          onMoodChange={setMood}
          tags={tags}
          onTagsChange={setTags}
          energyLevel={energyLevel}
          onEnergyLevelChange={setEnergyLevel}
          sleepQuality={sleepQuality}
          onSleepQualityChange={setSleepQuality}
          isPrivate={isPrivate}
          onIsPrivateChange={setIsPrivate}
          entryDate={entryDate}
          onEntryDateChange={setEntryDate}
          dateLocale={dateLocale}
          saving={saving}
          isValid={content.trim().length > 0}
          cancelHref={`/journal/${entry.id}`}
          labels={{
            dateLabel: t('new.dateLabel'),
            contentLabel: t('edit.content'),
            contentPlaceholder: t('edit.placeholder'),
            howFeeling: t('new.howFeeling'),
            generalMood: t('new.generalMood'),
            energyLevel: t('new.energyLevel'),
            sleepQuality: t('new.sleepQuality'),
            tags: t('new.tags'),
            addTags: t('new.addTags'),
            privateEntry: t('new.privateEntry'),
            excludeExport: t('new.excludeExport'),
            cancel: tCommon('cancel'),
            save: t('new.save'),
            saving: t('new.saving'),
          }}
        />
      </form>
    </div>
  )
}
