// src/routes/progress/[id]/+page.svelte
<script lang="ts">
  import { page } from '$app/state'
  import { goto } from '$app/navigation'
  import { format } from 'date-fns'
  import { i18n, getDateLocale } from '$lib/i18n.svelte'
  import { db } from '$lib/db'
  import type { PhysicalProgress, Measurements } from '$lib/types'
  import {
    MEASUREMENT_FIELD_KEY,
    MEASUREMENT_UNITS,
  } from '$lib/components/progress/progress-charts'
  import ArrowLeft from '@lucide/svelte/icons/arrow-left'
  import Trash2 from '@lucide/svelte/icons/trash-2'
  import CalendarIcon from '@lucide/svelte/icons/calendar'
  import Ruler from '@lucide/svelte/icons/ruler'
  import Camera from '@lucide/svelte/icons/camera'
  import ChevronLeft from '@lucide/svelte/icons/chevron-left'
  import ChevronRight from '@lucide/svelte/icons/chevron-right'
  import X from '@lucide/svelte/icons/x'

  let entry = $state<PhysicalProgress | null>(null)
  let loading = $state(true)
  let deleting = $state(false)
  let lightboxOpen = $state(false)
  let lightboxIndex = $state(0)
  let lightboxEl: HTMLDialogElement | undefined = $state()

  $effect(() => {
    if (!lightboxEl) return
    if (lightboxOpen) lightboxEl.showModal()
    else lightboxEl.close()
  })

  async function loadEntry() {
    const id = parseInt(page.params.id!)
    if (isNaN(id)) {
      await goto('/progress')
      return
    }
    const data = await db.physicalProgress.get(id)
    if (!data) {
      await goto('/progress')
      return
    }
    entry = data
    loading = false
  }

  $effect(() => {
    void page.params.id
    loading = true
    loadEntry()
  })

  async function handleDelete() {
    if (!entry?.id || !confirm(i18n.t('progress.detail.deleteConfirm'))) return
    deleting = true
    await db.physicalProgress.delete(entry.id)
    await goto('/progress')
  }

  function openLightbox(index: number) {
    lightboxIndex = index
    lightboxOpen = true
  }

  function navigateLightbox(direction: -1 | 1) {
    const count = entry?.photos?.length ?? 0
    if (count === 0) return
    lightboxIndex = (lightboxIndex + direction + count) % count
  }

  let measurementEntries = $derived(
    entry?.measurements
      ? (Object.entries(entry.measurements) as [keyof Measurements, number | undefined][]).filter(
          ([, value]) => value !== undefined
        )
      : []
  )
</script>

{#if loading}
  <p class="loading">{i18n.t('common.loading')}</p>
{:else if entry}
  <div class="header">
    <div class="header-left">
      <a href="/progress" class="icon-link" aria-label={i18n.t('common.back')}
        ><ArrowLeft size={20} /></a
      >
      <div>
        <h1>
          {format(new Date(entry.date), 'd MMMM yyyy', { locale: getDateLocale(i18n.locale) })}
        </h1>
        <p class="subtitle">
          <CalendarIcon size={12} />
          {format(new Date(entry.date), 'EEEE', { locale: getDateLocale(i18n.locale) })}
        </p>
      </div>
    </div>
    <button
      type="button"
      class="icon-link danger"
      onclick={handleDelete}
      disabled={deleting}
      aria-label={i18n.t('common.delete')}
    >
      <Trash2 size={20} />
    </button>
  </div>

  {#if entry.photos && entry.photos.length > 0}
    <div class="card">
      <p class="card-title">
        <Camera size={14} />
        {i18n.t('progress.detail.photos')} ({entry.photos.length})
      </p>
      <div class="photo-grid">
        {#each entry.photos as photo, index (index)}
          <button type="button" class="photo-btn" onclick={() => openLightbox(index)}>
            <img src={photo} alt="" />
          </button>
        {/each}
      </div>
    </div>
  {/if}

  {#if measurementEntries.length > 0}
    <div class="card">
      <p class="card-title"><Ruler size={14} /> {i18n.t('progress.detail.measurements')}</p>
      <div class="measurements-grid">
        {#each measurementEntries as [key, value] (key)}
          <div class="measurement-row">
            <span class="measurement-label">{i18n.t(MEASUREMENT_FIELD_KEY[key])}</span>
            <span class="measurement-value"
              >{value} <span class="unit">{MEASUREMENT_UNITS[key]}</span></span
            >
          </div>
        {/each}
      </div>
    </div>
  {/if}

  {#if entry.tags && entry.tags.length > 0}
    <div class="card">
      <p class="card-title">{i18n.t('progress.detail.tags')}</p>
      <div class="tag-row">
        {#each entry.tags as tag (tag)}
          <span class="tag-chip">{tag}</span>
        {/each}
      </div>
    </div>
  {/if}

  {#if entry.notes}
    <div class="card">
      <p class="card-title">{i18n.t('progress.detail.notes')}</p>
      <p class="notes">{entry.notes}</p>
    </div>
  {/if}

  <dialog
    bind:this={lightboxEl}
    class="lightbox"
    onclose={() => {
      lightboxOpen = false
    }}
  >
    <button
      type="button"
      class="lightbox-close"
      onclick={() => (lightboxOpen = false)}
      aria-label={i18n.t('common.close')}
    >
      <X size={22} />
    </button>
    {#if entry.photos && entry.photos.length > 1}
      <button
        type="button"
        class="lightbox-nav prev"
        onclick={() => navigateLightbox(-1)}
        aria-label="previous"
      >
        <ChevronLeft size={24} />
      </button>
      <button
        type="button"
        class="lightbox-nav next"
        onclick={() => navigateLightbox(1)}
        aria-label="next"
      >
        <ChevronRight size={24} />
      </button>
    {/if}
    {#if entry.photos}
      <img src={entry.photos[lightboxIndex]} alt="" class="lightbox-img" />
    {/if}
    {#if entry.photos && entry.photos.length > 1}
      <div class="lightbox-counter">{lightboxIndex + 1} / {entry.photos.length}</div>
    {/if}
  </dialog>
{/if}

<style>
  .loading {
    color: var(--ink-soft);
    text-align: center;
    padding: 40px 0;
  }
  .header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 16px;
  }
  .header-left {
    display: flex;
    align-items: center;
    gap: 10px;
  }
  h1 {
    font-size: 19px;
    font-weight: 700;
    margin: 0;
  }
  .subtitle {
    display: flex;
    align-items: center;
    gap: 4px;
    font-size: 12.5px;
    color: var(--ink-soft);
    margin: 2px 0 0;
    text-transform: capitalize;
  }
  .icon-link {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 36px;
    height: 36px;
    border-radius: 10px;
    color: var(--ink);
    text-decoration: none;
    border: none;
    background: transparent;
    cursor: pointer;
    flex-shrink: 0;
  }
  .icon-link.danger {
    color: var(--alert);
  }
  .card {
    background: var(--bg);
    border: 1px solid var(--line);
    border-radius: 16px;
    padding: 16px;
    margin-bottom: 14px;
  }
  .card-title {
    display: flex;
    align-items: center;
    gap: 6px;
    font-size: 13px;
    font-weight: 600;
    margin: 0 0 12px;
  }
  .photo-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 8px;
  }
  .photo-btn {
    aspect-ratio: 1;
    border-radius: 10px;
    overflow: hidden;
    background: var(--page);
    border: none;
    padding: 0;
    cursor: pointer;
  }
  .photo-btn img {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }
  .measurements-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 10px;
  }
  .measurement-row {
    display: flex;
    align-items: center;
    justify-content: space-between;
    background: var(--page);
    border-radius: 10px;
    padding: 10px 12px;
  }
  .measurement-label {
    font-size: 12.5px;
    color: var(--ink-soft);
  }
  .measurement-value {
    font-weight: 600;
  }
  .unit {
    color: var(--ink-soft);
    font-weight: 400;
  }
  .tag-row {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
  }
  .tag-chip {
    font-size: 12.5px;
    padding: 5px 12px;
    border-radius: 999px;
    background: var(--page);
    border: 1px solid var(--line);
  }
  .notes {
    white-space: pre-wrap;
    margin: 0;
    font-size: 13.5px;
  }
  dialog.lightbox {
    border: none;
    border-radius: 0;
    padding: 0;
    background: transparent;
    width: 100vw;
    height: 100vh;
    max-width: 100vw;
    max-height: 100vh;
    margin: 0;
    inset: 0;
  }
  dialog.lightbox[open] {
    display: flex;
    align-items: center;
    justify-content: center;
  }
  dialog.lightbox::backdrop {
    background: rgb(0 0 0 / 90%);
  }
  .lightbox-img {
    max-width: 92vw;
    max-height: 92vh;
    object-fit: contain;
  }
  .lightbox-close,
  .lightbox-nav {
    position: absolute;
    display: flex;
    align-items: center;
    justify-content: center;
    border: none;
    border-radius: 999px;
    background: rgb(0 0 0 / 50%);
    color: #fff;
    cursor: pointer;
    z-index: 1;
  }
  .lightbox-close {
    top: 16px;
    right: 16px;
    width: 40px;
    height: 40px;
  }
  .lightbox-nav {
    top: 50%;
    transform: translateY(-50%);
    width: 44px;
    height: 44px;
  }
  .lightbox-nav.prev {
    left: 16px;
  }
  .lightbox-nav.next {
    right: 16px;
  }
  .lightbox-counter {
    position: absolute;
    bottom: 16px;
    left: 50%;
    transform: translateX(-50%);
    background: rgb(0 0 0 / 50%);
    color: #fff;
    font-size: 12.5px;
    border-radius: 999px;
    padding: 4px 12px;
  }
</style>

// src/app/progress/[id]/page.tsx
'use client'

import { useEffect, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { useTranslations, useLocale } from 'next-intl'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Dialog, DialogContent } from '@/components/ui/dialog'
import {
  ArrowLeft,
  Trash2,
  Calendar,
  Ruler,
  Camera,
  ChevronLeft,
  ChevronRight,
  X,
} from 'lucide-react'
import Link from 'next/link'
import { db } from '@/lib/db'
import type { PhysicalProgress, Measurements } from '@/lib/types'
import { format } from 'date-fns'
import { fr } from 'date-fns/locale'
import { getDateLocale } from '@/i18n/date-locale'
import type { Locale } from '@/i18n/config'

const MEASUREMENT_UNITS: Record<keyof Measurements, string> = {
  weight: 'kg',
  height: 'cm',
  chest: 'cm',
  underbust: 'cm',
  waist: 'cm',
  hips: 'cm',
  shoulders: 'cm',
}

export default function ProgressDetailPage() {
  const t = useTranslations('progress')
  const tc = useTranslations('common')

  const MEASUREMENT_LABELS: Record<keyof Measurements, string> = {
    weight: t('new.weightField'),
    height: t('new.heightField'),
    chest: t('new.chestField'),
    underbust: t('new.underChestField'),
    waist: t('new.waistField'),
    hips: t('new.hipsField'),
    shoulders: t('new.shouldersField'),
  }
  const params = useParams()
  const router = useRouter()
  const [entry, setEntry] = useState<PhysicalProgress | null>(null)
  const [loading, setLoading] = useState(true)
  const [lightboxOpen, setLightboxOpen] = useState(false)
  const [lightboxIndex, setLightboxIndex] = useState(0)
  const [deleting, setDeleting] = useState(false)

  useEffect(() => {
    async function loadEntry() {
      const id = parseInt(params.id as string)
      if (isNaN(id)) {
        router.push('/progress')
        return
      }

      const data = await db.physicalProgress.get(id)
      if (!data) {
        router.push('/progress')
        return
      }

      setEntry(data)
      setLoading(false)
    }
    loadEntry()
  }, [params.id, router])

  async function handleDelete() {
    if (!entry?.id || !confirm(t('detail.deleteConfirm'))) return

    setDeleting(true)
    try {
      await db.physicalProgress.delete(entry.id)
      router.push('/progress')
    } catch (error) {
      console.error('Error deleting entry:', error)
      setDeleting(false)
    }
  }

  function openLightbox(index: number) {
    setLightboxIndex(index)
    setLightboxOpen(true)
  }

  function navigateLightbox(direction: 'prev' | 'next') {
    if (!entry?.photos) return

    if (direction === 'prev') {
      setLightboxIndex((prev) => (prev === 0 ? entry.photos!.length - 1 : prev - 1))
    } else {
      setLightboxIndex((prev) => (prev === entry.photos!.length - 1 ? 0 : prev + 1))
    }
  }

  if (loading) {
    return (
      <div className="flex min-h-[50vh] items-center justify-center p-4">
        <p className="text-muted-foreground">{tc('loading')}</p>
      </div>
    )
  }

  if (!entry) return null

  const measurementEntries = entry.measurements
    ? (Object.entries(entry.measurements) as [keyof Measurements, number | undefined][]).filter(
        (entry) => entry[1] !== undefined
      )
    : []

  return (
    <div className="space-y-6 p-4 pb-24">
      {/* Header */}
      <div className="flex items-center justify-between pt-2">
        <div className="flex items-center gap-3">
          <Link href="/progress">
            <Button variant="ghost" size="icon">
              <ArrowLeft className="h-5 w-5" />
            </Button>
          </Link>
          <div>
            <h1 className="text-foreground text-xl font-bold">
              {format(new Date(entry.date), 'd MMMM yyyy', { locale: fr })}
            </h1>
            <p className="text-muted-foreground flex items-center gap-1 text-sm">
              <Calendar className="h-3 w-3" />
              {format(new Date(entry.date), 'EEEE', { locale: fr })}
            </p>
          </div>
        </div>

        <Button
          variant="ghost"
          size="icon"
          onClick={handleDelete}
          disabled={deleting}
          className="text-destructive hover:text-destructive"
        >
          <Trash2 className="h-5 w-5" />
        </Button>
      </div>

      {/* Photos */}
      {entry.photos && entry.photos.length > 0 && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="flex items-center gap-2 text-base">
              <Camera className="h-4 w-4" />
              {t('detail.photos')} ({entry.photos.length})
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-2 gap-2">
              {entry.photos.map((photo, index) => (
                <button
                  key={index}
                  onClick={() => openLightbox(index)}
                  className="bg-muted focus:ring-primary aspect-square overflow-hidden rounded-lg focus:ring-2"
                >
                  <img
                    src={photo}
                    alt={`Photo ${index + 1}`}
                    className="h-full w-full object-cover transition-transform hover:scale-105"
                  />
                </button>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Measurements */}
      {measurementEntries.length > 0 && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="flex items-center gap-2 text-base">
              <Ruler className="h-4 w-4" />
              {t('detail.measurements')}
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-2 gap-3">
              {measurementEntries.map(([key, value]) => (
                <div
                  key={key}
                  className="bg-muted/30 flex items-center justify-between rounded-lg p-3"
                >
                  <span className="text-muted-foreground text-sm">{MEASUREMENT_LABELS[key]}</span>
                  <span className="font-medium">
                    {value} <span className="text-muted-foreground">{MEASUREMENT_UNITS[key]}</span>
                  </span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Tags */}
      {entry.tags && entry.tags.length > 0 && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-base">{t('detail.tags')}</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-2">
              {entry.tags.map((tag) => (
                <Badge key={tag} variant="secondary">
                  {tag}
                </Badge>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Notes */}
      {entry.notes && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-base">{t('detail.notes')}</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-foreground whitespace-pre-wrap">{entry.notes}</p>
          </CardContent>
        </Card>
      )}

      {/* Lightbox Dialog */}
      <Dialog open={lightboxOpen} onOpenChange={setLightboxOpen}>
        <DialogContent className="max-h-[95vh] max-w-[95vw] border-none bg-black p-0">
          <div className="relative flex h-full w-full items-center justify-center">
            {/* Close button */}
            <button
              onClick={() => setLightboxOpen(false)}
              className="absolute top-4 right-4 z-10 rounded-full bg-black/50 p-2 text-white hover:bg-black/70"
            >
              <X className="h-6 w-6" />
            </button>

            {/* Navigation */}
            {entry.photos && entry.photos.length > 1 && (
              <>
                <button
                  onClick={() => navigateLightbox('prev')}
                  className="absolute left-4 z-10 rounded-full bg-black/50 p-2 text-white hover:bg-black/70"
                >
                  <ChevronLeft className="h-6 w-6" />
                </button>
                <button
                  onClick={() => navigateLightbox('next')}
                  className="absolute right-4 z-10 rounded-full bg-black/50 p-2 text-white hover:bg-black/70"
                >
                  <ChevronRight className="h-6 w-6" />
                </button>
              </>
            )}

            {/* Image */}
            {entry.photos && (
              <img
                src={entry.photos[lightboxIndex]}
                alt={`Photo ${lightboxIndex + 1}`}
                className="max-h-[90vh] max-w-full object-contain"
              />
            )}

            {/* Counter */}
            {entry.photos && entry.photos.length > 1 && (
              <div className="absolute bottom-4 left-1/2 -translate-x-1/2 rounded-full bg-black/50 px-3 py-1 text-sm text-white">
                {lightboxIndex + 1} / {entry.photos.length}
              </div>
            )}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  )
}
