// src/components/medications/change-entry.tsx
'use client'

import { useTranslations, useLocale } from 'next-intl'
import { getDateLocale } from '@/i18n/date-locale'
import type { Locale } from '@/i18n/config'
import { format } from 'date-fns'
import { Badge } from '@/components/ui/badge'
import {
  Play,
  Pause,
  Square,
  RefreshCw,
  TrendingUp,
  Repeat,
  Clock,
  Pill,
  User,
  FileText,
} from 'lucide-react'
import type { TreatmentChange, TreatmentChangeType } from '@/lib/types'

// Configuration of change types (without labels - use the translations)
export const changeTypeConfig: Record<
  TreatmentChangeType,
  {
    icon: typeof Play
    color: string
    bgColor: string
  }
> = {
  started: {
    icon: Play,
    color: 'text-green-500',
    bgColor: 'bg-green-500/10',
  },
  stopped: {
    icon: Square,
    color: 'text-red-500',
    bgColor: 'bg-red-500/10',
  },
  paused: {
    icon: Pause,
    color: 'text-amber-500',
    bgColor: 'bg-amber-500/10',
  },
  resumed: {
    icon: RefreshCw,
    color: 'text-blue-500',
    bgColor: 'bg-blue-500/10',
  },
  dosage_change: {
    icon: TrendingUp,
    color: 'text-purple-500',
    bgColor: 'bg-purple-500/10',
  },
  method_change: {
    icon: Repeat,
    color: 'text-cyan-500',
    bgColor: 'bg-cyan-500/10',
  },
  frequency_change: {
    icon: Clock,
    color: 'text-orange-500',
    bgColor: 'bg-orange-500/10',
  },
}

interface ChangeEntryProps {
  change: TreatmentChange
  showMedicationName?: boolean
}

export function ChangeEntry({ change, showMedicationName = true }: ChangeEntryProps) {
  const t = useTranslations('objectives')
  const locale = useLocale()
  const dateLocale = getDateLocale(locale as Locale)
  const config = changeTypeConfig[change.changeType]
  const Icon = config.icon
  const label = t(`changeTypes.${change.changeType}`)

  return (
    <div className="bg-card flex gap-3 rounded-lg border p-3">
      {/* Icon */}
      <div className={`shrink-0 rounded-lg p-2 ${config.bgColor}`}>
        <Icon className={`h-4 w-4 ${config.color}`} />
      </div>

      {/* Content */}
      <div className="min-w-0 flex-1 space-y-1">
        <div className="flex items-start justify-between gap-2">
          <div>
            <Badge variant="outline" className={`${config.bgColor} border-0`}>
              <span className={config.color}>{label}</span>
            </Badge>
            {showMedicationName && (
              <div className="mt-1 flex items-center gap-1 text-sm font-medium">
                <Pill className="text-muted-foreground h-3 w-3" />
                {change.medicationName}
              </div>
            )}
          </div>
          <time className="text-muted-foreground text-xs whitespace-nowrap">
            {format(new Date(change.date), 'd MMM yyyy', { locale: dateLocale })}
          </time>
        </div>

        {/* Values change */}
        {(change.oldValue || change.newValue) && (
          <div className="text-sm">
            {change.oldValue && change.newValue ? (
              <span>
                <span className="text-muted-foreground line-through">{change.oldValue}</span>
                {' → '}
                <span className="text-foreground font-medium">{change.newValue}</span>
              </span>
            ) : change.newValue ? (
              <span className="font-medium">{change.newValue}</span>
            ) : null}
          </div>
        )}

        {/* Reason */}
        {change.reason && <p className="text-muted-foreground text-sm">{change.reason}</p>}

        {/* Prescriber */}
        {change.prescribedBy && (
          <div className="text-muted-foreground flex items-center gap-1 text-xs">
            <User className="h-3 w-3" />
            <span>
              {t('prescribedByPrefix')} {change.prescribedBy}
            </span>
          </div>
        )}

        {/* Notes */}
        {change.notes && (
          <div className="text-muted-foreground bg-muted/50 mt-2 flex items-start gap-1 rounded p-2 text-xs">
            <FileText className="mt-0.5 h-3 w-3 shrink-0" />
            <span>{change.notes}</span>
          </div>
        )}
      </div>
    </div>
  )
}

// Loading skeleton
export function ChangeEntrySkeleton() {
  return (
    <div className="bg-card flex animate-pulse gap-3 rounded-lg border p-3">
      <div className="bg-muted h-10 w-10 rounded-lg" />
      <div className="flex-1 space-y-2">
        <div className="bg-muted h-5 w-24 rounded" />
        <div className="bg-muted h-4 w-32 rounded" />
      </div>
    </div>
  )
}

// src/lib/components/medications/ChangeEntry.svelte
<script module lang="ts">
  import type { TreatmentChangeType } from '$lib/types'
  import Play from '@lucide/svelte/icons/play'
  import Square from '@lucide/svelte/icons/square'
  import Pause from '@lucide/svelte/icons/pause'
  import RefreshCw from '@lucide/svelte/icons/refresh-cw'
  import TrendingUp from '@lucide/svelte/icons/trending-up'
  import Repeat from '@lucide/svelte/icons/repeat'
  import Clock from '@lucide/svelte/icons/clock'

  export const changeTypeConfig: Record<TreatmentChangeType, { icon: typeof Play; color: string }> =
    {
      started: { icon: Play, color: 'var(--ok)' },
      stopped: { icon: Square, color: 'var(--alert)' },
      paused: { icon: Pause, color: 'var(--watch)' },
      resumed: { icon: RefreshCw, color: 'var(--blue-deep)' },
      dosage_change: { icon: TrendingUp, color: 'var(--pink-deep)' },
      method_change: { icon: Repeat, color: 'var(--blue)' },
      frequency_change: { icon: Clock, color: 'var(--gold)' },
    }
</script>

<script lang="ts">
  import { i18n, getDateLocale } from '$lib/i18n.svelte'
  import { format } from 'date-fns'
  import type { TreatmentChange } from '$lib/types'
  import Pill from '@lucide/svelte/icons/pill'
  import User from '@lucide/svelte/icons/user'
  import FileText from '@lucide/svelte/icons/file-text'

  let {
    change,
    showMedicationName = true,
  }: {
    change: TreatmentChange
    showMedicationName?: boolean
  } = $props()

  let config = $derived(changeTypeConfig[change.changeType])
</script>

<div class="entry">
  <div class="icon-wrap" style:background={`color-mix(in srgb, ${config.color} 16%, transparent)`}>
    <config.icon size={16} color={config.color} />
  </div>
  <div class="content">
    <div class="entry-head">
      <div>
        <span class="badge" style:color={config.color}>
          {i18n.t(`objectives.changeTypes.${change.changeType}`)}
        </span>
        {#if showMedicationName}
          <div class="med-name">
            <Pill size={12} />
            {change.medicationName}
          </div>
        {/if}
      </div>
      <time
        >{format(new Date(change.date), 'd MMM yyyy', { locale: getDateLocale(i18n.locale) })}</time
      >
    </div>

    {#if change.oldValue || change.newValue}
      <div class="values">
        {#if change.oldValue && change.newValue}
          <span class="old">{change.oldValue}</span> → <span class="new">{change.newValue}</span>
        {:else if change.newValue}
          <span class="new">{change.newValue}</span>
        {/if}
      </div>
    {/if}

    {#if change.reason}
      <p class="reason">{change.reason}</p>
    {/if}

    {#if change.prescribedBy}
      <div class="prescriber">
        <User size={12} />
        <span>{i18n.t('objectives.prescribedByPrefix')} {change.prescribedBy}</span>
      </div>
    {/if}

    {#if change.notes}
      <div class="notes">
        <FileText size={12} />
        <span>{change.notes}</span>
      </div>
    {/if}
  </div>
</div>

<style>
  .entry {
    display: flex;
    gap: 10px;
    background: var(--bg);
    border: 1px solid var(--line);
    border-radius: 14px;
    padding: 12px;
  }
  .icon-wrap {
    flex-shrink: 0;
    width: 34px;
    height: 34px;
    border-radius: 10px;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  .content {
    flex: 1;
    min-width: 0;
  }
  .entry-head {
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    gap: 8px;
  }
  .badge {
    display: inline-block;
    font-size: 11.5px;
    font-weight: 600;
  }
  .med-name {
    display: flex;
    align-items: center;
    gap: 4px;
    font-size: 13px;
    font-weight: 600;
    color: var(--ink-soft);
    margin-top: 3px;
  }
  time {
    font-size: 11px;
    color: var(--ink-faint);
    white-space: nowrap;
  }
  .values {
    font-size: 13.5px;
    margin-top: 6px;
  }
  .old {
    color: var(--ink-faint);
    text-decoration: line-through;
  }
  .new {
    font-weight: 600;
  }
  .reason {
    font-size: 13px;
    color: var(--ink-soft);
    margin: 6px 0 0;
  }
  .prescriber {
    display: flex;
    align-items: center;
    gap: 4px;
    font-size: 11.5px;
    color: var(--ink-faint);
    margin-top: 6px;
  }
  .notes {
    display: flex;
    align-items: flex-start;
    gap: 5px;
    font-size: 11.5px;
    color: var(--ink-soft);
    background: var(--page);
    border-radius: 8px;
    padding: 7px 8px;
    margin-top: 8px;
  }
</style>
