// src/components/medications/MedicationFormFields.tsx
'use client'

import { useTranslations } from 'next-intl'
import Link from 'next/link'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Switch } from '@/components/ui/switch'
import { Clock, Plus, Trash2 } from 'lucide-react'
import {
  MEDICATION_TYPES,
  ADMINISTRATION_METHODS,
  DOSAGE_UNITS,
  STOCK_UNITS,
  PILL_ROUTES,
  INJECTION_ROUTES,
  getFrequenciesForMethod,
} from '@/lib/constants'
import type {
  MedicationType,
  AdministrationMethod,
  SchedulingMode,
  PillAdministrationRoute,
  InjectionAdministrationRoute,
} from '@/lib/types'

interface Props {
  name: string
  onNameChange: (v: string) => void
  type: MedicationType
  onTypeChange: (v: MedicationType) => void
  dosage: string
  onDosageChange: (v: string) => void
  unit: string
  onUnitChange: (v: string) => void
  method: AdministrationMethod
  onMethodChange: (v: AdministrationMethod) => void
  frequency: string
  onFrequencyChange: (v: string) => void
  startDate: string
  onStartDateChange: (v: string) => void
  pillRoute: PillAdministrationRoute | undefined
  onPillRouteChange: (v: PillAdministrationRoute | undefined) => void
  injectionRoute: InjectionAdministrationRoute | undefined
  onInjectionRouteChange: (v: InjectionAdministrationRoute | undefined) => void
  schedulingMode: SchedulingMode
  onSchedulingModeChange: (v: SchedulingMode) => void
  scheduledTimes: string[]
  onScheduledTimesChange: (v: string[]) => void
  stock: string
  onStockChange: (v: string) => void
  stockUnit: string
  onStockUnitChange: (v: string) => void
  stockAlert: string
  onStockAlertChange: (v: string) => void
  saving: boolean
  backHref: string
  cancelLabel: string
  saveLabel: string
  savingLabel: string
  // edit-only optional
  endDate?: string
  onEndDateChange?: (v: string) => void
  isActive?: boolean
  onIsActiveChange?: (v: boolean) => void
  notes?: string
  onNotesChange?: (v: string) => void
}

export function MedicationFormFields({
  name,
  onNameChange,
  type,
  onTypeChange,
  dosage,
  onDosageChange,
  unit,
  onUnitChange,
  method,
  onMethodChange,
  frequency,
  onFrequencyChange,
  startDate,
  onStartDateChange,
  pillRoute,
  onPillRouteChange,
  injectionRoute,
  onInjectionRouteChange,
  schedulingMode,
  onSchedulingModeChange,
  scheduledTimes,
  onScheduledTimesChange,
  stock,
  onStockChange,
  stockUnit,
  onStockUnitChange,
  stockAlert,
  onStockAlertChange,
  saving,
  backHref,
  cancelLabel,
  saveLabel,
  savingLabel,
  endDate,
  onEndDateChange,
  isActive,
  onIsActiveChange,
  notes,
  onNotesChange,
}: Props) {
  const t = useTranslations('medications')

  function handleMethodChange(newMethod: AdministrationMethod) {
    onMethodChange(newMethod)
    const valid = getFrequenciesForMethod(newMethod)
    if (!valid.includes(frequency)) onFrequencyChange(valid[0]!)
  }

  function handleAddTime() {
    onScheduledTimesChange([...scheduledTimes, '12:00'])
  }

  function handleRemoveTime(index: number) {
    if (scheduledTimes.length > 1) {
      onScheduledTimesChange(scheduledTimes.filter((_, i) => i !== index))
    }
  }

  function handleTimeChange(index: number, value: string) {
    const next = [...scheduledTimes]
    next[index] = value
    onScheduledTimesChange(next)
  }

  return (
    <>
      {/* General Info */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">{t('new.generalInfo')}</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="name">{t('form.medicationName')}</Label>
            <Input
              id="name"
              value={name}
              onChange={(e) => onNameChange(e.target.value)}
              placeholder={t('new.namePlaceholder')}
              required
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="type">{t('form.type')}</Label>
            <Select value={type} onValueChange={(v) => onTypeChange(v as MedicationType)}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {Object.keys(MEDICATION_TYPES).map((key) => (
                  <SelectItem key={key} value={key}>
                    {t(`types.${key}`)}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="dosage">{t('form.dosage')}</Label>
              <Input
                id="dosage"
                type="number"
                step="0.1"
                value={dosage}
                onChange={(e) => onDosageChange(e.target.value)}
                placeholder="2"
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="unit">{t('form.unit')}</Label>
              <Select value={unit} onValueChange={onUnitChange}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {DOSAGE_UNITS.map((u) => (
                    <SelectItem key={u} value={u}>
                      {u}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="method">{t('form.method')}</Label>
            <Select
              value={method}
              onValueChange={(v) => handleMethodChange(v as AdministrationMethod)}
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {Object.keys(ADMINISTRATION_METHODS).map((key) => (
                  <SelectItem key={key} value={key}>
                    {t(`methods.${key}`)}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {method === 'pill' && (
            <div className="space-y-2">
              <Label htmlFor="pillRoute">{t('form.pillRoute')}</Label>
              <Select
                value={pillRoute || ''}
                onValueChange={(v) =>
                  onPillRouteChange((v as PillAdministrationRoute) || undefined)
                }
              >
                <SelectTrigger>
                  <SelectValue placeholder={t('form.selectPlaceholder')} />
                </SelectTrigger>
                <SelectContent>
                  {Object.keys(PILL_ROUTES).map((key) => (
                    <SelectItem key={key} value={key}>
                      {t(`pillRoutes.${key}`)}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          )}

          {method === 'injection' && (
            <div className="space-y-2">
              <Label htmlFor="injectionRoute">{t('form.injectionRoute')}</Label>
              <Select
                value={injectionRoute || ''}
                onValueChange={(v) =>
                  onInjectionRouteChange((v as InjectionAdministrationRoute) || undefined)
                }
              >
                <SelectTrigger>
                  <SelectValue placeholder={t('form.selectPlaceholder')} />
                </SelectTrigger>
                <SelectContent>
                  {Object.keys(INJECTION_ROUTES).map((key) => (
                    <SelectItem key={key} value={key}>
                      {t(`injectionRoutes.${key}`)}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          )}

          <div className="space-y-2">
            <Label htmlFor="frequency">{t('form.frequency')}</Label>
            <Select value={frequency} onValueChange={onFrequencyChange}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {getFrequenciesForMethod(method).map((f) => (
                  <SelectItem key={f} value={f}>
                    {t('frequencies.' + f)}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {endDate !== undefined ? (
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="startDate">{t('form.startDate')}</Label>
                <Input
                  id="startDate"
                  type="date"
                  value={startDate}
                  onChange={(e) => onStartDateChange(e.target.value)}
                  required
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="endDate">{t('form.endDate')}</Label>
                <Input
                  id="endDate"
                  type="date"
                  value={endDate}
                  onChange={(e) => onEndDateChange?.(e.target.value)}
                />
              </div>
            </div>
          ) : (
            <div className="space-y-2">
              <Label htmlFor="startDate">{t('form.startDate')}</Label>
              <Input
                id="startDate"
                type="date"
                value={startDate}
                onChange={(e) => onStartDateChange(e.target.value)}
                required
              />
            </div>
          )}

          {isActive !== undefined && onIsActiveChange && (
            <div className="flex items-center justify-between pt-2">
              <div>
                <p className="text-foreground font-medium">Médicament actif</p>
                <p className="text-muted-foreground text-sm">
                  Afficher dans la liste des médicaments à prendre
                </p>
              </div>
              <Switch checked={isActive} onCheckedChange={onIsActiveChange} />
            </div>
          )}
        </CardContent>
      </Card>

      {/* Scheduling */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-base">
            <Clock className="text-primary h-4 w-4" />
            {t('new.schedulingTitle')}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-foreground font-medium">{t('new.advancedMode')}</p>
              <p className="text-muted-foreground text-sm">{t('new.advancedModeDescription')}</p>
            </div>
            <Switch
              checked={schedulingMode === 'advanced'}
              onCheckedChange={(checked) => onSchedulingModeChange(checked ? 'advanced' : 'simple')}
            />
          </div>

          {schedulingMode === 'advanced' && (
            <div className="border-border space-y-3 border-t pt-2">
              <p className="text-muted-foreground text-sm">{t('new.advancedModeHint')}</p>
              {scheduledTimes.map((time, index) => (
                <div key={index} className="flex items-center gap-2">
                  <Input
                    type="time"
                    value={time}
                    onChange={(e) => handleTimeChange(index, e.target.value)}
                    className="flex-1"
                  />
                  {scheduledTimes.length > 1 && (
                    <Button
                      type="button"
                      variant="ghost"
                      size="icon"
                      onClick={() => handleRemoveTime(index)}
                      className="text-destructive"
                    >
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  )}
                </div>
              ))}
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={handleAddTime}
                className="w-full gap-2"
              >
                <Plus className="h-4 w-4" />
                {t('new.addTime')}
              </Button>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Stock */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">{t('new.stockTitle')}</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="stock">{t('form.stock')}</Label>
              <Input
                id="stock"
                type="number"
                step="0.1"
                value={stock}
                onChange={(e) => onStockChange(e.target.value)}
                placeholder="30"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="stockUnit">{t('form.stockUnit')}</Label>
              <Select value={stockUnit} onValueChange={onStockUnitChange}>
                <SelectTrigger>
                  <SelectValue placeholder={t('form.selectPlaceholder')} />
                </SelectTrigger>
                <SelectContent>
                  {STOCK_UNITS.map((u) => (
                    <SelectItem key={u} value={u}>
                      {t(`stockUnits.${u}`)}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
          <div className="space-y-2">
            <Label htmlFor="stockAlert">{t('form.lowStockAlert')}</Label>
            <Input
              id="stockAlert"
              type="number"
              step="0.1"
              value={stockAlert}
              onChange={(e) => onStockAlertChange(e.target.value)}
              placeholder="7"
            />
          </div>
        </CardContent>
      </Card>

      {/* Notes (edit-only) */}
      {notes !== undefined && onNotesChange && (
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Notes (optionnel)</CardTitle>
          </CardHeader>
          <CardContent>
            <Textarea
              value={notes}
              onChange={(e) => onNotesChange(e.target.value)}
              placeholder="Notes personnelles, effets secondaires observés, etc."
              rows={3}
            />
          </CardContent>
        </Card>
      )}

      {/* Submit */}
      <div className="flex gap-3">
        <Link href={backHref} className="flex-1">
          <Button variant="outline" className="w-full" type="button">
            {cancelLabel}
          </Button>
        </Link>
        <Button type="submit" className="flex-1" disabled={saving}>
          {saving ? savingLabel : saveLabel}
        </Button>
      </div>
    </>
  )
}

// src/lib/components/medications/MedicationFormFields.svelte
<script lang="ts">
  import { i18n } from '$lib/i18n.svelte'
  import {
    MEDICATION_TYPES,
    ADMINISTRATION_METHODS,
    DOSAGE_UNITS,
    STOCK_UNITS,
    PILL_ROUTES,
    INJECTION_ROUTES,
    getFrequenciesForMethod,
  } from '$lib/constants'
  import type {
    MedicationType,
    AdministrationMethod,
    SchedulingMode,
    PillAdministrationRoute,
    InjectionAdministrationRoute,
  } from '$lib/types'
  import Clock from '@lucide/svelte/icons/clock'
  import Plus from '@lucide/svelte/icons/plus'
  import Trash2 from '@lucide/svelte/icons/trash-2'

  let {
    name = $bindable(),
    type = $bindable(),
    dosage = $bindable(),
    unit = $bindable(),
    method = $bindable(),
    frequency = $bindable(),
    startDate = $bindable(),
    pillRoute = $bindable(),
    injectionRoute = $bindable(),
    schedulingMode = $bindable(),
    scheduledTimes = $bindable(),
    stock = $bindable(),
    stockUnit = $bindable(),
    stockAlert = $bindable(),
    saving,
    backHref,
    endDate = $bindable(undefined),
    isActive = $bindable(undefined),
    notes = $bindable(undefined),
  }: {
    name: string
    type: MedicationType
    dosage: string
    unit: string
    method: AdministrationMethod
    frequency: string
    startDate: string
    pillRoute: PillAdministrationRoute | undefined
    injectionRoute: InjectionAdministrationRoute | undefined
    schedulingMode: SchedulingMode
    scheduledTimes: string[]
    stock: string
    stockUnit: string
    stockAlert: string
    saving: boolean
    backHref: string
    endDate?: string
    isActive?: boolean
    notes?: string
  } = $props()

  function handleMethodChange(e: Event & { currentTarget: HTMLSelectElement }) {
    const newMethod = e.currentTarget.value as AdministrationMethod
    method = newMethod
    const valid = getFrequenciesForMethod(newMethod)
    if (!valid.includes(frequency)) frequency = valid[0]!
  }

  function handleAddTime() {
    scheduledTimes = [...scheduledTimes, '12:00']
  }

  function handleRemoveTime(index: number) {
    if (scheduledTimes.length > 1) {
      scheduledTimes = scheduledTimes.filter((_, i) => i !== index)
    }
  }
</script>

<div class="card">
  <p class="card-title">{i18n.t('medications.new.generalInfo')}</p>

  <div class="field">
    <label for="name">{i18n.t('medications.form.medicationName')}</label>
    <input
      id="name"
      bind:value={name}
      placeholder={i18n.t('medications.new.namePlaceholder')}
      required
    />
  </div>

  <div class="field">
    <label for="type">{i18n.t('medications.form.type')}</label>
    <select id="type" bind:value={type}>
      {#each Object.keys(MEDICATION_TYPES) as key (key)}
        <option value={key}>{i18n.t(`medications.types.${key}`)}</option>
      {/each}
    </select>
  </div>

  <div class="field-row">
    <div class="field">
      <label for="dosage">{i18n.t('medications.form.dosage')}</label>
      <input id="dosage" type="number" step="0.1" bind:value={dosage} placeholder="2" required />
    </div>
    <div class="field">
      <label for="unit">{i18n.t('medications.form.unit')}</label>
      <select id="unit" bind:value={unit}>
        {#each DOSAGE_UNITS as u (u)}
          <option value={u}>{u}</option>
        {/each}
      </select>
    </div>
  </div>

  <div class="field">
    <label for="method">{i18n.t('medications.form.method')}</label>
    <select id="method" value={method} onchange={handleMethodChange}>
      {#each Object.keys(ADMINISTRATION_METHODS) as key (key)}
        <option value={key}>{i18n.t(`medications.methods.${key}`)}</option>
      {/each}
    </select>
  </div>

  {#if method === 'pill'}
    <div class="field">
      <label for="pillRoute">{i18n.t('medications.form.pillRoute')}</label>
      <select
        id="pillRoute"
        value={pillRoute ?? ''}
        onchange={(e) =>
          (pillRoute = (e.currentTarget.value as PillAdministrationRoute) || undefined)}
      >
        <option value="">{i18n.t('medications.form.selectPlaceholder')}</option>
        {#each Object.keys(PILL_ROUTES) as key (key)}
          <option value={key}>{i18n.t(`medications.pillRoutes.${key}`)}</option>
        {/each}
      </select>
    </div>
  {/if}

  {#if method === 'injection'}
    <div class="field">
      <label for="injectionRoute">{i18n.t('medications.form.injectionRoute')}</label>
      <select
        id="injectionRoute"
        value={injectionRoute ?? ''}
        onchange={(e) =>
          (injectionRoute = (e.currentTarget.value as InjectionAdministrationRoute) || undefined)}
      >
        <option value="">{i18n.t('medications.form.selectPlaceholder')}</option>
        {#each Object.keys(INJECTION_ROUTES) as key (key)}
          <option value={key}>{i18n.t(`medications.injectionRoutes.${key}`)}</option>
        {/each}
      </select>
    </div>
  {/if}

  <div class="field">
    <label for="frequency">{i18n.t('medications.form.frequency')}</label>
    <select id="frequency" bind:value={frequency}>
      {#each getFrequenciesForMethod(method) as f (f)}
        <option value={f}>{i18n.t(`medications.frequencies.${f}`)}</option>
      {/each}
    </select>
  </div>

  {#if endDate !== undefined}
    <div class="field-row">
      <div class="field">
        <label for="startDate">{i18n.t('medications.form.startDate')}</label>
        <input id="startDate" type="date" bind:value={startDate} required />
      </div>
      <div class="field">
        <label for="endDate">{i18n.t('medications.form.endDate')}</label>
        <input id="endDate" type="date" bind:value={endDate} />
      </div>
    </div>
  {:else}
    <div class="field">
      <label for="startDate">{i18n.t('medications.form.startDate')}</label>
      <input id="startDate" type="date" bind:value={startDate} required />
    </div>
  {/if}

  {#if isActive !== undefined}
    <div class="switch-row">
      <div>
        <p class="switch-label">{i18n.t('medications.form.activeLabel')}</p>
        <p class="switch-desc">{i18n.t('medications.form.activeDescription')}</p>
      </div>
      <label class="switch">
        <input type="checkbox" bind:checked={isActive} />
        <span class="track"></span>
        <span class="thumb"></span>
      </label>
    </div>
  {/if}
</div>

<div class="card">
  <p class="card-title"><Clock size={14} /> {i18n.t('medications.new.schedulingTitle')}</p>

  <div class="switch-row">
    <div>
      <p class="switch-label">{i18n.t('medications.new.advancedMode')}</p>
      <p class="switch-desc">{i18n.t('medications.new.advancedModeDescription')}</p>
    </div>
    <label class="switch">
      <input
        type="checkbox"
        checked={schedulingMode === 'advanced'}
        onchange={(e) => (schedulingMode = e.currentTarget.checked ? 'advanced' : 'simple')}
      />
      <span class="track"></span>
      <span class="thumb"></span>
    </label>
  </div>

  {#if schedulingMode === 'advanced'}
    <div class="times">
      <p class="times-hint">{i18n.t('medications.new.advancedModeHint')}</p>
      {#each scheduledTimes as time, index (index)}
        <div class="time-row">
          <input
            type="time"
            value={time}
            onchange={(e) => {
              const next = [...scheduledTimes]
              next[index] = e.currentTarget.value
              scheduledTimes = next
            }}
          />
          {#if scheduledTimes.length > 1}
            <button type="button" class="icon-btn" onclick={() => handleRemoveTime(index)}>
              <Trash2 size={16} />
            </button>
          {/if}
        </div>
      {/each}
      <button type="button" class="btn btn-outline btn-block" onclick={handleAddTime}>
        <Plus size={16} />
        {i18n.t('medications.new.addTime')}
      </button>
    </div>
  {/if}
</div>

<div class="card">
  <p class="card-title">{i18n.t('medications.new.stockTitle')}</p>

  <div class="field-row">
    <div class="field">
      <label for="stock">{i18n.t('medications.form.stock')}</label>
      <input id="stock" type="number" step="0.1" bind:value={stock} placeholder="30" />
    </div>
    <div class="field">
      <label for="stockUnit">{i18n.t('medications.form.stockUnit')}</label>
      <select id="stockUnit" bind:value={stockUnit}>
        <option value="">{i18n.t('medications.form.selectPlaceholder')}</option>
        {#each STOCK_UNITS as u (u)}
          <option value={u}>{i18n.t(`medications.stockUnits.${u}`)}</option>
        {/each}
      </select>
    </div>
  </div>

  <div class="field">
    <label for="stockAlert">{i18n.t('medications.form.lowStockAlert')}</label>
    <input id="stockAlert" type="number" step="0.1" bind:value={stockAlert} placeholder="7" />
  </div>
</div>

{#if notes !== undefined}
  <div class="card">
    <p class="card-title">{i18n.t('medications.form.notesTitle')}</p>
    <textarea bind:value={notes} placeholder={i18n.t('medications.form.notesPlaceholder')} rows="3"
    ></textarea>
  </div>
{/if}

<div class="actions">
  <a href={backHref} class="btn btn-outline btn-block">{i18n.t('common.cancel')}</a>
  <button type="submit" class="btn btn-primary btn-block" disabled={saving}>
    {saving ? i18n.t('common.saving') : i18n.t('common.save')}
  </button>
</div>

<style>
  .card {
    background: var(--bg);
    border: 1px solid var(--line);
    border-radius: 16px;
    padding: 16px;
    margin-bottom: 16px;
  }
  .card-title {
    display: flex;
    align-items: center;
    gap: 6px;
    font-size: 13px;
    font-weight: 600;
    margin: 0 0 14px;
  }
  .field {
    margin-bottom: 14px;
  }
  .field:last-child {
    margin-bottom: 0;
  }
  .field-row {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 12px;
    margin-bottom: 14px;
  }
  .field-row:last-child {
    margin-bottom: 0;
  }
  label {
    display: block;
    font-size: 12.5px;
    color: var(--ink-soft);
    margin-bottom: 6px;
  }
  input,
  select,
  textarea {
    width: 100%;
    padding: 10px 12px;
    border: 1px solid var(--line);
    border-radius: 10px;
    background: var(--page);
    color: var(--ink);
    font-family: inherit;
    font-size: 14px;
  }
  textarea {
    resize: vertical;
  }
  .switch-row {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 12px;
    padding: 4px 0;
  }
  .switch-label {
    font-size: 14px;
    font-weight: 600;
    margin: 0;
  }
  .switch-desc {
    font-size: 12px;
    color: var(--ink-soft);
    margin: 2px 0 0;
  }
  .switch {
    position: relative;
    width: 44px;
    height: 26px;
    flex-shrink: 0;
  }
  .switch input {
    opacity: 0;
    width: 100%;
    height: 100%;
    position: absolute;
    margin: 0;
    cursor: pointer;
    z-index: 1;
  }
  .switch .track {
    position: absolute;
    inset: 0;
    background: var(--line);
    border-radius: 999px;
    transition: background 0.2s ease;
  }
  .switch input:checked + .track {
    background: linear-gradient(135deg, var(--blue-deep), var(--pink-deep));
  }
  .switch .thumb {
    position: absolute;
    top: 3px;
    left: 3px;
    width: 20px;
    height: 20px;
    background: #fff;
    border-radius: 50%;
    transition: transform 0.2s ease;
    box-shadow: 0 1px 3px var(--shadow);
  }
  .switch input:checked ~ .thumb {
    transform: translateX(18px);
  }
  .times {
    border-top: 1px solid var(--line);
    margin-top: 12px;
    padding-top: 12px;
  }
  .times-hint {
    font-size: 12.5px;
    color: var(--ink-soft);
    margin: 0 0 10px;
  }
  .time-row {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-bottom: 8px;
  }
  .time-row input {
    flex: 1;
  }
  .icon-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 38px;
    height: 38px;
    flex-shrink: 0;
    border: 1px solid var(--line);
    background: var(--page);
    color: var(--alert);
    border-radius: 10px;
    cursor: pointer;
  }
  .btn {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 6px;
    padding: 12px 18px;
    border-radius: 12px;
    border: 1px solid var(--line);
    background: var(--bg);
    color: var(--ink);
    font-family: inherit;
    font-size: 14px;
    font-weight: 600;
    cursor: pointer;
    text-decoration: none;
  }
  .btn:disabled {
    opacity: 0.5;
    cursor: default;
  }
  .btn-block {
    width: 100%;
  }
  .btn-outline {
    background: transparent;
  }
  .btn-primary {
    background: linear-gradient(135deg, var(--blue-deep), var(--pink-deep));
    color: #fff;
    border: none;
  }
  .actions {
    display: flex;
    gap: 12px;
  }
  .actions .btn {
    flex: 1;
  }
</style>
