// src/components/medications/treatment-gantt-chart.tsx
'use client'

import { useMemo, useRef, useState } from 'react'
import { useTranslations, useLocale } from 'next-intl'
import { getDateLocale } from '@/i18n/date-locale'
import type { Locale } from '@/i18n/config'
import { MEDICATION_TYPES } from '@/lib/constants'
import type { Medication } from '@/lib/types'
import { format, differenceInDays, startOfMonth, endOfMonth, eachMonthOfInterval } from 'date-fns'

interface TreatmentGanttChartProps {
  medications: Medication[]
}

export function TreatmentGanttChart({ medications }: TreatmentGanttChartProps) {
  const t = useTranslations('medications')
  const locale = useLocale()
  const dateLocale = getDateLocale(locale as Locale)
  const scrollRef = useRef<HTMLDivElement>(null)
  const [currentTime] = useState(() => Date.now())

  const { timelineStart, months, totalDays } = useMemo(() => {
    if (medications.length === 0) {
      const now = new Date()
      return {
        timelineStart: startOfMonth(now),
        timelineEnd: endOfMonth(now),
        months: [startOfMonth(now)],
        totalDays: 30,
      }
    }

    const starts = medications.map((m) => new Date(m.startDate))
    const ends = medications.map((m) => (m.endDate ? new Date(m.endDate) : new Date()))

    const earliest = startOfMonth(new Date(Math.min(...starts.map((d) => d.getTime()))))
    const latest = endOfMonth(new Date(Math.max(...ends.map((d) => d.getTime()), currentTime)))

    return {
      timelineStart: earliest,
      months: eachMonthOfInterval({ start: earliest, end: latest }),
      totalDays: Math.max(differenceInDays(latest, earliest), 1),
    }
  }, [medications, currentTime])

  if (medications.length === 0) {
    return (
      <p className="text-muted-foreground py-4 text-center text-sm">{t('history.noTreatments')}</p>
    )
  }

  const dayWidth = 3 // px per day
  const chartWidth = Math.max(totalDays * dayWidth, 300)
  const barHeight = 28
  const barGap = 8
  const labelWidth = 180

  function getBarLeft(date: Date): number {
    const days = differenceInDays(date, timelineStart)
    return Math.max(days * dayWidth, 0)
  }

  function getBarWidth(start: Date, end: Date): number {
    const days = differenceInDays(end, start)
    return Math.max(days * dayWidth, dayWidth)
  }

  const now = new Date()
  const todayStart = new Date(now.getFullYear(), now.getMonth(), now.getDate())

  return (
    <div className="flex overflow-hidden rounded-lg border">
      {/* Labels column */}
      <div className="bg-card border-border shrink-0 border-r" style={{ width: labelWidth }}>
        {/* Header spacer */}
        <div className="border-border h-8 border-b" />

        {medications.map((med) => {
          const typeInfo = MEDICATION_TYPES[med.type]
          const isEnded = med.endDate && new Date(med.endDate) < todayStart

          return (
            <div
              key={med.id}
              className="border-border flex items-center gap-1.5 border-b px-2"
              style={{ height: barHeight + barGap }}
            >
              <div
                className="h-2 w-2 shrink-0 rounded-full"
                style={{ backgroundColor: typeInfo.color, opacity: isEnded ? 0.5 : 1 }}
              />
              <span
                className="truncate text-xs font-medium"
                style={{ opacity: isEnded ? 0.5 : 1 }}
                title={med.name}
              >
                {med.name}
              </span>
            </div>
          )
        })}
      </div>

      {/* Scrollable chart area */}
      <div ref={scrollRef} className="flex-1 overflow-x-auto">
        <div style={{ width: chartWidth, minWidth: '100%' }}>
          {/* Month headers */}
          <div className="border-border relative flex h-8 border-b">
            {months.map((month) => {
              const left = getBarLeft(month)
              const monthEnd = endOfMonth(month)
              const width = getBarWidth(month, monthEnd)

              return (
                <div
                  key={month.toISOString()}
                  className="border-border absolute border-l px-1 text-[10px]"
                  style={{ left, width, lineHeight: '32px' }}
                >
                  <span className="text-muted-foreground capitalize">
                    {format(month, 'MMM yy', { locale: dateLocale })}
                  </span>
                </div>
              )
            })}
          </div>

          {/* Bars */}
          {medications.map((med) => {
            const start = new Date(med.startDate)
            const end = med.endDate ? new Date(med.endDate) : new Date()
            const typeInfo = MEDICATION_TYPES[med.type]
            const isEnded = med.endDate && new Date(med.endDate) < todayStart
            const left = getBarLeft(start)
            const width = getBarWidth(start, end)

            return (
              <div
                key={med.id}
                className="border-border relative border-b"
                style={{ height: barHeight + barGap }}
              >
                <div
                  className="absolute top-1 rounded"
                  style={{
                    left,
                    width,
                    height: barHeight,
                    backgroundColor: typeInfo.color,
                    opacity: isEnded ? 0.35 : 0.7,
                    borderStyle: isEnded ? 'dashed' : 'solid',
                    borderWidth: 1,
                    borderColor: typeInfo.color,
                  }}
                />
                {/* Active indicator: pulsing right edge */}
                {!isEnded && (
                  <div
                    className="absolute top-1 animate-pulse rounded-r"
                    style={{
                      left: left + width - 3,
                      width: 3,
                      height: barHeight,
                      backgroundColor: typeInfo.color,
                    }}
                  />
                )}
              </div>
            )
          })}
        </div>
      </div>
    </div>
  )
}

// src/lib/components/medications/TreatmentGanttChart.svelte
<script lang="ts">
  import { i18n, getDateLocale } from '$lib/i18n.svelte'
  import { MEDICATION_TYPES } from '$lib/constants'
  import type { Medication } from '$lib/types'
  import { format, differenceInDays, startOfMonth, endOfMonth, eachMonthOfInterval } from 'date-fns'

  let { medications }: { medications: Medication[] } = $props()

  let dateLocale = $derived(getDateLocale(i18n.locale))

  let timelineStart = $derived.by(() => {
    if (medications.length === 0) return startOfMonth(new Date())
    const starts = medications.map((m) => new Date(m.startDate))
    return startOfMonth(new Date(Math.min(...starts.map((d) => d.getTime()))))
  })

  let months = $derived.by(() => {
    if (medications.length === 0) return [startOfMonth(new Date())]
    const ends = medications.map((m) => (m.endDate ? new Date(m.endDate) : new Date()))
    const latest = endOfMonth(new Date(Math.max(...ends.map((d) => d.getTime()), Date.now())))
    return eachMonthOfInterval({ start: timelineStart, end: latest })
  })

  const dayWidth = 3
  const barHeight = 28
  const barGap = 8
  const labelWidth = 150

  let chartWidth = $derived.by(() => {
    if (medications.length === 0) return 300
    const ends = medications.map((m) => (m.endDate ? new Date(m.endDate) : new Date()))
    const latest = new Date(Math.max(...ends.map((d) => d.getTime()), Date.now()))
    return Math.max(differenceInDays(latest, timelineStart) * dayWidth, 300)
  })

  function getBarLeft(date: Date): number {
    return Math.max(differenceInDays(date, timelineStart) * dayWidth, 0)
  }

  function getBarWidth(start: Date, end: Date): number {
    return Math.max(differenceInDays(end, start) * dayWidth, dayWidth)
  }

  let todayStart = $derived.by(() => {
    const now = new Date()
    return new Date(now.getFullYear(), now.getMonth(), now.getDate())
  })
</script>

{#if medications.length === 0}
  <p class="empty">{i18n.t('medications.history.noTreatments')}</p>
{:else}
  <div class="gantt">
    <div class="labels" style:width={`${labelWidth}px`}>
      <div class="header-spacer"></div>
      {#each medications as med (med.id)}
        {@const typeInfo = MEDICATION_TYPES[med.type]}
        {@const isEnded = med.endDate !== undefined && new Date(med.endDate) < todayStart}
        <div class="label-row" style:height={`${barHeight + barGap}px`}>
          <span class="dot" style:background={typeInfo.color} style:opacity={isEnded ? 0.5 : 1}
          ></span>
          <span class="name" style:opacity={isEnded ? 0.5 : 1} title={med.name}>{med.name}</span>
        </div>
      {/each}
    </div>

    <div class="chart">
      <div style:width={`${chartWidth}px`} style:min-width="100%">
        <div class="months">
          {#each months as month (month.toISOString())}
            {@const left = getBarLeft(month)}
            {@const width = getBarWidth(month, endOfMonth(month))}
            <div class="month-label" style:left={`${left}px`} style:width={`${width}px`}>
              {format(month, 'MMM yy', { locale: dateLocale })}
            </div>
          {/each}
        </div>

        {#each medications as med (med.id)}
          {@const typeInfo = MEDICATION_TYPES[med.type]}
          {@const start = new Date(med.startDate)}
          {@const end = med.endDate ? new Date(med.endDate) : new Date()}
          {@const isEnded = med.endDate !== undefined && new Date(med.endDate) < todayStart}
          {@const left = getBarLeft(start)}
          {@const width = getBarWidth(start, end)}
          <div class="bar-row" style:height={`${barHeight + barGap}px`}>
            <div
              class="bar"
              class:ended={isEnded}
              style:left={`${left}px`}
              style:width={`${width}px`}
              style:height={`${barHeight}px`}
              style:background={typeInfo.color}
              style:border-color={typeInfo.color}
            ></div>
            {#if !isEnded}
              <div
                class="bar-edge"
                style:left={`${left + width - 3}px`}
                style:height={`${barHeight}px`}
                style:background={typeInfo.color}
              ></div>
            {/if}
          </div>
        {/each}
      </div>
    </div>
  </div>
{/if}

<style>
  .empty {
    font-size: 13px;
    color: var(--ink-soft);
    text-align: center;
    padding: 16px 0;
  }
  .gantt {
    display: flex;
    overflow: hidden;
    border: 1px solid var(--line);
    border-radius: 14px;
  }
  .labels {
    flex-shrink: 0;
    background: var(--bg);
    border-right: 1px solid var(--line);
  }
  .header-spacer {
    height: 32px;
    border-bottom: 1px solid var(--line);
  }
  .label-row {
    display: flex;
    align-items: center;
    gap: 6px;
    padding: 0 8px;
    border-bottom: 1px solid var(--line);
  }
  .dot {
    width: 8px;
    height: 8px;
    border-radius: 50%;
    flex-shrink: 0;
  }
  .name {
    font-size: 11px;
    font-weight: 600;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
  .chart {
    flex: 1;
    overflow-x: auto;
  }
  .months {
    position: relative;
    height: 32px;
    border-bottom: 1px solid var(--line);
  }
  .month-label {
    position: absolute;
    border-left: 1px solid var(--line);
    padding: 0 4px;
    font-size: 10px;
    line-height: 32px;
    color: var(--ink-soft);
    text-transform: capitalize;
  }
  .bar-row {
    position: relative;
    border-bottom: 1px solid var(--line);
  }
  .bar {
    position: absolute;
    top: 4px;
    border-radius: 4px;
    border-width: 1px;
    border-style: solid;
    opacity: 0.7;
  }
  .bar.ended {
    opacity: 0.35;
    border-style: dashed;
  }
  .bar-edge {
    position: absolute;
    top: 4px;
    width: 3px;
    border-radius: 0 4px 4px 0;
  }
</style>
