// src/app/practitioners/new/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { useTranslations } from 'next-intl'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { ArrowLeft } from 'lucide-react'
import { addPractitioner } from '@/lib/db'
import { PractitionerFormFields } from '@/components/practitioners/PractitionerFormFields'
import type { AppointmentType } from '@/lib/types'

export default function NewPractitionerPage() {
  const router = useRouter()
  const t = useTranslations('practitioners')
  const tc = useTranslations('common')
  const [saving, setSaving] = useState(false)

  // Form state
  const [name, setName] = useState('')
  const [specialty, setSpecialty] = useState<AppointmentType>('general')
  const [location, setLocation] = useState('')
  const [phone, setPhone] = useState('')
  const [email, setEmail] = useState('')
  const [website, setWebsite] = useState('')
  const [notes, setNotes] = useState('')
  const [isTransFriendly, setIsTransFriendly] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!name.trim()) return

    setSaving(true)
    try {
      await addPractitioner({
        name: name.trim(),
        specialty,
        location: location.trim() || undefined,
        phone: phone.trim() || undefined,
        email: email.trim() || undefined,
        website: website.trim() || undefined,
        notes: notes.trim() || undefined,
        isTransFriendly,
      })

      router.push('/practitioners')
    } catch (error) {
      console.error('Failed to create practitioner:', error)
      setSaving(false)
    }
  }

  return (
    <div className="space-y-6 p-4 pb-24">
      <div className="flex items-center gap-3 pt-2">
        <Link href="/practitioners">
          <Button variant="ghost" size="icon" className="shrink-0">
            <ArrowLeft className="h-5 w-5" />
          </Button>
        </Link>
        <div>
          <h1 className="text-foreground text-2xl font-bold">{t('new.title')}</h1>
          <p className="text-muted-foreground text-sm">{t('new.subtitle')}</p>
        </div>
      </div>

      <form onSubmit={handleSubmit} className="space-y-6">
        <PractitionerFormFields
          name={name}
          onNameChange={setName}
          specialty={specialty}
          onSpecialtyChange={setSpecialty}
          location={location}
          onLocationChange={setLocation}
          phone={phone}
          onPhoneChange={setPhone}
          email={email}
          onEmailChange={setEmail}
          website={website}
          onWebsiteChange={setWebsite}
          notes={notes}
          onNotesChange={setNotes}
          isTransFriendly={isTransFriendly}
          onIsTransFriendlyChange={setIsTransFriendly}
          saving={saving}
          isValid={name.trim().length > 0}
          backHref="/practitioners"
          labels={{
            basicInfo: t('new.basicInfo'),
            fullName: t('new.fullName'),
            namePlaceholder: t('new.namePlaceholder'),
            specialty: t('new.specialty'),
            transFriendly: t('new.transFriendly'),
            transFriendlyDesc: t('new.transFriendlyDesc'),
            contact: t('new.contact'),
            address: t('new.address'),
            addressPlaceholder: t('new.addressPlaceholder'),
            phone: t('new.phone'),
            phonePlaceholder: t('new.phonePlaceholder'),
            email: t('new.email'),
            emailPlaceholder: t('new.emailPlaceholder'),
            website: t('new.website'),
            websitePlaceholder: t('new.websitePlaceholder'),
            notes: t('new.notes'),
            notesPlaceholder: t('new.notesPlaceholder'),
            cancel: tc('cancel'),
            save: t('new.save'),
            saving: t('new.saving'),
          }}
        />
      </form>
    </div>
  )
}

// src/routes/practitioners/new/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation'
  import { i18n } from '$lib/i18n.svelte'
  import { addPractitioner } from '$lib/db'
  import type { AppointmentType } from '$lib/types'
  import PractitionerFormFields from '$lib/components/practitioners/PractitionerFormFields.svelte'
  import ArrowLeft from '@lucide/svelte/icons/arrow-left'

  let saving = $state(false)

  let name = $state('')
  let specialty = $state<AppointmentType>('general')
  let location = $state('')
  let phone = $state('')
  let email = $state('')
  let website = $state('')
  let notes = $state('')
  let isTransFriendly = $state(false)

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault()
    if (!name.trim()) return

    saving = true
    try {
      await addPractitioner({
        name: name.trim(),
        specialty,
        location: location.trim() || undefined,
        phone: phone.trim() || undefined,
        email: email.trim() || undefined,
        website: website.trim() || undefined,
        notes: notes.trim() || undefined,
        isTransFriendly,
      })
      await goto('/practitioners')
    } finally {
      saving = false
    }
  }
</script>

<div class="header">
  <a href="/practitioners" class="icon-link" aria-label={i18n.t('common.back')}
    ><ArrowLeft size={20} /></a
  >
  <div>
    <h1>{i18n.t('practitioners.new.title')}</h1>
    <p class="subtitle">{i18n.t('practitioners.new.subtitle')}</p>
  </div>
</div>

<form onsubmit={handleSubmit}>
  <PractitionerFormFields
    bind:name
    bind:specialty
    bind:location
    bind:phone
    bind:email
    bind:website
    bind:notes
    bind:isTransFriendly
    {saving}
    backHref="/practitioners"
  />
</form>

<style>
  .header {
    display: flex;
    align-items: center;
    gap: 10px;
    margin-bottom: 18px;
  }
  h1 {
    font-size: 19px;
    font-weight: 700;
    margin: 0;
  }
  .subtitle {
    font-size: 12.5px;
    color: var(--ink-soft);
    margin: 2px 0 0;
  }
  .icon-link {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 36px;
    height: 36px;
    border-radius: 10px;
    color: var(--ink);
    text-decoration: none;
    flex-shrink: 0;
  }
</style>
