// src/app/medications/calendar/page.tsx
'use client'

import { useEffect, useState } from 'react'
import { useLocale, useTranslations } from 'next-intl'
import { getDateLocale } from '@/i18n/date-locale'
import type { Locale } from '@/i18n/config'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Calendar } from '@/components/ui/calendar'
import { Checkbox } from '@/components/ui/checkbox'
import { ArrowLeft, Check, X, Calendar as CalendarIcon, Loader2 } from 'lucide-react'
import Link from 'next/link'
import {
  format,
  startOfMonth,
  endOfMonth,
  isSameDay,
  eachDayOfInterval,
  differenceInDays,
} from 'date-fns'
import { db, getMedications } from '@/lib/db'
import { getMedicationReminderTimes, shouldTakeMedicationOnDate } from '@/lib/notifications'
import type { Medication, MedicationLog } from '@/lib/types'

export default function MedicationsCalendarPage() {
  const t = useTranslations('medications')
  const tc = useTranslations('common')
  const locale = useLocale()
  const dateLocale = getDateLocale(locale as Locale)
  const [medications, setMedications] = useState<Medication[]>([])
  const [logs, setLogs] = useState<MedicationLog[]>([])
  const [totalDaysWithLogs, setTotalDaysWithLogs] = useState(0)
  const [selectedDate, setSelectedDate] = useState<Date>(new Date())
  const [currentMonth, setCurrentMonth] = useState<Date>(new Date())
  const [loading, setLoading] = useState(true)
  const [validating, setValidating] = useState(false)
  const [togglingDose, setTogglingDose] = useState<string | null>(null)

  useEffect(() => {
    async function loadData() {
      // Load ALL medications (including inactive/ended) for historical calendar view
      const meds = await getMedications(false)
      setMedications(meds)

      // Calculate total calendar days since first dose
      const allLogs = await db.medicationLogs.filter((log) => log.taken === true).toArray()
      if (allLogs.length > 0) {
        const firstDose = allLogs.reduce((earliest, log) => {
          const logDate = new Date(log.timestamp)
          return logDate < earliest ? logDate : earliest
        }, new Date(allLogs[0]!.timestamp))
        setTotalDaysWithLogs(differenceInDays(new Date(), firstDose) + 1)
      }

      setLoading(false)
    }
    loadData()
  }, [])

  // Load logs when month changes
  useEffect(() => {
    async function loadLogs() {
      const start = startOfMonth(currentMonth)
      const end = endOfMonth(currentMonth)

      const monthLogs = await db.medicationLogs.where('timestamp').between(start, end).toArray()

      setLogs(monthLogs)
    }
    loadLogs()
  }, [currentMonth])

  // Get logs for a specific day
  function getLogsForDay(date: Date) {
    return logs.filter((log) => isSameDay(new Date(log.timestamp), date))
  }

  // Get days with activity in current month (only days with taken doses)
  function getDaysWithLogs(): Date[] {
    const uniqueDays = new Map<string, Date>()
    logs.forEach((log) => {
      if (!log.taken) return // Only count taken doses
      const day = new Date(log.timestamp)
      const key = format(day, 'yyyy-MM-dd')
      if (!uniqueDays.has(key)) {
        uniqueDays.set(key, day)
      }
    })
    return Array.from(uniqueDays.values())
  }

  // Toggle a specific dose
  async function toggleDose(med: Medication, time: string, doseIndex: number) {
    const toggleKey = `${med.id}-${time}`
    setTogglingDose(toggleKey)

    try {
      // Find existing log for this dose
      const existingLog = logs.find(
        (l) =>
          l.medicationId === med.id &&
          isSameDay(new Date(l.timestamp), selectedDate) &&
          l.scheduledTime === time
      )

      if (existingLog) {
        // Toggle existing log
        await db.medicationLogs.update(existingLog.id!, { taken: !existingLog.taken })
      } else {
        // Create new log as taken
        await db.medicationLogs.add({
          medicationId: med.id!,
          timestamp: selectedDate,
          taken: true,
          scheduledTime: time,
          doseIndex,
        })
      }

      // Reload logs for the selected day
      const start = startOfMonth(currentMonth)
      const end = endOfMonth(currentMonth)
      const monthLogs = await db.medicationLogs.where('timestamp').between(start, end).toArray()
      setLogs(monthLogs)
    } catch (error) {
      console.error('Error toggling dose:', error)
    } finally {
      setTogglingDose(null)
    }
  }

  // Validate entire month - mark all doses as taken
  async function validateMonth() {
    if (
      !confirm(
        t('calendar.validateConfirm', {
          month: format(currentMonth, 'MMMM yyyy', { locale: dateLocale }),
        })
      )
    ) {
      return
    }

    setValidating(true)
    try {
      const start = startOfMonth(currentMonth)
      const end = endOfMonth(currentMonth)
      const days = eachDayOfInterval({ start, end })

      let totalAdded = 0

      for (const day of days) {
        for (const med of medications) {
          if (!shouldTakeMedicationOnDate(med, day)) continue

          const doseTimes = getMedicationReminderTimes(med)

          for (const time of doseTimes) {
            // Check if log already exists
            const existingLog = logs.find(
              (l) =>
                l.medicationId === med.id &&
                isSameDay(new Date(l.timestamp), day) &&
                l.scheduledTime === time
            )

            if (!existingLog) {
              // Create new log
              await db.medicationLogs.add({
                medicationId: med.id!,
                timestamp: day,
                taken: true,
                scheduledTime: time,
                doseIndex: doseTimes.indexOf(time),
              })
              totalAdded++
            } else if (!existingLog.taken) {
              // Update existing log to mark as taken
              await db.medicationLogs.update(existingLog.id!, { taken: true })
              totalAdded++
            }
          }
        }
      }

      // Reload logs
      const monthLogs = await db.medicationLogs.where('timestamp').between(start, end).toArray()
      setLogs(monthLogs)

      alert(`✅ ${t('calendar.validateSuccess', { count: totalAdded })}`)
    } catch (error) {
      console.error('Error validating month:', error)
      alert(`❌ ${t('calendar.validateError')}`)
    } finally {
      setValidating(false)
    }
  }

  // Calculate stats for selected day
  const selectedDayLogs = getLogsForDay(selectedDate)
  const takenCount = selectedDayLogs.filter((l) => l.taken).length

  // Medications to take for the selected day (strictly within their treatment period)
  const medicationsForSelectedDay = medications.filter((med) =>
    shouldTakeMedicationOnDate(med, selectedDate)
  )

  // Total doses: counts the individual doses for the medications to take that day
  const totalDoses = medicationsForSelectedDay.reduce((sum, med) => {
    const doseTimes = getMedicationReminderTimes(med)
    return sum + doseTimes.length
  }, 0)

  // Days with logs for highlighting
  const daysWithLogs = getDaysWithLogs()

  if (loading) {
    return (
      <div className="flex min-h-[50vh] items-center justify-center p-4">
        <p className="text-muted-foreground">{tc('loading')}</p>
      </div>
    )
  }

  return (
    <div className="space-y-6 p-4 pb-24">
      {/* Header */}
      <div className="flex items-center gap-3 pt-2">
        <Link href="/medications">
          <Button variant="ghost" size="icon">
            <ArrowLeft className="h-5 w-5" />
          </Button>
        </Link>
        <div>
          <h1 className="text-foreground text-xl font-bold">{t('calendar.title')}</h1>
          <p className="text-muted-foreground text-sm">{t('calendar.subtitle')}</p>
        </div>
      </div>

      {/* Calendar */}
      <Card>
        <CardContent className="p-3">
          <Calendar
            mode="single"
            selected={selectedDate}
            onSelect={(date) => date && setSelectedDate(date)}
            onMonthChange={setCurrentMonth}
            locale={dateLocale}
            modifiers={{
              hasLogs: daysWithLogs,
            }}
            modifiersStyles={{
              hasLogs: {
                fontWeight: 'bold',
                backgroundColor: 'var(--primary)',
                color: 'white',
                borderRadius: '50%',
              },
            }}
            className="rounded-md"
          />
        </CardContent>
      </Card>

      {/* Selected Day Details */}
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="flex items-center justify-between text-base">
            <span>{format(selectedDate, 'EEEE d MMMM yyyy', { locale: dateLocale })}</span>
            {takenCount > 0 && (
              <Badge variant="secondary">
                {takenCount}/{totalDoses} {t('calendar.taken')}
              </Badge>
            )}
          </CardTitle>
        </CardHeader>
        <CardContent>
          {medications.length === 0 ? (
            <p className="text-muted-foreground py-4 text-center text-sm">{t('calendar.noMeds')}</p>
          ) : medicationsForSelectedDay.length === 0 ? (
            <p className="text-muted-foreground py-4 text-center text-sm">
              {t('calendar.noDoses')}
            </p>
          ) : (
            <div className="space-y-2">
              {medicationsForSelectedDay.map((med) => {
                const medLogs = selectedDayLogs.filter((l) => l.medicationId === med.id)
                const doseTimes = getMedicationReminderTimes(med)
                const hasMultipleDoses = doseTimes.length > 1

                // Multiple doses: display each dose separately
                if (hasMultipleDoses) {
                  return (
                    <div key={med.id} className="space-y-1.5">
                      <p className="text-muted-foreground px-1 text-xs font-medium">
                        {med.name} ({med.dosage} {med.unit})
                      </p>
                      {doseTimes.map((time, idx) => {
                        const doseLog = medLogs.find((l) => l.scheduledTime === time)
                        const taken = doseLog?.taken ?? false
                        const toggleKey = `${med.id}-${time}`
                        const isToggling = togglingDose === toggleKey

                        return (
                          <div
                            key={toggleKey}
                            className={`flex items-center justify-between rounded-lg p-2.5 transition-colors ${
                              taken ? 'bg-primary/10' : 'bg-muted/30'
                            }`}
                          >
                            <div className="flex items-center gap-3">
                              {isToggling ? (
                                <Loader2 className="text-muted-foreground h-4 w-4 animate-spin" />
                              ) : (
                                <Checkbox
                                  checked={taken}
                                  onCheckedChange={() => toggleDose(med, time, idx)}
                                  className="h-5 w-5"
                                />
                              )}
                              <span className="text-foreground text-sm font-medium">{time}</span>
                            </div>
                            {taken && doseLog && (
                              <span className="text-muted-foreground text-xs">
                                {format(new Date(doseLog.timestamp), 'HH:mm')}
                              </span>
                            )}
                          </div>
                        )
                      })}
                    </div>
                  )
                }

                // Single dose: one entry
                const taken = medLogs.some((l) => l.taken)
                const takenAt = medLogs.find((l) => l.taken)
                const time = doseTimes[0] || '00:00'
                const toggleKey = `${med.id}-${time}`
                const isToggling = togglingDose === toggleKey

                return (
                  <div
                    key={med.id}
                    className={`flex items-center justify-between rounded-lg p-3 transition-colors ${
                      taken ? 'bg-primary/10' : 'bg-muted/30'
                    }`}
                  >
                    <div className="flex items-center gap-3">
                      {isToggling ? (
                        <Loader2 className="text-muted-foreground h-5 w-5 animate-spin" />
                      ) : (
                        <Checkbox
                          checked={taken}
                          onCheckedChange={() => toggleDose(med, time, 0)}
                          className="h-5 w-5"
                        />
                      )}
                      <div>
                        <p className="text-foreground text-sm font-medium">{med.name}</p>
                        <p className="text-muted-foreground text-xs">
                          {med.dosage} {med.unit}
                        </p>
                      </div>
                    </div>
                    {taken && takenAt && (
                      <span className="text-muted-foreground text-xs">
                        {format(new Date(takenAt.timestamp), 'HH:mm')}
                      </span>
                    )}
                  </div>
                )
              })}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Monthly Stats */}
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-base">
            {t('calendar.stats')} - {format(currentMonth, 'MMMM yyyy', { locale: dateLocale })}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="bg-muted/30 rounded-lg p-3 text-center">
              <p className="text-primary text-2xl font-bold">{daysWithLogs.length}</p>
              <p className="text-muted-foreground text-xs">{t('calendar.daysWithDoses')}</p>
            </div>
            <div className="bg-muted/30 rounded-lg p-3 text-center">
              <p className="text-foreground text-2xl font-bold">
                {logs.filter((l) => l.taken).length}
              </p>
              <p className="text-muted-foreground text-xs">{t('calendar.totalDoses')}</p>
            </div>
          </div>

          {totalDaysWithLogs > 0 && (
            <div className="bg-primary/10 rounded-lg p-3 text-center">
              <p className="text-primary text-2xl font-bold">{totalDaysWithLogs}</p>
              <p className="text-muted-foreground text-xs">{t('calendar.daysSinceStart')}</p>
            </div>
          )}

          <Button
            onClick={validateMonth}
            disabled={validating || medications.length === 0}
            variant="outline"
            className="w-full"
          >
            <CalendarIcon className="mr-2 h-4 w-4" />
            {validating ? t('calendar.validating') : t('calendar.validateMonth')}
          </Button>
          <p className="text-muted-foreground text-center text-xs">{t('calendar.validateHelp')}</p>
        </CardContent>
      </Card>
    </div>
  )
}

// src/routes/medications/calendar/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import {
    format,
    startOfMonth,
    endOfMonth,
    isSameDay,
    eachDayOfInterval,
    differenceInDays,
  } from 'date-fns'
  import { i18n, getDateLocale } from '$lib/i18n.svelte'
  import { db, getMedications } from '$lib/db'
  import { getMedicationReminderTimes, shouldTakeMedicationOnDate } from '$lib/notifications'
  import type { Medication, MedicationLog } from '$lib/types'
  import MonthCalendar from '$lib/components/ui/MonthCalendar.svelte'
  import ArrowLeft from '@lucide/svelte/icons/arrow-left'
  import CalendarIcon from '@lucide/svelte/icons/calendar'
  import Loader2 from '@lucide/svelte/icons/loader-2'

  let medications = $state<Medication[]>([])
  let logs = $state<MedicationLog[]>([])
  let totalDaysWithLogs = $state(0)
  let selectedDate = $state(new Date())
  let currentMonth = $state(new Date())
  let loading = $state(true)
  let validating = $state(false)
  let togglingDose = $state<string | null>(null)

  let dateLocale = $derived(getDateLocale(i18n.locale))

  async function reloadMonthLogs() {
    const start = startOfMonth(currentMonth)
    const end = endOfMonth(currentMonth)
    logs = await db.medicationLogs.where('timestamp').between(start, end).toArray()
  }

  onMount(async () => {
    medications = await getMedications(false)

    const allLogs = await db.medicationLogs.filter((log) => log.taken === true).toArray()
    if (allLogs.length > 0) {
      const firstDose = allLogs.reduce((earliest, log) => {
        const logDate = new Date(log.timestamp)
        return logDate < earliest ? logDate : earliest
      }, new Date(allLogs[0]!.timestamp))
      totalDaysWithLogs = differenceInDays(new Date(), firstDose) + 1
    }

    await reloadMonthLogs()
    loading = false
  })

  function getLogsForDay(date: Date) {
    return logs.filter((log) => isSameDay(new Date(log.timestamp), date))
  }

  let daysWithLogs = $derived.by(() => {
    const uniqueDays: Record<string, Date> = {}
    for (const log of logs) {
      if (!log.taken) continue
      const day = new Date(log.timestamp)
      uniqueDays[format(day, 'yyyy-MM-dd')] = day
    }
    return Object.values(uniqueDays)
  })

  async function toggleDose(med: Medication, time: string, doseIndex: number) {
    const toggleKey = `${med.id}-${time}`
    togglingDose = toggleKey

    const existingLog = logs.find(
      (l) =>
        l.medicationId === med.id &&
        isSameDay(new Date(l.timestamp), selectedDate) &&
        l.scheduledTime === time
    )

    if (existingLog) {
      await db.medicationLogs.update(existingLog.id!, { taken: !existingLog.taken })
    } else {
      await db.medicationLogs.add({
        medicationId: med.id!,
        timestamp: selectedDate,
        taken: true,
        scheduledTime: time,
        doseIndex,
      })
    }

    await reloadMonthLogs()
    togglingDose = null
  }

  async function validateMonth() {
    if (
      !confirm(
        i18n
          .t('medications.calendar.validateConfirm')
          .replace('{month}', format(currentMonth, 'MMMM yyyy', { locale: dateLocale }))
      )
    ) {
      return
    }

    validating = true
    const start = startOfMonth(currentMonth)
    const end = endOfMonth(currentMonth)
    const days = eachDayOfInterval({ start, end })

    let totalAdded = 0

    for (const day of days) {
      for (const med of medications) {
        if (!shouldTakeMedicationOnDate(med, day)) continue

        const doseTimes = getMedicationReminderTimes(med)

        for (const time of doseTimes) {
          const existingLog = logs.find(
            (l) =>
              l.medicationId === med.id &&
              isSameDay(new Date(l.timestamp), day) &&
              l.scheduledTime === time
          )

          if (!existingLog) {
            await db.medicationLogs.add({
              medicationId: med.id!,
              timestamp: day,
              taken: true,
              scheduledTime: time,
              doseIndex: doseTimes.indexOf(time),
            })
            totalAdded++
          } else if (!existingLog.taken) {
            await db.medicationLogs.update(existingLog.id!, { taken: true })
            totalAdded++
          }
        }
      }
    }

    await reloadMonthLogs()
    alert(i18n.t('medications.calendar.validateSuccess').replace('{count}', String(totalAdded)))
    validating = false
  }

  let selectedDayLogs = $derived(getLogsForDay(selectedDate))
  let takenCount = $derived(selectedDayLogs.filter((l) => l.taken).length)
  let medicationsForSelectedDay = $derived(
    medications.filter((med) => shouldTakeMedicationOnDate(med, selectedDate))
  )
  let totalDoses = $derived(
    medicationsForSelectedDay.reduce((sum, med) => sum + getMedicationReminderTimes(med).length, 0)
  )
</script>

{#if loading}
  <p class="loading">{i18n.t('common.loading')}</p>
{:else}
  <div class="header">
    <a href="/medications" class="icon-link" aria-label={i18n.t('common.back')}
      ><ArrowLeft size={20} /></a
    >
    <div>
      <h1>{i18n.t('medications.calendar.title')}</h1>
      <p class="subtitle">{i18n.t('medications.calendar.subtitle')}</p>
    </div>
  </div>

  <div class="card">
    <MonthCalendar
      {currentMonth}
      {selectedDate}
      highlighted={daysWithLogs}
      {dateLocale}
      onSelectDate={(d) => (selectedDate = d)}
      onMonthChange={async (d) => {
        currentMonth = d
        await reloadMonthLogs()
      }}
    />
  </div>

  <div class="card">
    <div class="day-header">
      <span>{format(selectedDate, 'EEEE d MMMM yyyy', { locale: dateLocale })}</span>
      {#if takenCount > 0}
        <span class="chip">{takenCount}/{totalDoses} {i18n.t('medications.calendar.taken')}</span>
      {/if}
    </div>

    {#if medications.length === 0}
      <p class="empty">{i18n.t('medications.calendar.noMeds')}</p>
    {:else if medicationsForSelectedDay.length === 0}
      <p class="empty">{i18n.t('medications.calendar.noDoses')}</p>
    {:else}
      <div class="dose-list">
        {#each medicationsForSelectedDay as med (med.id)}
          {@const medLogs = selectedDayLogs.filter((l) => l.medicationId === med.id)}
          {@const doseTimes = getMedicationReminderTimes(med)}
          {#if doseTimes.length > 1}
            <p class="med-label">{med.name} ({med.dosage} {med.unit})</p>
            {#each doseTimes as time, idx (time)}
              {@const doseLog = medLogs.find((l) => l.scheduledTime === time)}
              {@const taken = doseLog?.taken ?? false}
              {@const toggleKey = `${med.id}-${time}`}
              {@const isToggling = togglingDose === toggleKey}
              <div class="dose-line" class:taken>
                <div class="dose-left">
                  {#if isToggling}
                    <Loader2 size={16} />
                  {:else}
                    <input
                      type="checkbox"
                      checked={taken}
                      onchange={() => toggleDose(med, time, idx)}
                    />
                  {/if}
                  <span>{time}</span>
                </div>
                {#if taken && doseLog}
                  <span class="dose-time">{format(new Date(doseLog.timestamp), 'HH:mm')}</span>
                {/if}
              </div>
            {/each}
          {:else}
            {@const taken = medLogs.some((l) => l.taken)}
            {@const takenAt = medLogs.find((l) => l.taken)}
            {@const time = doseTimes[0] || '00:00'}
            {@const toggleKey = `${med.id}-${time}`}
            {@const isToggling = togglingDose === toggleKey}
            <div class="dose-line" class:taken>
              <div class="dose-left">
                {#if isToggling}
                  <Loader2 size={16} />
                {:else}
                  <input
                    type="checkbox"
                    checked={taken}
                    onchange={() => toggleDose(med, time, 0)}
                  />
                {/if}
                <div>
                  <p class="med-name">{med.name}</p>
                  <p class="med-dosage">{med.dosage} {med.unit}</p>
                </div>
              </div>
              {#if taken && takenAt}
                <span class="dose-time">{format(new Date(takenAt.timestamp), 'HH:mm')}</span>
              {/if}
            </div>
          {/if}
        {/each}
      </div>
    {/if}
  </div>

  <div class="card">
    <p class="card-title">
      {i18n.t('medications.calendar.stats')} · {format(currentMonth, 'MMMM yyyy', {
        locale: dateLocale,
      })}
    </p>
    <div class="stats-grid">
      <div class="stat">
        <p class="stat-num">{daysWithLogs.length}</p>
        <p class="stat-label">{i18n.t('medications.calendar.daysWithDoses')}</p>
      </div>
      <div class="stat">
        <p class="stat-num">{logs.filter((l) => l.taken).length}</p>
        <p class="stat-label">{i18n.t('medications.calendar.totalDoses')}</p>
      </div>
    </div>

    {#if totalDaysWithLogs > 0}
      <div class="stat-wide">
        <p class="stat-num">{totalDaysWithLogs}</p>
        <p class="stat-label">{i18n.t('medications.calendar.daysSinceStart')}</p>
      </div>
    {/if}

    <button
      type="button"
      class="btn-outline-block"
      disabled={validating || medications.length === 0}
      onclick={validateMonth}
    >
      <CalendarIcon size={16} />
      {validating
        ? i18n.t('medications.calendar.validating')
        : i18n.t('medications.calendar.validateMonth')}
    </button>
    <p class="help">{i18n.t('medications.calendar.validateHelp')}</p>
  </div>
{/if}

<style>
  .loading {
    color: var(--ink-soft);
    text-align: center;
    padding: 40px 0;
  }
  .header {
    display: flex;
    align-items: center;
    gap: 10px;
    margin-bottom: 18px;
  }
  h1 {
    font-size: 19px;
    font-weight: 700;
    margin: 0;
  }
  .subtitle {
    font-size: 12.5px;
    color: var(--ink-soft);
    margin: 2px 0 0;
  }
  .icon-link {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 36px;
    height: 36px;
    border-radius: 10px;
    color: var(--ink);
    text-decoration: none;
    flex-shrink: 0;
  }
  .card {
    background: var(--bg);
    border: 1px solid var(--line);
    border-radius: 16px;
    padding: 14px;
    margin-bottom: 14px;
  }
  .day-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-size: 14px;
    font-weight: 600;
    margin-bottom: 12px;
    text-transform: capitalize;
  }
  .chip {
    font-size: 11.5px;
    font-weight: 600;
    padding: 3px 9px;
    border-radius: 999px;
    background: color-mix(in srgb, var(--blue-deep) 18%, transparent);
    color: var(--blue-deep);
  }
  .empty {
    font-size: 13px;
    color: var(--ink-soft);
    text-align: center;
    padding: 16px 0;
    margin: 0;
  }
  .dose-list {
    display: flex;
    flex-direction: column;
    gap: 6px;
  }
  .med-label {
    font-size: 11.5px;
    font-weight: 600;
    color: var(--ink-soft);
    margin: 6px 0 0;
  }
  .dose-line {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 8px 10px;
    border-radius: 10px;
    background: var(--page);
  }
  .dose-line.taken {
    background: color-mix(in srgb, var(--blue-deep) 12%, transparent);
  }
  .dose-left {
    display: flex;
    align-items: center;
    gap: 10px;
  }
  .med-name {
    font-size: 13.5px;
    font-weight: 600;
    margin: 0;
  }
  .med-dosage {
    font-size: 11.5px;
    color: var(--ink-soft);
    margin: 0;
  }
  .dose-time {
    font-size: 11.5px;
    color: var(--ink-soft);
  }
  .card-title {
    font-size: 13px;
    font-weight: 600;
    margin: 0 0 12px;
    text-transform: capitalize;
  }
  .stats-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 10px;
    margin-bottom: 10px;
  }
  .stat,
  .stat-wide {
    background: var(--page);
    border-radius: 10px;
    padding: 10px;
    text-align: center;
  }
  .stat-wide {
    margin-bottom: 12px;
  }
  .stat-num {
    font-size: 20px;
    font-weight: 700;
    margin: 0;
  }
  .stat-label {
    font-size: 11px;
    color: var(--ink-soft);
    margin: 2px 0 0;
  }
  .btn-outline-block {
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
    padding: 11px;
    border-radius: 12px;
    border: 1px solid var(--line);
    background: transparent;
    color: var(--ink);
    font-family: inherit;
    font-size: 13.5px;
    font-weight: 600;
    cursor: pointer;
  }
  .btn-outline-block:disabled {
    opacity: 0.5;
    cursor: default;
  }
  .help {
    font-size: 11px;
    color: var(--ink-faint);
    text-align: center;
    margin: 8px 0 0;
  }
</style>
