// src/routes/appointments/calendar/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { format, isSameDay, isThisYear } from 'date-fns'
  import { i18n, getDateLocale } from '$lib/i18n.svelte'
  import { getAppointments, getUpcomingAppointments } from '$lib/db'
  import type { Appointment } from '$lib/types'
  import YearCalendar from '$lib/components/appointments/YearCalendar.svelte'
  import ArrowLeft from '@lucide/svelte/icons/arrow-left'
  import Plus from '@lucide/svelte/icons/plus'

  let allAppointments = $state<Appointment[]>([])
  let upcomingCount = $state(0)
  let selectedDate = $state(new Date())
  let loading = $state(true)

  let dateLocale = $derived(getDateLocale(i18n.locale))

  onMount(async () => {
    const [all, upcoming] = await Promise.all([getAppointments(500), getUpcomingAppointments()])
    allAppointments = all
    upcomingCount = upcoming.length
    loading = false
  })

  let thisYearCount = $derived(allAppointments.filter((a) => isThisYear(new Date(a.date))).length)

  let selectedDayAppointments = $derived(
    allAppointments
      .filter((a) => isSameDay(new Date(a.date), selectedDate))
      .sort((a, b) => (a.time ?? '').localeCompare(b.time ?? ''))
  )
</script>

{#if loading}
  <p class="loading">{i18n.t('common.loading')}</p>
{:else}
  <div class="header">
    <a href="/appointments" class="icon-link" aria-label={i18n.t('common.back')}
      ><ArrowLeft size={20} /></a
    >
    <div>
      <h1>{i18n.t('appointments.calendarPage.title')}</h1>
      <p class="subtitle">{i18n.t('appointments.calendarPage.subtitle')}</p>
    </div>
  </div>

  <div class="stats-grid">
    <div class="stat">
      <p class="stat-num">{allAppointments.length}</p>
      <p class="stat-label">{i18n.t('appointments.calendarPage.total')}</p>
    </div>
    <div class="stat">
      <p class="stat-num">{upcomingCount}</p>
      <p class="stat-label">{i18n.t('appointments.calendarPage.upcoming')}</p>
    </div>
    <div class="stat">
      <p class="stat-num">{thisYearCount}</p>
      <p class="stat-label">{i18n.t('appointments.calendarPage.thisYear')}</p>
    </div>
  </div>

  <div class="card">
    <YearCalendar
      appointments={allAppointments}
      {selectedDate}
      {dateLocale}
      onSelectDate={(d) => (selectedDate = d)}
    />
  </div>

  <div class="card">
    <div class="day-header">
      <span>{format(selectedDate, 'EEEE d MMMM yyyy', { locale: dateLocale })}</span>
      <a
        href="/appointments/new"
        class="icon-link small"
        aria-label={i18n.t('appointments.calendarPage.addRdv')}><Plus size={16} /></a
      >
    </div>

    {#if selectedDayAppointments.length === 0}
      <p class="empty">{i18n.t('appointments.calendarPage.noneThisDay')}</p>
    {:else}
      <div class="apt-list">
        {#each selectedDayAppointments as apt (apt.id)}
          <a href={`/appointments/${apt.id}`} class="apt-line">
            <span class="apt-type">{i18n.t('appointments.types.' + apt.type)}</span>
            {#if apt.time}<span class="apt-time">{apt.time}</span>{/if}
          </a>
        {/each}
      </div>
    {/if}
  </div>
{/if}

<style>
  .loading {
    color: var(--ink-soft);
    text-align: center;
    padding: 40px 0;
  }
  .header {
    display: flex;
    align-items: center;
    gap: 10px;
    margin-bottom: 18px;
  }
  h1 {
    font-size: 19px;
    font-weight: 700;
    margin: 0;
  }
  .subtitle {
    font-size: 12.5px;
    color: var(--ink-soft);
    margin: 2px 0 0;
  }
  .icon-link {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 36px;
    height: 36px;
    border-radius: 10px;
    color: var(--ink);
    text-decoration: none;
    flex-shrink: 0;
  }
  .icon-link.small {
    width: 30px;
    height: 30px;
    border: 1px solid var(--line);
  }
  .stats-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 8px;
    margin-bottom: 14px;
  }
  .stat {
    background: var(--bg);
    border: 1px solid var(--line);
    border-radius: 12px;
    padding: 10px;
    text-align: center;
  }
  .stat-num {
    font-size: 18px;
    font-weight: 700;
    margin: 0;
  }
  .stat-label {
    font-size: 10.5px;
    color: var(--ink-soft);
    margin: 2px 0 0;
  }
  .card {
    background: var(--bg);
    border: 1px solid var(--line);
    border-radius: 16px;
    padding: 14px;
    margin-bottom: 14px;
  }
  .day-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-size: 14px;
    font-weight: 600;
    margin-bottom: 12px;
    text-transform: capitalize;
  }
  .empty {
    font-size: 13px;
    color: var(--ink-soft);
    text-align: center;
    padding: 16px 0;
    margin: 0;
  }
  .apt-list {
    display: flex;
    flex-direction: column;
    gap: 6px;
  }
  .apt-line {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 9px 10px;
    border-radius: 10px;
    background: var(--page);
    text-decoration: none;
  }
  .apt-type {
    font-size: 13.5px;
    font-weight: 600;
  }
  .apt-time {
    font-size: 12px;
    color: var(--ink-soft);
  }
</style>

// src/app/appointments/calendar/page.tsx
'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import {
  ArrowLeft,
  Plus,
  Calendar as CalendarIcon,
  Clock,
  User,
  MapPin,
  ChevronRight,
} from 'lucide-react'
import { format } from 'date-fns'
import { getAppointments } from '@/lib/db'
import { useTranslations, useLocale } from 'next-intl'
import { getDateLocale } from '@/i18n/date-locale'
import type { Locale } from '@/i18n/config'
import { APPOINTMENT_TYPES } from '@/lib/constants'
import type { Appointment } from '@/lib/types'
import { YearCalendar } from '@/components/appointments/year-calendar'

export default function CalendarPage() {
  const t = useTranslations('appointments')
  const locale = useLocale()
  const dateLocale = getDateLocale(locale as Locale)
  const router = useRouter()
  const [appointments, setAppointments] = useState<Appointment[]>([])
  const [loading, setLoading] = useState(true)
  const [selectedDate, setSelectedDate] = useState<Date | null>(null)
  const [selectedAppointments, setSelectedAppointments] = useState<Appointment[]>([])

  useEffect(() => {
    async function loadAppointments() {
      // Load all appointments (high limit for the yearly view)
      const data = await getAppointments(500)
      setAppointments(data)
      setLoading(false)
    }
    loadAppointments()
  }, [])

  const handleDayClick = (date: Date, dayAppointments: Appointment[]) => {
    setSelectedDate(date)
    setSelectedAppointments(dayAppointments)
  }

  const handleAppointmentClick = (appointment: Appointment) => {
    router.push(`/appointments/${appointment.id}`)
  }

  return (
    <div className="space-y-6 p-4 pb-24">
      {/* Header */}
      <div className="flex items-center justify-between pt-2">
        <div className="flex items-center gap-3">
          <Link href="/appointments">
            <Button variant="ghost" size="icon">
              <ArrowLeft className="h-5 w-5" />
            </Button>
          </Link>
          <div>
            <h1 className="text-foreground flex items-center gap-2 text-xl font-bold">
              <CalendarIcon className="text-trans-pink h-5 w-5" />
              {t('calendarPage.title')}
            </h1>
            <p className="text-muted-foreground text-sm">{t('calendarPage.subtitle')}</p>
          </div>
        </div>
        <Link href="/appointments/new">
          <Button size="sm" className="gap-2">
            <Plus className="h-4 w-4" />
            {t('add')}
          </Button>
        </Link>
      </div>

      {/* Stats rapides */}
      <div className="grid grid-cols-3 gap-3">
        <Card>
          <CardContent className="p-4 text-center">
            <p className="text-foreground text-2xl font-bold">{appointments.length}</p>
            <p className="text-muted-foreground text-xs">{t('calendarPage.total')}</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 text-center">
            <p className="text-foreground text-2xl font-bold">
              {appointments.filter((a) => new Date(a.date) >= new Date()).length}
            </p>
            <p className="text-muted-foreground text-xs">{t('calendarPage.upcoming')}</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 text-center">
            <p className="text-foreground text-2xl font-bold">
              {
                appointments.filter((a) => {
                  const d = new Date(a.date)
                  const now = new Date()
                  return d.getFullYear() === now.getFullYear()
                }).length
              }
            </p>
            <p className="text-muted-foreground text-xs">{t('calendarPage.thisYear')}</p>
          </CardContent>
        </Card>
      </div>

      {/* Calendrier */}
      {loading ? (
        <Card>
          <CardContent className="py-12 text-center">
            <p className="text-muted-foreground">{t('calendarPage.loading')}</p>
          </CardContent>
        </Card>
      ) : (
        <Card>
          <CardContent className="p-4">
            <YearCalendar appointments={appointments} onDayClick={handleDayClick} />
          </CardContent>
        </Card>
      )}

      {/* Dialog for the selected day's appointments */}
      <Dialog open={!!selectedDate} onOpenChange={() => setSelectedDate(null)}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <CalendarIcon className="text-primary h-5 w-5" />
              {selectedDate && format(selectedDate, 'EEEE d MMMM yyyy', { locale: dateLocale })}
            </DialogTitle>
          </DialogHeader>

          <div className="mt-4 space-y-3">
            {selectedAppointments.length === 0 ? (
              <div className="py-6 text-center">
                <p className="text-muted-foreground mb-4">{t('calendarPage.noneThisDay')}</p>
                <Link href="/appointments/new">
                  <Button className="gap-2">
                    <Plus className="h-4 w-4" />
                    {t('calendarPage.addRdv')}
                  </Button>
                </Link>
              </div>
            ) : (
              selectedAppointments
                .sort((a, b) => {
                  if (!a.time || !b.time) return 0
                  return a.time.localeCompare(b.time)
                })
                .map((apt) => {
                  const typeInfo = APPOINTMENT_TYPES[apt.type]
                  return (
                    <button
                      key={apt.id}
                      onClick={() => handleAppointmentClick(apt)}
                      className="border-border hover:bg-muted/50 w-full rounded-lg border p-3 text-left transition-colors"
                    >
                      <div className="flex items-start gap-3">
                        <div
                          className="shrink-0 rounded-lg p-2"
                          style={{ backgroundColor: `${typeInfo?.color}20` }}
                        >
                          <CalendarIcon className="h-4 w-4" style={{ color: typeInfo?.color }} />
                        </div>
                        <div className="min-w-0 flex-1">
                          <div className="flex items-center gap-2">
                            <p className="text-foreground font-medium">{t('types.' + apt.type)}</p>
                            {apt.time && (
                              <Badge variant="outline" className="text-xs">
                                {apt.time}
                              </Badge>
                            )}
                          </div>
                          <div className="text-muted-foreground mt-1 flex flex-wrap gap-2 text-sm">
                            {apt.doctor && (
                              <span className="flex items-center gap-1">
                                <User className="h-3 w-3" />
                                {apt.doctor}
                              </span>
                            )}
                            {apt.location && (
                              <span className="flex items-center gap-1">
                                <MapPin className="h-3 w-3" />
                                {apt.location}
                              </span>
                            )}
                          </div>
                        </div>
                        <ChevronRight className="text-muted-foreground h-4 w-4 shrink-0 self-center" />
                      </div>
                    </button>
                  )
                })
            )}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  )
}
