// src/lib/components/journal/MoodPicker.svelte
<script lang="ts">
  import { i18n } from '$lib/i18n.svelte'
  import { MOOD_LEVELS, MOOD_EMOJI, MOOD_COLOR } from './mood-config'
  import type { MoodLevel } from '$lib/types'

  let {
    value = $bindable(),
    label,
    size = 'md',
  }: {
    value: MoodLevel | undefined
    label: string
    size?: 'md' | 'lg'
  } = $props()
</script>

<div class="mood-picker">
  <p class="mood-label">{label}</p>
  <div class="mood-row">
    {#each MOOD_LEVELS as level (level)}
      {@const moodLabel = i18n.t('journal.moods.' + level)}
      <button
        type="button"
        class="mood-btn size-{size}"
        class:selected={value === level}
        style:background={value === level
          ? `color-mix(in srgb, ${MOOD_COLOR[level]} 30%, transparent)`
          : undefined}
        style:border-color={value === level ? MOOD_COLOR[level] : undefined}
        onclick={() => (value = level)}
        title={moodLabel}
        aria-label={moodLabel}
      >
        {MOOD_EMOJI[level]}
      </button>
    {/each}
  </div>
  {#if value}
    <p class="mood-value">{i18n.t('journal.moods.' + value)}</p>
  {/if}
</div>

<style>
  .mood-picker {
    margin-bottom: 4px;
  }
  .mood-label {
    font-size: 12px;
    color: var(--ink-soft);
    margin: 0 0 8px;
  }
  .mood-row {
    display: flex;
    align-items: center;
    gap: 8px;
  }
  .mood-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    border-radius: 50%;
    border: 2px solid var(--line);
    background: var(--page);
    cursor: pointer;
    opacity: 0.6;
    transition:
      opacity 0.15s ease,
      background 0.15s ease,
      border-color 0.15s ease;
  }
  .mood-btn.selected {
    opacity: 1;
  }
  .size-md {
    width: 38px;
    height: 38px;
    font-size: 18px;
  }
  .size-lg {
    width: 46px;
    height: 46px;
    font-size: 22px;
  }
  .mood-value {
    font-size: 12px;
    color: var(--ink-soft);
    margin: 6px 0 0;
  }
</style>

// src/components/journal/mood-picker.tsx
'use client'

import { useTranslations } from 'next-intl'
import { cn } from '@/lib/utils'
import type { MoodLevel } from '@/lib/types'

interface MoodPickerProps {
  value?: MoodLevel
  onChange: (mood: MoodLevel) => void
  label?: string
  size?: 'sm' | 'md' | 'lg'
}

const moodConfig: { level: MoodLevel; emoji: string; labelKey: string; color: string }[] = [
  {
    level: 1,
    emoji: '😢',
    labelKey: '1',
    color: 'bg-red-500/20 border-red-500/50 hover:bg-red-500/30',
  },
  {
    level: 2,
    emoji: '😔',
    labelKey: '2',
    color: 'bg-orange-500/20 border-orange-500/50 hover:bg-orange-500/30',
  },
  {
    level: 3,
    emoji: '😐',
    labelKey: '3',
    color: 'bg-yellow-500/20 border-yellow-500/50 hover:bg-yellow-500/30',
  },
  {
    level: 4,
    emoji: '🙂',
    labelKey: '4',
    color: 'bg-green-500/20 border-green-500/50 hover:bg-green-500/30',
  },
  {
    level: 5,
    emoji: '😊',
    labelKey: '5',
    color: 'bg-emerald-500/20 border-emerald-500/50 hover:bg-emerald-500/30',
  },
]

const selectedColors: Record<MoodLevel, string> = {
  1: 'bg-red-500 border-red-500 text-white',
  2: 'bg-orange-500 border-orange-500 text-white',
  3: 'bg-yellow-500 border-yellow-500 text-black',
  4: 'bg-green-500 border-green-500 text-white',
  5: 'bg-emerald-500 border-emerald-500 text-white',
}

const sizeClasses = {
  sm: 'w-8 h-8 text-lg',
  md: 'w-10 h-10 text-xl',
  lg: 'w-12 h-12 text-2xl',
}

export function MoodPicker({ value, onChange, label, size = 'md' }: MoodPickerProps) {
  const t = useTranslations('journal')
  return (
    <div className="space-y-2">
      {label && <label className="text-foreground text-sm font-medium">{label}</label>}
      <div className="flex items-center gap-2">
        {moodConfig.map((mood) => {
          const isSelected = value === mood.level
          const moodLabel = t(`moods.${mood.labelKey}`)
          return (
            <button
              key={mood.level}
              type="button"
              onClick={() => onChange(mood.level)}
              className={cn(
                'flex items-center justify-center rounded-full border-2 transition-all',
                sizeClasses[size],
                isSelected ? selectedColors[mood.level] : mood.color + ' opacity-60'
              )}
              title={moodLabel}
              aria-label={moodLabel}
            >
              {mood.emoji}
            </button>
          )
        })}
      </div>
      {value && <p className="text-muted-foreground text-xs">{t(`moods.${value}`)}</p>}
    </div>
  )
}

export function MoodDisplay({ mood, size = 'sm' }: { mood: MoodLevel; size?: 'sm' | 'md' | 'lg' }) {
  const t = useTranslations('journal')
  const config = moodConfig.find((m) => m.level === mood)
  if (!config) return null

  return (
    <span
      className={cn(
        'inline-flex items-center justify-center rounded-full',
        sizeClasses[size],
        selectedColors[mood]
      )}
      title={t(`moods.${mood}`)}
    >
      {config.emoji}
    </span>
  )
}

export { moodConfig }
