// src/routes/appointments/new/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { goto } from '$app/navigation'
  import { i18n } from '$lib/i18n.svelte'
  import {
    addAppointment,
    getObjectives,
    findOrCreatePractitioner,
    incrementPractitionerUsage,
  } from '$lib/db'
  import type { AppointmentType, Objective } from '$lib/types'
  import AppointmentFormFields from '$lib/components/appointments/AppointmentFormFields.svelte'
  import ArrowLeft from '@lucide/svelte/icons/arrow-left'

  let loading = $state(false)
  let objectives = $state<Objective[]>([])

  let date = $state(new Date().toISOString().split('T')[0]!)
  let time = $state('')
  let type = $state<AppointmentType>('general')
  let doctor = $state('')
  let practitionerId = $state<number | undefined>(undefined)
  let location = $state('')
  let notes = $state('')
  let cost = $state('')
  let reminderMinutes = $state('')
  let objectiveId = $state('')

  onMount(async () => {
    objectives = await getObjectives()
  })

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault()
    if (!date) {
      alert(i18n.t('appointments.form.selectDateAlert'))
      return
    }

    loading = true
    try {
      let finalPractitionerId = practitionerId
      if (doctor && !practitionerId) {
        finalPractitionerId = await findOrCreatePractitioner(doctor, type)
      } else if (practitionerId) {
        await incrementPractitionerUsage(practitionerId)
      }

      await addAppointment({
        date: new Date(date),
        time: time || undefined,
        type,
        doctor: doctor || undefined,
        practitionerId: finalPractitionerId,
        location: location || undefined,
        notes: notes || undefined,
        cost: cost ? parseFloat(cost) : undefined,
        reminderMinutes: reminderMinutes ? parseInt(reminderMinutes) : undefined,
        objectiveId: objectiveId ? parseInt(objectiveId) : undefined,
      })
      await goto('/appointments')
    } catch {
      alert(i18n.t('appointments.form.saveError'))
    } finally {
      loading = false
    }
  }
</script>

<div class="header">
  <a href="/appointments" class="icon-link" aria-label={i18n.t('common.back')}
    ><ArrowLeft size={20} /></a
  >
  <div>
    <h1>{i18n.t('appointments.new.title')}</h1>
    <p class="subtitle">{i18n.t('appointments.new.subtitle')}</p>
  </div>
</div>

<form onsubmit={handleSubmit}>
  <AppointmentFormFields
    bind:date
    bind:time
    bind:type
    bind:doctor
    bind:practitionerId
    bind:location
    bind:notes
    bind:cost
    bind:reminderMinutes
    bind:objectiveId
    {objectives}
    saving={loading}
    backHref="/appointments"
  />
</form>

<style>
  .header {
    display: flex;
    align-items: center;
    gap: 10px;
    margin-bottom: 18px;
  }
  h1 {
    font-size: 19px;
    font-weight: 700;
    margin: 0;
  }
  .subtitle {
    font-size: 12.5px;
    color: var(--ink-soft);
    margin: 2px 0 0;
  }
  .icon-link {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 36px;
    height: 36px;
    border-radius: 10px;
    color: var(--ink);
    text-decoration: none;
    flex-shrink: 0;
  }
</style>

// src/app/appointments/new/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { useLocale } from 'next-intl'
import { getDateLocale } from '@/i18n/date-locale'
import type { Locale } from '@/i18n/config'
import { Button } from '@/components/ui/button'
import { ArrowLeft } from 'lucide-react'
import Link from 'next/link'
import {
  addAppointment,
  addReminder,
  findOrCreatePractitioner,
  incrementPractitionerUsage,
  getObjectives,
} from '@/lib/db'
import { useTranslations } from 'next-intl'
import type { AppointmentType, Objective, Practitioner } from '@/lib/types'
import { AppointmentFormFields } from '@/components/appointments/AppointmentFormFields'
import { getModulePreferences } from '@/lib/notifications'

export default function NewAppointmentPage() {
  const t = useTranslations('appointments')
  const router = useRouter()
  const locale = useLocale()
  const dateLocale = getDateLocale(locale as Locale)
  const [saving, setSaving] = useState(false)

  // Form state
  const [type, setType] = useState<AppointmentType>('endocrinologist')
  const [date, setDate] = useState<Date | undefined>(undefined)
  const [time, setTime] = useState('')
  const [doctor, setDoctor] = useState('')
  const [practitionerId, setPractitionerId] = useState<number | undefined>()
  const [location, setLocation] = useState('')
  const [notes, setNotes] = useState('')
  const [reminderMinutes, setReminderMinutes] = useState<number | undefined>(60)
  const [cost, setCost] = useState<string>('')
  const [showCostTracking, setShowCostTracking] = useState(
    () => getModulePreferences().costTrackingEnabled
  )
  const [objectiveId, setObjectiveId] = useState<number | undefined>(undefined)
  const [linkedObjectives, setLinkedObjectives] = useState<Objective[]>([])

  useEffect(() => {
    getObjectives()
      .then((all) =>
        setLinkedObjectives(all.filter((o) => o.source === 'act' || o.category === 'medical'))
      )
      .catch((error) => console.error('Error loading objectives:', error))
  }, [])

  // Handle practitioner text change
  const handlePractitionerChange = (name: string, id?: number) => {
    setDoctor(name)
    setPractitionerId(id)
  }

  // Handle practitioner selection: auto-fill location
  const handlePractitionerSelect = (practitioner: Practitioner) => {
    // Auto-fill the location if the practitioner has an address and the field is empty
    if (practitioner.location && !location) {
      setLocation(practitioner.location)
    }
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()

    if (!date) {
      alert(t('form.selectDateAlert'))
      return
    }

    setSaving(true)

    try {
      // Get or create practitioner ID
      let finalPractitionerId = practitionerId
      if (doctor && !practitionerId) {
        // Auto-create practitioner if name provided but no ID
        finalPractitionerId = await findOrCreatePractitioner(doctor, type)
      } else if (practitionerId) {
        // Increment usage if existing practitioner selected
        await incrementPractitionerUsage(practitionerId)
      }

      // Create the appointment with practitioner link
      const parsedCost = parseFloat(cost)
      const appointmentId = await addAppointment({
        type,
        date,
        time: time || undefined,
        practitionerId: finalPractitionerId,
        doctor: doctor || undefined,
        location: location || undefined,
        notes: notes || undefined,
        reminderMinutes,
        cost: !isNaN(parsedCost) && parsedCost > 0 ? parsedCost : undefined,
        objectiveId: objectiveId || undefined,
      })

      // Create a reminder if set
      if (reminderMinutes && appointmentId) {
        const reminderTime = new Date(date)
        if (time) {
          const [hours, minutes] = time.split(':').map(Number)
          reminderTime.setHours(hours!, minutes!)
        }
        reminderTime.setMinutes(reminderTime.getMinutes() - reminderMinutes)

        await addReminder({
          type: 'appointment',
          referenceId: appointmentId as number,
          title: t('new.reminderTitle', { type: t('types.' + type) }),
          message: doctor ? t('new.reminderMessage', { doctor }) : undefined,
          schedule: reminderTime.toISOString(),
          enabled: true,
        })
      }

      router.push('/appointments')
    } catch (error) {
      console.error('Error saving appointment:', error)
      alert(t('form.saveError'))
      setSaving(false)
    }
  }

  return (
    <div className="space-y-6 p-4 pb-24">
      <div className="flex items-center gap-3 pt-2">
        <Link href="/appointments">
          <Button variant="ghost" size="icon">
            <ArrowLeft className="h-5 w-5" />
          </Button>
        </Link>
        <div>
          <h1 className="text-foreground text-xl font-bold">{t('new.title')}</h1>
          <p className="text-muted-foreground text-sm">{t('new.subtitle')}</p>
        </div>
      </div>

      <form onSubmit={handleSubmit} className="space-y-6">
        <AppointmentFormFields
          type={type}
          onTypeChange={setType}
          date={date}
          onDateChange={setDate}
          time={time}
          onTimeChange={setTime}
          doctor={doctor}
          onPractitionerChange={handlePractitionerChange}
          onPractitionerSelect={handlePractitionerSelect}
          location={location}
          onLocationChange={setLocation}
          notes={notes}
          onNotesChange={setNotes}
          reminderMinutes={reminderMinutes}
          onReminderMinutesChange={setReminderMinutes}
          cost={cost}
          onCostChange={setCost}
          showCostTracking={showCostTracking}
          linkedObjectives={linkedObjectives}
          objectiveId={objectiveId}
          onObjectiveIdChange={setObjectiveId}
          saving={saving}
          dateLocale={dateLocale}
          labels={{
            typeLabel: t('form.typeLabel'),
            selectType: t('form.selectType'),
            dateAndTime: t('form.dateAndTime'),
            dateLabel: t('form.dateLabel'),
            selectDate: t('form.selectDate'),
            timeLabel: t('form.timeLabel'),
            details: t('form.details'),
            practitionerLabel: t('form.practitionerLabel'),
            practitionerPlaceholder: t('form.practitionerPlaceholder'),
            locationLabel: t('form.locationLabel'),
            locationPlaceholder: t('form.locationPlaceholder'),
            notesLabel: t('form.notesLabel'),
            notesPlaceholder: t('form.notesPlaceholder'),
            linkedObjective: t('form.linkedObjective'),
            noLinkedObjective: t('form.noLinkedObjective'),
            costLabel: t('form.costLabel'),
            costPlaceholder: t('form.costPlaceholder'),
            reminderTitle: t('form.reminderTitle'),
            reminderConfig: t('form.reminderConfig'),
            noReminder: t('form.noReminder'),
            save: t('new.save'),
            saving: t('new.saving'),
          }}
        />
      </form>
    </div>
  )
}
