// src/routes/resources/faq/+page.svelte
<script lang="ts">
  import { i18n } from '$lib/i18n.svelte'
  import ArrowLeft from '@lucide/svelte/icons/arrow-left'
  import Smartphone from '@lucide/svelte/icons/smartphone'
  import Stethoscope from '@lucide/svelte/icons/stethoscope'
  import HelpCircle from '@lucide/svelte/icons/help-circle'

  type FAQCategory = 'app' | 'medical' | 'general'

  const faqItemIds: Record<FAQCategory, string[]> = {
    app: [
      'app-data-privacy',
      'app-offline',
      'app-backup',
      'app-install',
      'app-notifications',
      'app-delete-data',
    ],
    medical: ['med-ranges', 'med-tracking', 'med-not-advice'],
    general: ['gen-name', 'gen-contribute', 'gen-support'],
  }

  const categoryConfig: Record<FAQCategory, { icon: typeof Smartphone; color: string }> = {
    app: { icon: Smartphone, color: 'var(--blue-deep)' },
    medical: { icon: Stethoscope, color: 'var(--pink-deep)' },
    general: { icon: HelpCircle, color: 'var(--gold)' },
  }

  const categories: FAQCategory[] = ['app', 'medical', 'general']

  let selectedCategory = $state<FAQCategory | 'all'>('all')

  let displayedItemIds = $derived(
    selectedCategory === 'all'
      ? categories.flatMap((cat) => faqItemIds[cat].map((id) => ({ id, category: cat })))
      : faqItemIds[selectedCategory].map((id) => ({ id, category: selectedCategory }))
  )
</script>

<div class="header">
  <a href="/resources" class="back-btn" aria-label={i18n.t('common.back')}>
    <ArrowLeft size={18} />
  </a>
  <div>
    <h1>{i18n.t('resources.faq.title')}</h1>
    <p class="subtitle">{i18n.t('resources.faq.subtitle')}</p>
  </div>
</div>

<div class="filter-row">
  <button
    type="button"
    class="filter-btn"
    class:active={selectedCategory === 'all'}
    onclick={() => (selectedCategory = 'all')}
  >
    {i18n.t('resources.faq.all')}
  </button>
  {#each categories as cat (cat)}
    {@const config = categoryConfig[cat]}
    <button
      type="button"
      class="filter-btn"
      class:active={selectedCategory === cat}
      onclick={() => (selectedCategory = cat)}
    >
      <config.icon size={14} />
      {i18n.t(`resources.faq.categoriesLabels.${cat}`)}
    </button>
  {/each}
</div>

{#if selectedCategory === 'all'}
  {#each categories as category (category)}
    {@const itemIds = faqItemIds[category]}
    {@const config = categoryConfig[category]}
    <section class="faq-section">
      <div class="section-head">
        <span
          class="category-badge"
          style:background={`color-mix(in srgb, ${config.color} 16%, transparent)`}
          style:color={config.color}
        >
          <config.icon size={13} />
          {i18n.t(`resources.faq.categoriesLabels.${category}`)}
        </span>
        <span class="count-text">
          {itemIds.length}
          {itemIds.length > 1
            ? i18n.t('resources.faq.questions')
            : i18n.t('resources.faq.question')}
        </span>
      </div>
      <div class="item-list">
        {#each itemIds as id (id)}
          {@render faqItem(id)}
        {/each}
      </div>
    </section>
  {/each}
{:else}
  <div class="item-list">
    {#each displayedItemIds as { id } (id)}
      {@render faqItem(id)}
    {/each}
  </div>
{/if}

<div class="card contact-card">
  <p class="row-desc">{i18n.t('resources.faq.helpText')}</p>
  <p class="row-desc">
    {i18n.t('resources.faq.consultPrefix')}
    <a href="/resources">{i18n.t('resources.faq.communityResources')}</a>
    {i18n.t('resources.faq.orReport')}
  </p>
</div>

{#snippet faqItem(id: string)}
  <details class="faq-item">
    <summary>{i18n.t(`resources.faq.items.${id}.q`)}</summary>
    <p class="answer">{i18n.t(`resources.faq.items.${id}.a`)}</p>
  </details>
{/snippet}

<style>
  .header {
    display: flex;
    align-items: center;
    gap: 10px;
    margin-bottom: 16px;
  }
  .back-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 36px;
    height: 36px;
    border-radius: 10px;
    background: var(--bg);
    border: 1px solid var(--line);
    color: var(--ink);
    text-decoration: none;
    flex-shrink: 0;
  }
  h1 {
    font-size: 21px;
    font-weight: 700;
    margin: 0;
  }
  .subtitle {
    font-size: 12.5px;
    color: var(--ink-soft);
    margin: 2px 0 0;
  }
  .filter-row {
    display: flex;
    gap: 8px;
    overflow-x: auto;
    padding-bottom: 4px;
    margin-bottom: 18px;
  }
  .filter-btn {
    display: flex;
    align-items: center;
    gap: 5px;
    flex-shrink: 0;
    padding: 7px 12px;
    border-radius: 999px;
    border: 1px solid var(--line);
    background: var(--bg);
    color: var(--ink-soft);
    font-family: inherit;
    font-size: 12.5px;
    font-weight: 600;
    cursor: pointer;
  }
  .filter-btn.active {
    background: linear-gradient(135deg, var(--blue-deep), var(--pink-deep));
    color: #fff;
    border-color: transparent;
  }
  .faq-section {
    margin-bottom: 20px;
  }
  .section-head {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-bottom: 10px;
  }
  .category-badge {
    display: flex;
    align-items: center;
    gap: 5px;
    font-size: 11.5px;
    font-weight: 700;
    padding: 4px 10px;
    border-radius: 999px;
  }
  .count-text {
    font-size: 12px;
    color: var(--ink-soft);
  }
  .item-list {
    display: flex;
    flex-direction: column;
    gap: 8px;
  }
  .faq-item {
    background: var(--bg);
    border: 1px solid var(--line);
    border-radius: 14px;
    padding: 4px 14px;
  }
  .faq-item summary {
    padding: 10px 0;
    font-size: 13.5px;
    font-weight: 600;
    cursor: pointer;
    list-style: none;
  }
  .faq-item summary::-webkit-details-marker {
    display: none;
  }
  .answer {
    font-size: 12.5px;
    line-height: 1.5;
    color: var(--ink-soft);
    border-left: 2px solid color-mix(in srgb, var(--blue-deep) 30%, transparent);
    margin: 0 0 12px;
    padding-left: 12px;
  }
  .row-desc {
    font-size: 12.5px;
    color: var(--ink-soft);
    margin: 0 0 6px;
  }
  .card {
    background: var(--bg);
    border: 1px solid var(--line);
    border-radius: 16px;
    padding: 16px;
  }
  .contact-card {
    text-align: center;
    margin-top: 8px;
  }
  .contact-card a {
    color: var(--blue-deep);
    text-decoration: underline;
  }
</style>

// src/app/resources/faq/page.tsx
'use client'

import { useState } from 'react'
import { useTranslations } from 'next-intl'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible'
import { ArrowLeft, ChevronDown, Smartphone, Stethoscope, HelpCircle } from 'lucide-react'
import Link from 'next/link'

type FAQCategory = 'app' | 'medical' | 'general'

const faqItemIds: Record<FAQCategory, string[]> = {
  app: [
    'app-data-privacy',
    'app-offline',
    'app-backup',
    'app-install',
    'app-notifications',
    'app-delete-data',
  ],
  medical: ['med-ranges', 'med-tracking', 'med-not-advice'],
  general: ['gen-name', 'gen-contribute', 'gen-support'],
}

const categoryConfig: Record<FAQCategory, { icon: React.ReactNode; color: string }> = {
  app: {
    icon: <Smartphone className="h-4 w-4" />,
    color: 'bg-blue-500/20 text-blue-400',
  },
  medical: {
    icon: <Stethoscope className="h-4 w-4" />,
    color: 'bg-pink-500/20 text-pink-400',
  },
  general: {
    icon: <HelpCircle className="h-4 w-4" />,
    color: 'bg-purple-500/20 text-purple-400',
  },
}

function FAQItemCard({
  id,
  category,
  t,
}: {
  id: string
  category: FAQCategory
  t: ReturnType<typeof useTranslations<'resources'>>
}) {
  const [isOpen, setIsOpen] = useState(false)
  const config = categoryConfig[category]

  return (
    <Collapsible open={isOpen} onOpenChange={setIsOpen}>
      <Card className={isOpen ? 'ring-primary/30 ring-1' : ''}>
        <CollapsibleTrigger asChild>
          <CardContent className="cursor-pointer p-4">
            <div className="flex items-start gap-3">
              <div className={`rounded-lg p-2 ${config.color} shrink-0`}>{config.icon}</div>
              <div className="min-w-0 flex-1">
                <h3 className="text-foreground text-left font-medium">{t(`faq.items.${id}.q`)}</h3>
              </div>
              <ChevronDown
                className={`text-muted-foreground h-5 w-5 shrink-0 transition-transform ${
                  isOpen ? 'rotate-180' : ''
                }`}
              />
            </div>
          </CardContent>
        </CollapsibleTrigger>
        <CollapsibleContent>
          <div className="px-4 pt-0 pb-4">
            <div className="border-primary/20 ml-4 border-l-2 pl-12">
              <p className="text-muted-foreground text-sm leading-relaxed">
                {t(`faq.items.${id}.a`)}
              </p>
            </div>
          </div>
        </CollapsibleContent>
      </Card>
    </Collapsible>
  )
}

function FAQSection({
  category,
  itemIds,
  t,
}: {
  category: FAQCategory
  itemIds: string[]
  t: ReturnType<typeof useTranslations<'resources'>>
}) {
  const config = categoryConfig[category]

  if (itemIds.length === 0) return null

  return (
    <section className="space-y-3">
      <div className="flex items-center gap-2">
        <Badge variant="outline" className={`${config.color} border-0`}>
          {config.icon}
          <span className="ml-1">{t(`faq.categoriesLabels.${category}`)}</span>
        </Badge>
        <span className="text-muted-foreground text-sm">
          {itemIds.length} {itemIds.length > 1 ? t('faq.questions') : t('faq.question')}
        </span>
      </div>
      <div className="space-y-2">
        {itemIds.map((id) => (
          <FAQItemCard key={id} id={id} category={category} t={t} />
        ))}
      </div>
    </section>
  )
}

export default function FAQPage() {
  const t = useTranslations('resources')
  const [selectedCategory, setSelectedCategory] = useState<FAQCategory | 'all'>('all')

  const categories: FAQCategory[] = ['app', 'medical', 'general']

  const displayedItemIds =
    selectedCategory === 'all'
      ? categories.flatMap((cat) => faqItemIds[cat].map((id) => ({ id, category: cat })))
      : faqItemIds[selectedCategory].map((id) => ({ id, category: selectedCategory }))

  return (
    <div className="space-y-6 p-4 pb-24">
      {/* Header */}
      <div className="flex items-center gap-3 pt-2">
        <Link href="/resources">
          <Button variant="ghost" size="icon" className="shrink-0">
            <ArrowLeft className="h-5 w-5" />
          </Button>
        </Link>
        <div>
          <h1 className="text-foreground text-2xl font-bold">{t('faq.title')}</h1>
          <p className="text-muted-foreground text-sm">{t('faq.subtitle')}</p>
        </div>
      </div>

      {/* Category Filter */}
      <div className="-mx-4 flex gap-2 overflow-x-auto px-4 pb-2">
        <Button
          variant={selectedCategory === 'all' ? 'default' : 'outline'}
          size="sm"
          onClick={() => setSelectedCategory('all')}
          className="shrink-0"
        >
          {t('faq.all')}
        </Button>
        {categories.map((cat) => {
          const config = categoryConfig[cat]
          return (
            <Button
              key={cat}
              variant={selectedCategory === cat ? 'default' : 'outline'}
              size="sm"
              onClick={() => setSelectedCategory(cat)}
              className="shrink-0 gap-1"
            >
              {config.icon}
              {t(`faq.categoriesLabels.${cat}`)}
            </Button>
          )
        })}
      </div>

      {/* Content */}
      {selectedCategory === 'all' ? (
        <div className="space-y-8">
          {categories.map((category) => (
            <FAQSection key={category} category={category} itemIds={faqItemIds[category]} t={t} />
          ))}
        </div>
      ) : (
        <div className="space-y-2">
          {displayedItemIds.map(({ id, category }) => (
            <FAQItemCard key={id} id={id} category={category} t={t} />
          ))}
        </div>
      )}

      {/* Contact */}
      <Card className="from-primary/5 bg-gradient-to-r to-pink-500/5">
        <CardContent className="space-y-2 p-4 text-center">
          <p className="text-muted-foreground text-sm">{t('faq.helpText')}</p>
          <p className="text-muted-foreground text-sm">
            {t('faq.consultPrefix')}{' '}
            <Link href="/resources" className="text-primary hover:underline">
              {t('faq.communityResources')}
            </Link>{' '}
            {t('faq.orReport')}
          </p>
        </CardContent>
      </Card>
    </div>
  )
}
