// src/lib/components/onboarding/WelcomeStep.svelte
<script lang="ts">
  import { i18n } from '$lib/i18n.svelte'
  import Lock from '@lucide/svelte/icons/lock'
  import Shield from '@lucide/svelte/icons/shield'
  import Heart from '@lucide/svelte/icons/heart'

  let { onNext }: { onNext: () => void } = $props()
</script>

<div class="welcome">
  <p class="wordmark">Chrysalide</p>

  <div class="intro">
    <h1>{i18n.t('onboarding.welcome.title')}</h1>
    <p class="subtitle">{i18n.t('onboarding.welcome.subtitle')}</p>
  </div>

  <div class="features">
    <div class="feature">
      <div class="feature-icon"><Lock size={18} /></div>
      <div>
        <p class="feature-title">{i18n.t('onboarding.welcome.localTitle')}</p>
        <p class="feature-desc">{i18n.t('onboarding.welcome.localDesc')}</p>
      </div>
    </div>
    <div class="feature">
      <div class="feature-icon pink"><Shield size={18} /></div>
      <div>
        <p class="feature-title">{i18n.t('onboarding.welcome.privacyTitle')}</p>
        <p class="feature-desc">{i18n.t('onboarding.welcome.privacyDesc')}</p>
      </div>
    </div>
    <div class="feature">
      <div class="feature-icon ok"><Heart size={18} /></div>
      <div>
        <p class="feature-title">{i18n.t('onboarding.welcome.communityTitle')}</p>
        <p class="feature-desc">{i18n.t('onboarding.welcome.communityDesc')}</p>
      </div>
    </div>
  </div>

  <button type="button" class="cta" onclick={onNext}>
    {i18n.t('onboarding.welcome.start')}
  </button>
</div>

<style>
  .welcome {
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    gap: 28px;
    padding: 32px 0;
  }
  .wordmark {
    font-size: 26px;
    font-weight: 800;
    margin: 0;
    background: linear-gradient(135deg, var(--blue-deep), var(--pink-deep));
    background-clip: text;
    -webkit-background-clip: text;
    color: transparent;
  }
  .intro {
    display: flex;
    flex-direction: column;
    gap: 6px;
  }
  h1 {
    font-size: 22px;
    font-weight: 700;
    margin: 0;
  }
  .subtitle {
    font-size: 13px;
    color: var(--ink-soft);
    margin: 0;
  }
  .features {
    width: 100%;
    display: flex;
    flex-direction: column;
    gap: 10px;
    text-align: left;
  }
  .feature {
    display: flex;
    align-items: flex-start;
    gap: 12px;
    padding: 14px;
    border-radius: 14px;
    border: 1px solid var(--line);
    background: var(--bg);
  }
  .feature-icon {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 36px;
    height: 36px;
    border-radius: 10px;
    background: color-mix(in srgb, var(--blue-deep) 14%, transparent);
    color: var(--blue-deep);
    flex-shrink: 0;
  }
  .feature-icon.pink {
    background: color-mix(in srgb, var(--pink-deep) 14%, transparent);
    color: var(--pink-deep);
  }
  .feature-icon.ok {
    background: color-mix(in srgb, var(--ok) 16%, transparent);
    color: var(--ok);
  }
  .feature-title {
    font-size: 13.5px;
    font-weight: 600;
    margin: 0;
  }
  .feature-desc {
    font-size: 12px;
    color: var(--ink-soft);
    margin: 2px 0 0;
  }
  .cta {
    width: 100%;
    padding: 14px;
    border-radius: 14px;
    border: none;
    background: linear-gradient(135deg, var(--blue-deep), var(--pink-deep));
    color: #fff;
    font-family: inherit;
    font-size: 15px;
    font-weight: 700;
    cursor: pointer;
  }
  .cta:active {
    transform: scale(0.98);
  }
</style>

// src/components/onboarding/welcome-step.tsx
'use client'

import { Shield, Lock, Heart } from 'lucide-react'
import { useTranslations } from 'next-intl'
import { ChrysalideLogo } from '@/components/brand/logo'

interface WelcomeStepProps {
  onNext: () => void
}

export function WelcomeStep({ onNext }: WelcomeStepProps) {
  const t = useTranslations('onboarding')
  return (
    <div className="flex flex-col items-center space-y-8 py-8 text-center">
      {/* Logo */}
      <div className="animate-flutter">
        <ChrysalideLogo size={80} animated={false} />
      </div>

      {/* Title */}
      <div className="space-y-2">
        <h1 className="text-gradient-trans text-3xl font-bold">{t('welcome.title')}</h1>
        <p className="text-muted-foreground">{t('welcome.subtitle')}</p>
      </div>

      {/* Privacy Features */}
      <div className="w-full space-y-3 text-left">
        <div
          className="bg-card border-border animate-slide-up flex items-start gap-3 rounded-xl border p-4"
          style={{ animationDelay: '0.1s' }}
        >
          <div className="bg-primary/10 text-primary rounded-lg p-2">
            <Lock className="h-5 w-5" />
          </div>
          <div>
            <p className="text-foreground font-medium">{t('welcome.localTitle')}</p>
            <p className="text-muted-foreground text-sm">{t('welcome.localDesc')}</p>
          </div>
        </div>

        <div
          className="bg-card border-border animate-slide-up flex items-start gap-3 rounded-xl border p-4"
          style={{ animationDelay: '0.2s' }}
        >
          <div className="bg-secondary/10 text-secondary rounded-lg p-2">
            <Shield className="h-5 w-5" />
          </div>
          <div>
            <p className="text-foreground font-medium">{t('welcome.privacyTitle')}</p>
            <p className="text-muted-foreground text-sm">{t('welcome.privacyDesc')}</p>
          </div>
        </div>

        <div
          className="bg-card border-border animate-slide-up flex items-start gap-3 rounded-xl border p-4"
          style={{ animationDelay: '0.3s' }}
        >
          <div className="rounded-lg bg-green-500/10 p-2 text-green-500">
            <Heart className="h-5 w-5" />
          </div>
          <div>
            <p className="text-foreground font-medium">{t('welcome.communityTitle')}</p>
            <p className="text-muted-foreground text-sm">{t('welcome.communityDesc')}</p>
          </div>
        </div>
      </div>

      {/* CTA */}
      <button
        onClick={onNext}
        className="gradient-trans-glow shadow-trans-glow hover:shadow-trans-glow-lg w-full rounded-xl py-4 text-lg font-semibold text-white transition-all active:scale-[0.98]"
      >
        {t('welcome.start')}
      </button>
    </div>
  )
}
