// src/lib/components/practitioners/PractitionerInput.svelte
<script lang="ts">
  import { i18n } from '$lib/i18n.svelte'
  import { getPractitioners, searchPractitioners } from '$lib/db'
  import type { AppointmentType, Practitioner } from '$lib/types'
  import User from '@lucide/svelte/icons/user'
  import Plus from '@lucide/svelte/icons/plus'
  import MapPin from '@lucide/svelte/icons/map-pin'
  import Star from '@lucide/svelte/icons/star'

  let {
    value = $bindable(),
    practitionerId = $bindable(),
    specialty,
    placeholder = '',
    id,
    onSelect,
  }: {
    value: string
    practitionerId: number | undefined
    specialty?: AppointmentType
    placeholder?: string
    id?: string
    onSelect?: (practitioner: Practitioner) => void
  } = $props()

  let containerEl: HTMLDivElement | undefined = $state()
  let showSuggestions = $state(false)
  let suggestions = $state<Practitioner[]>([])
  let recentPractitioners = $state<Practitioner[]>([])
  let loading = $state(false)

  $effect(() => {
    const currentSpecialty = specialty
    getPractitioners(currentSpecialty).then((list) => {
      recentPractitioners = list.slice(0, 5)
    })
  })

  $effect(() => {
    const query = value
    if (query.length < 2) {
      suggestions = []
      return
    }
    loading = true
    const timer = setTimeout(() => {
      searchPractitioners(query, specialty)
        .then((results) => (suggestions = results))
        .finally(() => (loading = false))
    }, 200)
    return () => clearTimeout(timer)
  })

  function handleInput() {
    practitionerId = undefined
    showSuggestions = true
  }

  function selectPractitioner(practitioner: Practitioner) {
    value = practitioner.name
    practitionerId = practitioner.id
    onSelect?.(practitioner)
    showSuggestions = false
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape') showSuggestions = false
  }

  function handleClickOutside(e: MouseEvent) {
    if (containerEl && !containerEl.contains(e.target as Node)) {
      showSuggestions = false
    }
  }

  $effect(() => {
    document.addEventListener('mousedown', handleClickOutside)
    return () => document.removeEventListener('mousedown', handleClickOutside)
  })

  let linked = $derived(practitionerId !== undefined)
  let displaySuggestions = $derived(value.length >= 2 ? suggestions : recentPractitioners)
  let showRecent = $derived(value.length < 2 && recentPractitioners.length > 0)
  let showCreateOption = $derived(
    value.length >= 2 && !suggestions.some((p) => p.name.toLowerCase() === value.toLowerCase())
  )
</script>

<div class="wrap" bind:this={containerEl}>
  <div class="input-row">
    <User size={16} class="input-icon" />
    <input
      {id}
      type="text"
      class:linked
      bind:value
      oninput={handleInput}
      onfocus={() => (showSuggestions = true)}
      onkeydown={handleKeydown}
      {placeholder}
    />
  </div>

  {#if showSuggestions && (displaySuggestions.length > 0 || showCreateOption || showRecent)}
    <div class="dropdown">
      {#if showRecent}
        <div class="dropdown-header">{i18n.t('practitioners.input.recentHeader')}</div>
      {/if}

      {#if value.length >= 2 && suggestions.length > 0}
        <div class="dropdown-header">
          {loading
            ? i18n.t('practitioners.input.searching')
            : i18n
                .t('practitioners.input.resultsCount')
                .replace('{count}', String(suggestions.length))}
        </div>
      {/if}

      {#if showCreateOption}
        <button type="button" class="option create" onclick={() => (showSuggestions = false)}>
          <Plus size={16} />
          <span>{i18n.t('practitioners.input.addOption').replace('{value}', value)}</span>
        </button>
      {/if}

      {#each displaySuggestions as practitioner (practitioner.id)}
        <button type="button" class="option" onclick={() => selectPractitioner(practitioner)}>
          <div class="option-icon"><User size={16} /></div>
          <div class="option-body">
            <div class="option-name">
              <span>{practitioner.name}</span>
              {#if practitioner.isTransFriendly}
                <Star size={12} class="star" />
              {/if}
            </div>
            <div class="option-meta">
              <span>{i18n.t('appointments.types.' + practitioner.specialty)}</span>
              {#if practitioner.location}
                <span class="dot">•</span>
                <span class="location"><MapPin size={12} />{practitioner.location}</span>
              {/if}
            </div>
          </div>
        </button>
      {/each}

      {#if value.length >= 2 && suggestions.length === 0 && !loading}
        <div class="empty">{i18n.t('practitioners.input.emptyResults')}</div>
      {/if}
    </div>
  {/if}
</div>

<style>
  .wrap {
    position: relative;
  }
  .input-row {
    position: relative;
  }
  .input-row :global(.input-icon) {
    position: absolute;
    top: 50%;
    left: 11px;
    transform: translateY(-50%);
    color: var(--ink-soft);
  }
  input {
    width: 100%;
    padding: 9px 11px 9px 34px;
    border: 1px solid var(--line);
    border-radius: 9px;
    background: var(--page);
    color: var(--ink);
    font-family: inherit;
    font-size: 13.5px;
  }
  input.linked {
    border-color: var(--blue-deep);
  }
  .dropdown {
    position: absolute;
    z-index: 50;
    top: calc(100% + 4px);
    left: 0;
    right: 0;
    max-height: 260px;
    overflow-y: auto;
    background: var(--bg);
    border: 1px solid var(--line);
    border-radius: 12px;
    box-shadow: 0 20px 50px -18px var(--shadow);
  }
  .dropdown-header {
    padding: 7px 12px;
    font-size: 11px;
    font-weight: 600;
    color: var(--ink-soft);
    background: color-mix(in srgb, var(--line) 40%, transparent);
    border-bottom: 1px solid var(--line);
  }
  .option {
    display: flex;
    align-items: flex-start;
    gap: 10px;
    width: 100%;
    padding: 10px 12px;
    border: none;
    border-bottom: 1px solid var(--line);
    background: transparent;
    color: inherit;
    font-family: inherit;
    text-align: left;
    cursor: pointer;
  }
  .option:last-child {
    border-bottom: none;
  }
  .option:hover {
    background: color-mix(in srgb, var(--line) 40%, transparent);
  }
  .option.create {
    align-items: center;
    color: var(--blue-deep);
  }
  .option-icon {
    flex-shrink: 0;
    background: var(--line);
    border-radius: 8px;
    padding: 6px;
    color: var(--ink-soft);
  }
  .option-body {
    min-width: 0;
    flex: 1;
  }
  .option-name {
    display: flex;
    align-items: center;
    gap: 6px;
    font-size: 13.5px;
    font-weight: 600;
  }
  .option-name :global(.star) {
    color: var(--gold);
    fill: var(--gold);
    flex-shrink: 0;
  }
  .option-meta {
    display: flex;
    align-items: center;
    gap: 6px;
    font-size: 11.5px;
    color: var(--ink-soft);
    margin-top: 2px;
  }
  .option-meta .dot {
    color: var(--ink-faint);
  }
  .option-meta .location {
    display: flex;
    align-items: center;
    gap: 3px;
  }
  .empty {
    padding: 16px 12px;
    text-align: center;
    font-size: 12.5px;
    color: var(--ink-soft);
  }
</style>

// src/components/appointments/practitioner-input.tsx
'use client'

import { useState, useRef, useEffect, useCallback } from 'react'
import { User, Plus, MapPin, Phone, Star } from 'lucide-react'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'
import { searchPractitioners, getPractitioners } from '@/lib/db'
import { useTranslations } from 'next-intl'
import type { Practitioner, AppointmentType } from '@/lib/types'
import { APPOINTMENT_TYPES } from '@/lib/constants'

interface PractitionerInputProps {
  value: string
  onChange: (name: string, practitionerId?: number) => void
  onSelect?: (practitioner: Practitioner) => void
  specialty?: AppointmentType
  placeholder?: string
  className?: string
  id?: string
}

/**
 * Autocomplete input for practitioners
 * Suggests existing practitioners and allows creating new ones
 */
export function PractitionerInput({
  value,
  onChange,
  onSelect,
  specialty,
  placeholder = 'Practitioner name...',
  className,
  id,
}: PractitionerInputProps) {
  const t = useTranslations('appointments')
  const [inputValue, setInputValue] = useState(value)
  const [prevValue, setPrevValue] = useState(value)
  const [showSuggestions, setShowSuggestions] = useState(false)
  const [suggestions, setSuggestions] = useState<Practitioner[]>([])
  const [recentPractitioners, setRecentPractitioners] = useState<Practitioner[]>([])
  const [loading, setLoading] = useState(false)
  const inputRef = useRef<HTMLInputElement>(null)
  const containerRef = useRef<HTMLDivElement>(null)

  // Sync input value with prop (derived during render, no extra effect round-trip)
  if (value !== prevValue) {
    setPrevValue(value)
    setInputValue(value)
  }

  // Load recent practitioners when specialty changes
  useEffect(() => {
    async function loadRecent() {
      const recent = await getPractitioners(specialty)
      setRecentPractitioners(recent.slice(0, 5))
    }
    loadRecent()
  }, [specialty])

  // Search practitioners on input change
  const searchDebounced = useCallback(
    async (query: string) => {
      if (query.length < 2) {
        setSuggestions([])
        return
      }

      setLoading(true)
      try {
        const results = await searchPractitioners(query, specialty)
        setSuggestions(results)
      } finally {
        setLoading(false)
      }
    },
    [specialty]
  )

  // Debounce search
  useEffect(() => {
    const timer = setTimeout(() => {
      searchDebounced(inputValue)
    }, 200)

    return () => clearTimeout(timer)
  }, [inputValue, searchDebounced])

  const selectPractitioner = (practitioner: Practitioner) => {
    setInputValue(practitioner.name)
    onChange(practitioner.name, practitioner.id)
    // Call onSelect with the full practitioner for auto-fill
    if (onSelect) {
      onSelect(practitioner)
    }
    setShowSuggestions(false)
  }

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newValue = e.target.value
    setInputValue(newValue)
    onChange(newValue, undefined) // No ID when typing manually
    setShowSuggestions(true)
  }

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && inputValue) {
      e.preventDefault()
      onChange(inputValue, undefined)
      setShowSuggestions(false)
    } else if (e.key === 'Escape') {
      setShowSuggestions(false)
    }
  }

  // Close suggestions when clicking outside
  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (containerRef.current && !containerRef.current.contains(e.target as Node)) {
        setShowSuggestions(false)
      }
    }
    document.addEventListener('mousedown', handleClickOutside)
    return () => document.removeEventListener('mousedown', handleClickOutside)
  }, [])

  // Show recent or search results
  const displaySuggestions = inputValue.length >= 2 ? suggestions : recentPractitioners
  const showRecent = inputValue.length < 2 && recentPractitioners.length > 0
  const showCreateOption =
    inputValue.length >= 2 &&
    !suggestions.some((p) => p.name.toLowerCase() === inputValue.toLowerCase())

  return (
    <div ref={containerRef} className={cn('relative', className)}>
      <div className="relative">
        <User className="text-muted-foreground absolute top-1/2 left-3 h-4 w-4 -translate-y-1/2" />
        <Input
          ref={inputRef}
          id={id}
          value={inputValue}
          onChange={handleInputChange}
          onFocus={() => setShowSuggestions(true)}
          onKeyDown={handleKeyDown}
          placeholder={placeholder}
          className="pl-9"
        />
      </div>

      {/* Dropdown suggestions */}
      {showSuggestions && (displaySuggestions.length > 0 || showCreateOption || showRecent) && (
        <div className="bg-background border-border absolute z-50 mt-1 max-h-60 w-full overflow-y-auto rounded-lg border shadow-lg">
          {/* Recent practitioners header */}
          {showRecent && (
            <div className="text-muted-foreground bg-muted/30 border-border border-b px-3 py-1.5 text-xs font-medium">
              Praticien·nes récent·es
            </div>
          )}

          {/* Search results header */}
          {inputValue.length >= 2 && suggestions.length > 0 && (
            <div className="text-muted-foreground bg-muted/30 border-border border-b px-3 py-1.5 text-xs font-medium">
              {loading
                ? 'Recherche...'
                : `${suggestions.length} résultat${suggestions.length > 1 ? 's' : ''}`}
            </div>
          )}

          {/* Create new option */}
          {showCreateOption && (
            <button
              type="button"
              className="hover:bg-muted/50 border-border flex w-full items-center gap-2 border-b px-3 py-2.5 text-left text-sm"
              onClick={() => {
                onChange(inputValue, undefined)
                setShowSuggestions(false)
              }}
            >
              <Plus className="text-primary h-4 w-4" />
              <span>{t('practitionerInput.addOption', { value: inputValue })}</span>
            </button>
          )}

          {/* Practitioner list */}
          {displaySuggestions.map((practitioner) => (
            <button
              key={practitioner.id}
              type="button"
              className="hover:bg-muted/50 flex w-full items-start gap-3 px-3 py-2.5 text-left"
              onClick={() => selectPractitioner(practitioner)}
            >
              <div className="bg-muted shrink-0 rounded-lg p-1.5">
                <User className="text-muted-foreground h-4 w-4" />
              </div>
              <div className="min-w-0 flex-1">
                <div className="flex items-center gap-2">
                  <span className="text-foreground truncate text-sm font-medium">
                    {practitioner.name}
                  </span>
                  {practitioner.isTransFriendly && (
                    <Star className="h-3 w-3 shrink-0 fill-yellow-500 text-yellow-500" />
                  )}
                </div>
                <div className="text-muted-foreground mt-0.5 flex items-center gap-2 text-xs">
                  <span>{t('types.' + practitioner.specialty)}</span>
                  {practitioner.location && (
                    <>
                      <span className="text-border">•</span>
                      <span className="flex items-center gap-0.5 truncate">
                        <MapPin className="h-3 w-3 shrink-0" />
                        {practitioner.location}
                      </span>
                    </>
                  )}
                </div>
              </div>
            </button>
          ))}

          {/* Empty state */}
          {inputValue.length >= 2 && suggestions.length === 0 && !loading && (
            <div className="text-muted-foreground px-3 py-4 text-center text-sm">
              Aucun·e praticien·ne trouvé·e
            </div>
          )}
        </div>
      )}
    </div>
  )
}
