// src/lib/components/appointments/YearCalendar.svelte
<script lang="ts">
  import {
    format,
    startOfYear,
    endOfYear,
    eachMonthOfInterval,
    startOfMonth,
    endOfMonth,
    startOfWeek,
    endOfWeek,
    eachDayOfInterval,
    isSameDay,
    isToday,
  } from 'date-fns'
  import type { Locale } from 'date-fns'
  import { SvelteMap, SvelteSet } from 'svelte/reactivity'
  import ChevronLeft from '@lucide/svelte/icons/chevron-left'
  import ChevronRight from '@lucide/svelte/icons/chevron-right'
  import { i18n } from '$lib/i18n.svelte'
  import { APPOINTMENT_TYPES } from '$lib/constants'
  import type { Appointment } from '$lib/types'

  let {
    appointments,
    selectedDate,
    dateLocale,
    onSelectDate,
  }: {
    appointments: Appointment[]
    selectedDate: Date
    dateLocale: Locale
    onSelectDate: (date: Date) => void
  } = $props()

  let year = $state(new Date().getFullYear())

  let months = $derived(
    eachMonthOfInterval({
      start: startOfYear(new Date(year, 0, 1)),
      end: endOfYear(new Date(year, 0, 1)),
    })
  )

  let appointmentsByDate = $derived.by(() => {
    const map = new SvelteMap<string, Appointment[]>()
    for (const apt of appointments) {
      const key = format(new Date(apt.date), 'yyyy-MM-dd')
      const list = map.get(key)
      if (list) {
        list.push(apt)
      } else {
        map.set(key, [apt])
      }
    }
    return map
  })

  let weekdayLabels = $derived(
    eachDayOfInterval({
      start: startOfWeek(new Date(), { weekStartsOn: 1 }),
      end: endOfWeek(new Date(), { weekStartsOn: 1 }),
    }).map((d) => format(d, 'EEEEE', { locale: dateLocale }))
  )

  function monthDays(month: Date) {
    return eachDayOfInterval({ start: startOfMonth(month), end: endOfMonth(month) })
  }

  function dayAppointments(day: Date) {
    return appointmentsByDate.get(format(day, 'yyyy-MM-dd')) ?? []
  }

  function dayColors(day: Date) {
    const colors = new SvelteSet<string>()
    for (const apt of dayAppointments(day)) {
      colors.add(APPOINTMENT_TYPES[apt.type]?.color ?? '#6B7280')
    }
    return [...colors].slice(0, 3)
  }
</script>

<div class="year-nav">
  <button type="button" class="year-btn" onclick={() => (year -= 1)} aria-label="←">
    <ChevronLeft size={18} />
  </button>
  <span class="year-label">{year}</span>
  <button type="button" class="year-btn" onclick={() => (year += 1)} aria-label="→">
    <ChevronRight size={18} />
  </button>
</div>

<div class="legend">
  {#each Object.entries(APPOINTMENT_TYPES) as [type, info] (type)}
    <div class="legend-item">
      <span class="legend-dot" style="background:{info.color}"></span>
      {i18n.t('appointments.types.' + type)}
    </div>
  {/each}
</div>

<div class="months-grid">
  {#each months as month (month.toISOString())}
    <div class="month">
      <p class="month-name">{format(month, 'MMMM', { locale: dateLocale })}</p>
      <div class="weekdays">
        {#each weekdayLabels as label, i (i)}
          <span>{label}</span>
        {/each}
      </div>
      <div class="days">
        {#each Array((startOfMonth(month).getDay() + 6) % 7) as _, i (i)}
          <span class="day empty"></span>
        {/each}
        {#each monthDays(month) as day (day.toISOString())}
          {@const colors = dayColors(day)}
          <button
            type="button"
            class="day"
            class:today={isToday(day)}
            class:selected={isSameDay(day, selectedDate)}
            onclick={() => onSelectDate(day)}
          >
            <span class="day-num" style={colors.length && !isToday(day) ? `color:${colors[0]}` : ''}
              >{format(day, 'd')}</span
            >
            {#if colors.length}
              <span class="dots">
                {#each colors as color (color)}
                  <span class="dot" style="background:{color}"></span>
                {/each}
              </span>
            {/if}
          </button>
        {/each}
      </div>
    </div>
  {/each}
</div>

<style>
  .year-nav {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 10px;
  }
  .year-label {
    font-size: 17px;
    font-weight: 700;
  }
  .year-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 30px;
    height: 30px;
    border: none;
    background: transparent;
    color: var(--ink-soft);
    border-radius: 999px;
    cursor: pointer;
  }
  .year-btn:active {
    background: var(--line);
  }
  .legend {
    display: flex;
    flex-wrap: wrap;
    gap: 8px 12px;
    margin-bottom: 14px;
  }
  .legend-item {
    display: flex;
    align-items: center;
    gap: 5px;
    font-size: 11px;
    color: var(--ink-soft);
  }
  .legend-dot {
    width: 7px;
    height: 7px;
    border-radius: 50%;
    flex-shrink: 0;
  }
  .months-grid {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 10px;
  }
  @media (min-width: 640px) {
    .months-grid {
      grid-template-columns: repeat(3, 1fr);
    }
  }
  .month {
    border: 1px solid var(--line);
    border-radius: 12px;
    padding: 8px;
  }
  .month-name {
    font-size: 12px;
    font-weight: 600;
    text-align: center;
    text-transform: capitalize;
    margin: 0 0 6px;
  }
  .weekdays {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    text-align: center;
    font-size: 8px;
    color: var(--ink-faint);
    text-transform: uppercase;
    margin-bottom: 2px;
  }
  .days {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    gap: 1px;
  }
  .day {
    aspect-ratio: 1;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    border: none;
    background: transparent;
    color: var(--ink);
    font-size: 9px;
    font-family: inherit;
    border-radius: 4px;
    cursor: pointer;
    padding: 0;
  }
  .day.empty {
    cursor: default;
  }
  .day.today .day-num {
    font-weight: 700;
    color: var(--blue-deep);
  }
  .day.selected {
    background: linear-gradient(135deg, var(--blue-deep), var(--pink-deep));
  }
  .day.selected .day-num {
    color: #fff !important;
  }
  .dots {
    display: flex;
    gap: 1px;
    margin-top: 1px;
  }
  .dot {
    width: 3px;
    height: 3px;
    border-radius: 50%;
  }
</style>

// src/components/appointments/year-calendar.tsx
'use client'

import { useState, useMemo } from 'react'
import {
  format,
  startOfYear,
  endOfYear,
  eachMonthOfInterval,
  startOfMonth,
  endOfMonth,
  eachDayOfInterval,
  isSameMonth,
  isSameDay,
  isToday,
  getDay,
} from 'date-fns'
import { ChevronLeft, ChevronRight } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { useTranslations, useLocale } from 'next-intl'
import { getDateLocale } from '@/i18n/date-locale'
import type { Locale } from '@/i18n/config'
import { cn } from '@/lib/utils'
import { APPOINTMENT_TYPES } from '@/lib/constants'
import type { Appointment, AppointmentType } from '@/lib/types'

interface YearCalendarProps {
  appointments: Appointment[]
  onDayClick?: (date: Date, dayAppointments: Appointment[]) => void
  onAppointmentClick?: (appointment: Appointment) => void
}

// Days of the week (starts Monday)
const WEEKDAYS = ['L', 'M', 'M', 'J', 'V', 'S', 'D']

/**
 * Year calendar - 12-month grid (4x3)
 * Displays appointments with color-coded indicators by type
 */
export function YearCalendar({ appointments, onDayClick, onAppointmentClick }: YearCalendarProps) {
  const t = useTranslations('appointments')
  const [year, setYear] = useState(new Date().getFullYear())

  // Compute the months of the year
  const yearStart = startOfYear(new Date(year, 0, 1))
  const yearEnd = endOfYear(new Date(year, 0, 1))
  const months = eachMonthOfInterval({ start: yearStart, end: yearEnd })

  // Index appointments by date for fast access
  const appointmentsByDate = useMemo(() => {
    const map = new Map<string, Appointment[]>()
    appointments.forEach((apt) => {
      const dateKey = format(new Date(apt.date), 'yyyy-MM-dd')
      if (!map.has(dateKey)) {
        map.set(dateKey, [])
      }
      map.get(dateKey)!.push(apt)
    })
    return map
  }, [appointments])

  const navigateYear = (delta: number) => {
    setYear((y) => y + delta)
  }

  return (
    <div className="space-y-4">
      {/* Year navigation */}
      <div className="flex items-center justify-between">
        <Button variant="ghost" size="icon" onClick={() => navigateYear(-1)} className="shrink-0">
          <ChevronLeft className="h-5 w-5" />
        </Button>
        <h2 className="text-foreground text-xl font-bold">{year}</h2>
        <Button variant="ghost" size="icon" onClick={() => navigateYear(1)} className="shrink-0">
          <ChevronRight className="h-5 w-5" />
        </Button>
      </div>

      {/* Legend */}
      <div className="flex flex-wrap gap-2 text-xs">
        {Object.entries(APPOINTMENT_TYPES).map(([type, info]) => (
          <div key={type} className="flex items-center gap-1">
            <div className="h-2 w-2 rounded-full" style={{ backgroundColor: info.color }} />
            <span className="text-muted-foreground">{t('types.' + type)}</span>
          </div>
        ))}
      </div>

      {/* Month grid (4 columns x 3 rows) */}
      <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">
        {months.map((month) => (
          <MonthMiniCalendar
            key={month.toISOString()}
            month={month}
            appointmentsByDate={appointmentsByDate}
            onDayClick={onDayClick}
          />
        ))}
      </div>
    </div>
  )
}

// Mini calendar for a month
function MonthMiniCalendar({
  month,
  appointmentsByDate,
  onDayClick,
}: {
  month: Date
  appointmentsByDate: Map<string, Appointment[]>
  onDayClick?: (date: Date, appointments: Appointment[]) => void
}) {
  const locale = useLocale()
  const dateLocale = getDateLocale(locale as Locale)
  const monthStart = startOfMonth(month)
  const monthEnd = endOfMonth(month)
  const days = eachDayOfInterval({ start: monthStart, end: monthEnd })

  // Offset for the first day (0 = Sunday, we want to start on Monday)
  const firstDayOffset = (getDay(monthStart) + 6) % 7

  return (
    <div className="bg-card border-border rounded-lg border p-2">
      {/* Month name */}
      <h3 className="text-foreground mb-2 text-center text-sm font-medium capitalize">
        {format(month, 'MMMM', { locale: dateLocale })}
      </h3>

      {/* Weekday headers */}
      <div className="mb-1 grid grid-cols-7 gap-0.5">
        {WEEKDAYS.map((day, i) => (
          <div key={i} className="text-muted-foreground text-center text-[9px] font-medium">
            {day}
          </div>
        ))}
      </div>

      {/* Days */}
      <div className="grid grid-cols-7 gap-0.5">
        {/* Empty cells for the offset */}
        {Array.from({ length: firstDayOffset }).map((_, i) => (
          <div key={`empty-${i}`} className="aspect-square" />
        ))}

        {/* Days of the month */}
        {days.map((day) => {
          const dateKey = format(day, 'yyyy-MM-dd')
          const dayAppointments = appointmentsByDate.get(dateKey) || []
          const hasAppointments = dayAppointments.length > 0
          const today = isToday(day)

          // Get the unique colors of the day's appointments
          const appointmentColors = [
            ...new Set(
              dayAppointments.map((apt) => APPOINTMENT_TYPES[apt.type]?.color || '#6B7280')
            ),
          ].slice(0, 3) // Max 3 indicators

          return (
            <button
              key={day.toISOString()}
              onClick={() => onDayClick?.(day, dayAppointments)}
              className={cn(
                'relative flex aspect-square flex-col items-center justify-center rounded text-[10px]',
                'hover:bg-muted/50 transition-colors',
                today && 'bg-primary/20 font-bold',
                hasAppointments && 'font-medium'
              )}
            >
              <span
                className={cn(today && 'text-primary')}
                style={hasAppointments && !today ? { color: appointmentColors[0] } : undefined}
              >
                {format(day, 'd')}
              </span>

              {/* Appointment indicators */}
              {hasAppointments && (
                <div className="mt-0.5 flex gap-0.5">
                  {appointmentColors.map((color, i) => (
                    <div
                      key={i}
                      className="h-1 w-1 rounded-full"
                      style={{ backgroundColor: color }}
                    />
                  ))}
                </div>
              )}
            </button>
          )
        })}
      </div>
    </div>
  )
}
